export const FORESHADOWING_MAX_SENTENCES = 4;
export const FORESHADOWING_MIN_SENTENCES = 2;

export const INTEL_TIER_UNKNOWN_BELOW = 10;
export const INTEL_TIER_RUMOR_BELOW = 30;
export const INTEL_TIER_BRIEFED_BELOW = 70;

export const INTERVENTION_ATTRIBUTION_WINDOW = 12;
export const FORESHADOWING_CACHE_MAX_ENTRIES = 256;
