import type { ArchetypeDef } from './types';

export const SETTLEMENT_ARCHETYPES: ArchetypeDef[] = [
  {
    id: 'garrison-town',
    name: 'Garrison Town',
    requiredTags: [{ tag: 'military', count: 3 }],
    capstoneSublocations: ['sublocation-type.siege-stores'],
    capstoneNpcs: ['commander'],
    proseFlavor: 'a town that exists to hold the line',
    priority: 50,
  },
  {
    id: 'arcane-conclave',
    name: 'Arcane Conclave',
    requiredTags: [{ tag: 'scholarly', count: 2 }, { tag: 'arcane', count: 1 }],
    capstoneSublocations: ['sublocation-type.arcane-council-chamber'],
    capstoneNpcs: ['researcher'],
    proseFlavor: 'where knowledge is hoarded and secrets traded',
    priority: 40,
  },
  {
    id: 'trade-nexus',
    name: 'Trade Nexus',
    requiredTags: [{ tag: 'commerce', count: 3 }],
    capstoneSublocations: ['sublocation-type.merchant-prince-hall'],
    capstoneNpcs: ['broker'],
    proseFlavor: 'the sound of coin never stops',
    priority: 45,
  },
  {
    id: 'holy-seat',
    name: 'Holy Seat',
    requiredTags: [{ tag: 'religious', count: 2 }, { tag: 'cultural', count: 1 }],
    capstoneSublocations: ['sublocation-type.cathedral', 'sublocation-type.pilgrim-quarter'],
    capstoneNpcs: ['priest'],
    proseFlavor: 'faith made stone',
    priority: 35,
  },
  {
    id: 'thieves-haven',
    name: "Thieves' Haven",
    requiredTags: [{ tag: 'underworld', count: 2 }, { tag: 'commerce', count: 1 }],
    capstoneSublocations: ['sublocation-type.hidden-court'],
    capstoneNpcs: ['fence'],
    proseFlavor: "two economies — one you see, one you don't",
    priority: 30,
  },
  {
    id: 'frontier-bastion',
    name: 'Frontier Bastion',
    requiredTags: [{ tag: 'military', count: 2 }, { tag: 'borderlands', count: 1 }],
    capstoneSublocations: ['sublocation-type.reinforced-keep', 'sublocation-type.refugee-quarter'],
    capstoneNpcs: ['guard'],
    proseFlavor: 'the last safe place before the wild',
    priority: 55,
  },
  {
    id: 'nature-sanctuary',
    name: 'Nature Sanctuary',
    requiredTags: [{ tag: 'nature', count: 2 }, { tag: 'cultural', count: 1 }],
    capstoneSublocations: ['sublocation-type.ancient-grove', 'sublocation-type.beast-pen'],
    capstoneNpcs: ['hermit'],
    proseFlavor: 'the land speaks here, and they listen',
    priority: 25,
  },
  {
    id: 'seat-of-power',
    name: 'Seat of Power',
    requiredTags: [{ tag: 'authority', count: 2 }, { tag: 'military', count: 1 }],
    capstoneSublocations: ['sublocation-type.high-court', 'sublocation-type.royal-guard-quarters'],
    capstoneNpcs: ['noble'],
    proseFlavor: 'power flows downhill from these walls',
    priority: 60,
  },
];
