import type { ReachDomain } from './traits';
import type { SocialOrientation } from './disposition';

/** Axiological value pairs (from the Axiological Motivation Engine design) */
export type ValuePair =
  | 'ambition_contentment'
  | 'courage_prudence'
  | 'cruelty_compassion'
  | 'cunning_honesty'
  | 'devotion_independence'
  | 'loyalty_treachery'
  | 'tradition_innovation'
  | 'dominance_humility'
  | 'wrath_patience'
  | 'greed_generosity';

/** Actor's axiological profile: each value from -1.0 (right pole) to +1.0 (left pole) */
export type AxiologicalProfile = Record<ValuePair, number>;

/** An action candidate generated by the pipeline */
export interface ActionCandidate {
  templateId: string;
  targetId: string;
  domain: ReachDomain;
  score: number;               // computed alignment score
  motivations: ValuePair[];    // which values drive this choice
  probability?: number;        // normalized probability (post top-N)
  socialOrientation?: SocialOrientation;  // cooperative/defective/neutral bias
}

/** Configuration for the selection pipeline */
export interface SelectionConfig {
  topN: number;                // how many candidates to keep (3-5)
  survivalThreshold: number;   // threat level that triggers survival layer
}

/** Result of the selection pipeline */
export interface SelectionResult {
  selected: ActionCandidate;
  candidates: ActionCandidate[];  // the top-N candidates with probabilities
  wasSurvivalOverride: boolean;
}
