import type { ReachDomain } from './traits';
import type { SocialOrientation } from './disposition';

/**
 * Canonical axiological value pairs — one per Reach domain + one meta pair.
 * Convention: +1.0 = virtue/first pole, -1.0 = flaw/second pole.
 * Source: Obsidian → TheFantasyWorldSimulator/Domains/Axiological Pairs.md
 */
export type ValuePair =
  | 'mercy_ruthlessness'       // Iron   — Mercy (+1) vs Ruthlessness (-1)
  | 'asceticism_extravagance'  // Gold   — Asceticism (+1) vs Extravagance (-1)
  | 'honesty_cunning'          // Shadow — Honesty (+1) vs Cunning (-1)
  | 'tradition_novelty'        // Veil   — Tradition (+1) vs Novelty (-1)
  | 'loyalty_ambition'         // Heart  — Loyalty (+1) vs Ambition (-1)
  | 'frankness_propriety'      // Eye    — Frankness (+1) vs Propriety (-1)
  | 'humility_pride'           // Stone  — Humility (+1) vs Pride (-1)
  | 'sacrifice_survival'       // Star   — Sacrifice (+1) vs Survival (-1)
  | 'stoicism_passion'         // Flesh  — Stoicism (+1) vs Passion (-1)
  | 'courage_prudence';        // Meta   — Courage (+1) vs Prudence (-1)

/** Actor's axiological profile: +1.0 = virtue (first pole), -1.0 = flaw (second pole) */
export type AxiologicalProfile = Record<ValuePair, number>;

/** Canonical list of all value pairs (array form for iteration) */
export const VALUE_PAIRS: readonly ValuePair[] = [
  'mercy_ruthlessness',
  'asceticism_extravagance',
  'honesty_cunning',
  'tradition_novelty',
  'loyalty_ambition',
  'frankness_propriety',
  'humility_pride',
  'sacrifice_survival',
  'stoicism_passion',
  'courage_prudence',
] as const;

/** Maps each reach domain to its bound axiological pair */
export const REACH_VALUE_PAIR: Record<ReachDomain, ValuePair> = {
  iron:   'mercy_ruthlessness',
  gold:   'asceticism_extravagance',
  shadow: 'honesty_cunning',
  veil:   'tradition_novelty',
  heart:  'loyalty_ambition',
  eye:    'frankness_propriety',
  stone:  'humility_pride',
  star:   'sacrifice_survival',
  flesh:  'stoicism_passion',
};

/** The meta pair (not reach-bound) */
export const META_VALUE_PAIR: ValuePair = 'courage_prudence';

/** An action candidate generated by the pipeline */
export interface ActionCandidate {
  templateId: string;
  targetId: string;
  domain: ReachDomain;
  score: number;               // computed alignment score
  motivations: ValuePair[];    // which values drive this choice
  probability?: number;        // normalized probability (post top-N)
  socialOrientation?: SocialOrientation;  // cooperative/defective/neutral bias
  sublocationId?: string;      // selected sublocation instance (if any)
}

/** Configuration for the selection pipeline */
export interface SelectionConfig {
  topN: number;                // how many candidates to keep (3-5)
  survivalThreshold: number;   // threat level that triggers survival layer
}

/** Result of the selection pipeline */
export interface SelectionResult {
  selected: ActionCandidate;
  candidates: ActionCandidate[];  // the top-N candidates with probabilities
  wasSurvivalOverride: boolean;
}
