import type { ReachDomain } from './traits';
import type { SocialOrientation } from './disposition';

/**
 * Canonical axiological value pairs — one per Reach domain + one meta pair.
 * Convention: +1.0 = virtue/first pole, -1.0 = flaw/second pole.
 * Source: Obsidian → TheFantasyWorldSimulator/Domains/Axiological Pairs.md
 */
export type ValuePair =
  | 'mercy_ruthlessness'           // Iron   — Protector (+1) vs Conqueror (-1)
  | 'asceticism_extravagance'      // Gold   — Mender (+1) vs Magnate (-1)
  | 'honesty_cunning'              // Shadow — Confessor (+1) vs Puppeteer (-1)
  | 'tradition_novelty'            // Veil   — Archivist (+1) vs Heretic (-1)
  | 'loyalty_ambition'             // Heart  — Sworn (+1) vs Renegade (-1)
  | 'revelation_discretion'        // Eye    — Seeker (+1) vs Sentinel (-1)
  | 'preservation_transformation'  // Stone  — Guardian (+1) vs Shaper (-1)
  | 'sacrifice_survival'           // Star   — Martyr (+1) vs Survivor (-1)
  | 'courage_prudence';            // Meta   — Vanguard (+1) vs Watcher (-1)
  // Removed in TB-075 Phase 1: frankness_propriety (Eye), humility_pride (Stone), stoicism_passion (Flesh)

/** Actor's axiological profile: +1.0 = virtue (first pole), -1.0 = flaw (second pole) */
export type AxiologicalProfile = Record<ValuePair, number>;

/** Canonical list of all value pairs (array form for iteration) */
export const VALUE_PAIRS: readonly ValuePair[] = [
  'mercy_ruthlessness',
  'asceticism_extravagance',
  'honesty_cunning',
  'tradition_novelty',
  'loyalty_ambition',
  'revelation_discretion',
  'preservation_transformation',
  'sacrifice_survival',
  'courage_prudence',
] as const;

/** Maps each reach domain to its bound axiological pair */
export const REACH_VALUE_PAIR: Record<ReachDomain, ValuePair> = {
  iron:   'mercy_ruthlessness',
  gold:   'asceticism_extravagance',
  shadow: 'honesty_cunning',
  veil:   'tradition_novelty',
  heart:  'loyalty_ambition',
  eye:    'revelation_discretion',
  stone:  'preservation_transformation',
  star:   'sacrifice_survival',
};

/** The meta pair (not reach-bound) */
export const META_VALUE_PAIR: ValuePair = 'courage_prudence';

/** Archetype names for each value pair (positive = virtue pole, negative = flaw pole) */
export const ARCHETYPE_NAMES: Record<ValuePair, { positive: string; negative: string }> = {
  mercy_ruthlessness:           { positive: 'Protector',  negative: 'Conqueror' },
  asceticism_extravagance:      { positive: 'Mender',     negative: 'Magnate' },
  honesty_cunning:              { positive: 'Confessor',  negative: 'Puppeteer' },
  tradition_novelty:            { positive: 'Archivist',  negative: 'Heretic' },
  loyalty_ambition:             { positive: 'Sworn',      negative: 'Renegade' },
  revelation_discretion:        { positive: 'Seeker',     negative: 'Sentinel' },
  preservation_transformation:  { positive: 'Guardian',   negative: 'Shaper' },
  sacrifice_survival:           { positive: 'Martyr',     negative: 'Survivor' },
  courage_prudence:             { positive: 'Vanguard',   negative: 'Watcher' },
};

// ─── Reputation Tallies ─────────────────────────────────────────

/** Per-reach, per-polarity reputation accumulation counters.
 * Stored on actor node properties as `reputationTallies`.
 * Incremented by encounter completions, decayed each tick. */
export type ReputationTallyKey = `${ReachDomain}.${'positive' | 'negative'}`;
export type ReputationTallies = Partial<Record<ReputationTallyKey, number>>;

/** An action candidate generated by the pipeline */
export interface ActionCandidate {
  templateId: string;
  targetId: string;
  domain: ReachDomain;
  score: number;               // computed alignment score
  motivations: ValuePair[];    // which values drive this choice
  probability?: number;        // normalized probability (post top-N)
  socialOrientation?: SocialOrientation;  // cooperative/defective/neutral bias
  sublocationId?: string;      // selected sublocation instance (if any)
}

/** Configuration for the selection pipeline */
export interface SelectionConfig {
  topN: number;                // how many candidates to keep (3-5)
  survivalThreshold: number;   // threat level that triggers survival layer
}

/** Result of the selection pipeline */
export interface SelectionResult {
  selected: ActionCandidate;
  candidates: ActionCandidate[];  // the top-N candidates with probabilities
  wasSurvivalOverride: boolean;
}
