/**
 * The Assize Letter — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { ASSIZE_LETTER_TEMPLATE } from '../assize-letter';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Assize Letter — template structure", () => {
  it('carries its identity', () => {
    expect(ASSIZE_LETTER_TEMPLATE.id).toBe('encounter.town.assize_letter');
    expect(ASSIZE_LETTER_TEMPLATE.reach).toBe('star');
    expect(ASSIZE_LETTER_TEMPLATE.rarityTier).toBe(2);
    expect(ASSIZE_LETTER_TEMPLATE.steps).toHaveLength(1);
  });

  it('step 0 deals the authored hand', () => {
    const step = ASSIZE_LETTER_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['assize.draw_down_the_river', 'assize.lengthen_the_day']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(ASSIZE_LETTER_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(ASSIZE_LETTER_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(ASSIZE_LETTER_TEMPLATE.consequenceDraw).toEqual(['knowledge', 'movement']);
    expect(ASSIZE_LETTER_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.assize_letter',
          reach: 'star',
          rarityTier: 2,
        }),
        ASSIZE_LETTER_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
