/**
 * The Last Lot at the Exchange — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { BELL_AT_THE_EXCHANGE_TEMPLATE } from '../bell-at-the-exchange';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Last Lot at the Exchange — template structure", () => {
  it('carries its identity', () => {
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.id).toBe('encounter.town.bell_at_the_exchange');
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.reach).toBe('gold');
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.rarityTier).toBe(2);
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = BELL_AT_THE_EXCHANGE_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bell.remember_the_price']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = BELL_AT_THE_EXCHANGE_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bell.cloud_the_count', 'bell.hold_the_bell']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.settings).toEqual(['urban']);
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.consequenceDraw).toEqual(['possession', 'story_seed']);
    expect(BELL_AT_THE_EXCHANGE_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.bell_at_the_exchange',
          reach: 'gold',
          rarityTier: 2,
        }),
        BELL_AT_THE_EXCHANGE_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
