/**
 * The Leaning Bell Tower — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { BELL_TOWER_SHORING_TEMPLATE } from '../bell-tower-shoring';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Leaning Bell Tower — template structure", () => {
  it('carries its identity', () => {
    expect(BELL_TOWER_SHORING_TEMPLATE.id).toBe('encounter.town.bell_tower_shoring');
    expect(BELL_TOWER_SHORING_TEMPLATE.reach).toBe('stone');
    expect(BELL_TOWER_SHORING_TEMPLATE.rarityTier).toBe(2);
    expect(BELL_TOWER_SHORING_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = BELL_TOWER_SHORING_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bell.show_the_hidden', 'bell.slow_the_settling']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'time']);
  });

  it('step 1 deals the authored hand', () => {
    const step = BELL_TOWER_SHORING_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bell.stir_old_pride', 'bell.press_the_wall']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force', 'spirit']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(BELL_TOWER_SHORING_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(BELL_TOWER_SHORING_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(BELL_TOWER_SHORING_TEMPLATE.consequenceDraw).toEqual(['possession', 'knowledge']);
    expect(BELL_TOWER_SHORING_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.bell_tower_shoring',
          reach: 'stone',
          rarityTier: 2,
        }),
        BELL_TOWER_SHORING_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
