/**
 * The Border Levy — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { BORDER_LEVY_TEMPLATE } from '../border-levy';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';

describe("The Border Levy — template structure", () => {
  it('carries its identity', () => {
    expect(BORDER_LEVY_TEMPLATE.id).toBe('encounter.realm.border_levy');
    expect(BORDER_LEVY_TEMPLATE.reach).toBe('iron');
    expect(BORDER_LEVY_TEMPLATE.rarityTier).toBe(2);
    expect(BORDER_LEVY_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = BORDER_LEVY_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['levy.recall_the_tally', 'levy.raise_the_murmur']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'time']);
  });

  it('step 1 deals the authored hand', () => {
    const step = BORDER_LEVY_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['levy.loosen_the_post']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(BORDER_LEVY_TEMPLATE.settings).toEqual(['wayside', 'rural']);
    expect(BORDER_LEVY_TEMPLATE.locationSubtypes).toEqual(expandSettings(['wayside', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(BORDER_LEVY_TEMPLATE.consequenceDraw).toEqual(['thread', 'drive']);
    expect(BORDER_LEVY_TEMPLATE.consequenceDraw).toEqual(
      drawConsequenceHand({
        templateId: 'encounter.realm.border_levy',
        reach: 'iron',
        rarityTier: 2,
      }),
    );
  });
});
