/**
 * The Boundary Survey — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { BOUNDARY_SURVEY_TEMPLATE } from '../boundary-survey';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Boundary Survey — template structure", () => {
  it('carries its identity', () => {
    expect(BOUNDARY_SURVEY_TEMPLATE.id).toBe('encounter.town.boundary_survey');
    expect(BOUNDARY_SURVEY_TEMPLATE.reach).toBe('eye');
    expect(BOUNDARY_SURVEY_TEMPLATE.rarityTier).toBe(2);
    expect(BOUNDARY_SURVEY_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = BOUNDARY_SURVEY_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bounds.quicken_the_turf', 'bounds.loose_the_wind']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'life']);
  });

  it('step 1 deals the authored hand', () => {
    const step = BOUNDARY_SURVEY_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bounds.call_up_the_oath', 'bounds.walk_the_old_line']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'order']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(BOUNDARY_SURVEY_TEMPLATE.settings).toEqual(['rural']);
    expect(BOUNDARY_SURVEY_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(BOUNDARY_SURVEY_TEMPLATE.consequenceDraw).toEqual(['possession', 'knowledge']);
    expect(BOUNDARY_SURVEY_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.boundary_survey',
          reach: 'eye',
          rarityTier: 2,
        }),
        BOUNDARY_SURVEY_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
