/**
 * The Vault Before the Rains — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { CATHEDRAL_VAULT_TEMPLATE } from '../cathedral-vault';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Vault Before the Rains — template structure", () => {
  it('carries its identity', () => {
    expect(CATHEDRAL_VAULT_TEMPLATE.id).toBe('encounter.town.cathedral_vault');
    expect(CATHEDRAL_VAULT_TEMPLATE.reach).toBe('stone');
    expect(CATHEDRAL_VAULT_TEMPLATE.rarityTier).toBe(2);
    expect(CATHEDRAL_VAULT_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = CATHEDRAL_VAULT_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['vault.hurry_the_season', 'vault.show_the_hairline']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(CATHEDRAL_VAULT_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(CATHEDRAL_VAULT_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(CATHEDRAL_VAULT_TEMPLATE.consequenceDraw).toEqual(['relationship', 'place']);
    expect(CATHEDRAL_VAULT_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.cathedral_vault',
          reach: 'stone',
          rarityTier: 2,
        }),
        CATHEDRAL_VAULT_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
