/**
 * The Cathedral Loan — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { CATHEDRAL_LOAN_TEMPLATE } from '../cathedral-loan';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Cathedral Loan — template structure", () => {
  it('carries its identity', () => {
    expect(CATHEDRAL_LOAN_TEMPLATE.id).toBe('encounter.town.cathedral_loan');
    expect(CATHEDRAL_LOAN_TEMPLATE.reach).toBe('gold');
    expect(CATHEDRAL_LOAN_TEMPLATE.rarityTier).toBe(2);
    expect(CATHEDRAL_LOAN_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = CATHEDRAL_LOAN_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['cathedral.slow_the_loading', 'cathedral.dull_the_silver']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'order']);
  });

  it('step 1 deals the authored hand', () => {
    const step = CATHEDRAL_LOAN_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['cathedral.plant_the_fear', 'cathedral.open_the_ledger']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(CATHEDRAL_LOAN_TEMPLATE.settings).toEqual(['urban']);
    expect(CATHEDRAL_LOAN_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(CATHEDRAL_LOAN_TEMPLATE.consequenceDraw).toEqual(['relationship', 'possession']);
    expect(CATHEDRAL_LOAN_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.cathedral_loan',
          reach: 'gold',
          rarityTier: 2,
        }),
        CATHEDRAL_LOAN_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
