/**
 * False Coin at the Mint — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { COINERS_MINT_TEMPLATE } from '../coiners-mint';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("False Coin at the Mint — template structure", () => {
  it('carries its identity', () => {
    expect(COINERS_MINT_TEMPLATE.id).toBe('encounter.town.coiners_mint');
    expect(COINERS_MINT_TEMPLATE.reach).toBe('shadow');
    expect(COINERS_MINT_TEMPLATE.rarityTier).toBe(2);
    expect(COINERS_MINT_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = COINERS_MINT_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['coin.loosen_a_tongue', 'coin.stir_a_banked_fire']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['energy', 'mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = COINERS_MINT_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['coin.hold_the_door_shut', 'coin.harden_a_kind_heart']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(COINERS_MINT_TEMPLATE.settings).toEqual(['urban']);
    expect(COINERS_MINT_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(COINERS_MINT_TEMPLATE.consequenceDraw).toEqual(['standing', 'possession']);
    expect(COINERS_MINT_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.coiners_mint',
          reach: 'shadow',
          rarityTier: 2,
        }),
        COINERS_MINT_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
