/**
 * The Comet Disputation — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { COMET_DISPUTATION_TEMPLATE } from '../comet-disputation';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Comet Disputation — template structure", () => {
  it('carries its identity', () => {
    expect(COMET_DISPUTATION_TEMPLATE.id).toBe('encounter.town.comet_disputation');
    expect(COMET_DISPUTATION_TEMPLATE.reach).toBe('star');
    expect(COMET_DISPUTATION_TEMPLATE.rarityTier).toBe(2);
    expect(COMET_DISPUTATION_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = COMET_DISPUTATION_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['comet.part_the_clouds', 'comet.slow_the_hours']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(COMET_DISPUTATION_TEMPLATE.settings).toEqual(['urban']);
    expect(COMET_DISPUTATION_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(COMET_DISPUTATION_TEMPLATE.consequenceDraw).toEqual(['secret', 'drive']);
    expect(COMET_DISPUTATION_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.comet_disputation',
          reach: 'star',
          rarityTier: 2,
        }),
        COMET_DISPUTATION_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
