/**
 * The Counting-House Dispute — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { COUNTING_HOUSE_DISPUTE_TEMPLATE } from '../counting-house-dispute';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Counting-House Dispute — template structure", () => {
  it('carries its identity', () => {
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.id).toBe('encounter.town.counting_house_dispute');
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.reach).toBe('gold');
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.rarityTier).toBe(2);
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = COUNTING_HOUSE_DISPUTE_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['counting.reveal_the_cost', 'counting.weigh_the_purse']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['life', 'matter']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.settings).toEqual(['urban']);
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.consequenceDraw).toEqual(['knowledge', 'secret']);
    expect(COUNTING_HOUSE_DISPUTE_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.counting_house_dispute',
          reach: 'gold',
          rarityTier: 2,
        }),
        COUNTING_HOUSE_DISPUTE_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
