/**
 * The Crown's Summons — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { COURT_SUMMONS_TEMPLATE } from '../court-summons';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';

describe("The Crown's Summons — template structure", () => {
  it('carries its identity', () => {
    expect(COURT_SUMMONS_TEMPLATE.id).toBe('encounter.realm.court_summons');
    expect(COURT_SUMMONS_TEMPLATE.reach).toBe('gold');
    expect(COURT_SUMMONS_TEMPLATE.rarityTier).toBe(2);
    expect(COURT_SUMMONS_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = COURT_SUMMONS_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['summons.weigh_the_hall', 'summons.warm_the_crier']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'order']);
  });

  it('step 1 deals the authored hand', () => {
    const step = COURT_SUMMONS_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['summons.dull_the_echo']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['darkness']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(COURT_SUMMONS_TEMPLATE.settings).toEqual(['urban', 'stronghold']);
    expect(COURT_SUMMONS_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'stronghold']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(COURT_SUMMONS_TEMPLATE.consequenceDraw).toEqual(['possession', 'movement']);
    expect(COURT_SUMMONS_TEMPLATE.consequenceDraw).toEqual(
      drawConsequenceHand({
        templateId: 'encounter.realm.court_summons',
        reach: 'gold',
        rarityTier: 2,
      }),
    );
  });
});
