/**
 * The Crown's Reckoning — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { CROWNS_RECKONING_TEMPLATE } from '../crowns-reckoning';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';

describe("The Crown's Reckoning — template structure", () => {
  it('carries its identity', () => {
    expect(CROWNS_RECKONING_TEMPLATE.id).toBe('encounter.realm.crowns_reckoning');
    expect(CROWNS_RECKONING_TEMPLATE.reach).toBe('iron');
    expect(CROWNS_RECKONING_TEMPLATE.rarityTier).toBe(2);
    expect(CROWNS_RECKONING_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = CROWNS_RECKONING_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['reckoning.harden_the_muster', 'reckoning.quiet_the_fear']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force', 'spirit']);
  });

  it('step 1 deals the authored hand', () => {
    const step = CROWNS_RECKONING_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['reckoning.recall_the_border']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(CROWNS_RECKONING_TEMPLATE.settings).toEqual(['urban', 'stronghold']);
    expect(CROWNS_RECKONING_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'stronghold']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    // The id draws [membership, omen]; the ONE recorded swap (THR-1145) holds the
    // template to [standing, omen] — `check:encounter` recomputes the post-swap hand,
    // so this pins both halves: the drawn hand and the swap that moved it.
    expect(
      drawConsequenceHand({
        templateId: 'encounter.realm.crowns_reckoning',
        reach: 'iron',
        rarityTier: 2,
      }),
    ).toEqual(['membership', 'omen']);
    expect(CROWNS_RECKONING_TEMPLATE.consequenceSwap).toMatchObject({ from: 'membership', to: 'standing' });
    expect(CROWNS_RECKONING_TEMPLATE.consequenceDraw).toEqual(['standing', 'omen']);
  });
});
