/**
 * The Widow's Dream — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { CUNNING_FAIR_TEMPLATE } from '../cunning-fair';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Widow's Dream — template structure", () => {
  it('carries its identity', () => {
    expect(CUNNING_FAIR_TEMPLATE.id).toBe('encounter.town.cunning_fair');
    expect(CUNNING_FAIR_TEMPLATE.reach).toBe('veil');
    expect(CUNNING_FAIR_TEMPLATE.rarityTier).toBe(2);
    expect(CUNNING_FAIR_TEMPLATE.steps).toHaveLength(1);
  });

  it('step 0 deals the authored hand', () => {
    const step = CUNNING_FAIR_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['cunning.borrow_her_sleep', 'cunning.rattle_the_flue']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(CUNNING_FAIR_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(CUNNING_FAIR_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(CUNNING_FAIR_TEMPLATE.consequenceDraw).toEqual(['secret', 'thread']);
    expect(CUNNING_FAIR_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.cunning_fair',
          reach: 'veil',
          rarityTier: 2,
        }),
        CUNNING_FAIR_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
