/**
 * The Debt Arbitration — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { DEBT_ARBITRATION_TEMPLATE } from '../debt-arbitration';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Debt Arbitration — template structure", () => {
  it('carries its identity', () => {
    expect(DEBT_ARBITRATION_TEMPLATE.id).toBe('encounter.town.debt_arbitration');
    expect(DEBT_ARBITRATION_TEMPLATE.reach).toBe('gold');
    expect(DEBT_ARBITRATION_TEMPLATE.rarityTier).toBe(2);
    expect(DEBT_ARBITRATION_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = DEBT_ARBITRATION_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['debt.stoke_the_grievance', 'debt.counsel_patience']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'spirit']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(DEBT_ARBITRATION_TEMPLATE.settings).toEqual(['urban']);
    expect(DEBT_ARBITRATION_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(DEBT_ARBITRATION_TEMPLATE.consequenceDraw).toEqual(['possession', 'knowledge']);
    expect(DEBT_ARBITRATION_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.debt_arbitration',
          reach: 'gold',
          rarityTier: 2,
        }),
        DEBT_ARBITRATION_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
