/**
 * The Drowned Man's Will — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { DROWNED_MANS_TESTIMONY_TEMPLATE } from '../drowned-mans-testimony';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Drowned Man's Will — template structure", () => {
  it('carries its identity', () => {
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.id).toBe('encounter.town.drowned_mans_testimony');
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.reach).toBe('veil');
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.rarityTier).toBe(2);
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.steps).toHaveLength(1);
  });

  it('step 0 deals the authored hand', () => {
    const step = DROWNED_MANS_TESTIMONY_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['testimony.loosen_the_rivals_tongue', 'testimony.call_up_the_dead']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'entropy']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.consequenceDraw).toEqual(['thread', 'drive']);
    expect(DROWNED_MANS_TESTIMONY_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.drowned_mans_testimony',
          reach: 'veil',
          rarityTier: 2,
        }),
        DROWNED_MANS_TESTIMONY_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
