/**
 * The Duke's Nativity — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { DUCAL_NATIVITY_TEMPLATE } from '../ducal-nativity';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Duke's Nativity — template structure", () => {
  it('carries its identity', () => {
    expect(DUCAL_NATIVITY_TEMPLATE.id).toBe('encounter.town.ducal_nativity');
    expect(DUCAL_NATIVITY_TEMPLATE.reach).toBe('star');
    expect(DUCAL_NATIVITY_TEMPLATE.rarityTier).toBe(2);
    expect(DUCAL_NATIVITY_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = DUCAL_NATIVITY_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['nativity.kindle_duty', 'nativity.plant_caution']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'spirit']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(DUCAL_NATIVITY_TEMPLATE.settings).toEqual(['urban']);
    expect(DUCAL_NATIVITY_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(DUCAL_NATIVITY_TEMPLATE.consequenceDraw).toEqual(['drive', 'place']);
    expect(DUCAL_NATIVITY_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.ducal_nativity',
          reach: 'star',
          rarityTier: 2,
        }),
        DUCAL_NATIVITY_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
