/**
 * Called to the Ring — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { FAIR_BOUT_TEMPLATE } from '../fair-bout';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("Called to the Ring — template structure", () => {
  it('carries its identity', () => {
    expect(FAIR_BOUT_TEMPLATE.id).toBe('encounter.town.fair_bout');
    expect(FAIR_BOUT_TEMPLATE.reach).toBe('iron');
    expect(FAIR_BOUT_TEMPLATE.rarityTier).toBe(2);
    expect(FAIR_BOUT_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = FAIR_BOUT_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['bout.rouse_the_crowd', 'bout.cool_the_blood']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['energy', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(FAIR_BOUT_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(FAIR_BOUT_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(FAIR_BOUT_TEMPLATE.consequenceDraw).toEqual(['companion', 'secret']);
    expect(FAIR_BOUT_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.fair_bout',
          reach: 'iron',
          rarityTier: 2,
        }),
        FAIR_BOUT_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
