/**
 * Called to End a Feud — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { FEUD_MEDIATION_TEMPLATE } from '../feud-mediation';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("Called to End a Feud — template structure", () => {
  it('carries its identity', () => {
    expect(FEUD_MEDIATION_TEMPLATE.id).toBe('encounter.town.feud_mediation');
    expect(FEUD_MEDIATION_TEMPLATE.reach).toBe('heart');
    expect(FEUD_MEDIATION_TEMPLATE.rarityTier).toBe(2);
    expect(FEUD_MEDIATION_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = FEUD_MEDIATION_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['feud.loosen_a_tongue', 'feud.wake_old_memory']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'time']);
  });

  it('step 1 deals the authored hand', () => {
    const step = FEUD_MEDIATION_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['feud.dull_a_suspicion']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos']);
  });

  it('step 2 deals the authored hand', () => {
    const step = FEUD_MEDIATION_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['feud.seal_the_handshake', 'feud.lay_grudges_down']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['order']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(FEUD_MEDIATION_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(FEUD_MEDIATION_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(FEUD_MEDIATION_TEMPLATE.consequenceDraw).toEqual(['companion', 'secret']);
    expect(FEUD_MEDIATION_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.feud_mediation',
          reach: 'heart',
          rarityTier: 2,
        }),
        FEUD_MEDIATION_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
