/**
 * The Failing Dyke — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { FLOOD_DYKE_MENDING_TEMPLATE } from '../flood-dyke-mending';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Failing Dyke — template structure", () => {
  it('carries its identity', () => {
    expect(FLOOD_DYKE_MENDING_TEMPLATE.id).toBe('encounter.town.flood_dyke_mending');
    expect(FLOOD_DYKE_MENDING_TEMPLATE.reach).toBe('stone');
    expect(FLOOD_DYKE_MENDING_TEMPLATE.rarityTier).toBe(2);
    expect(FLOOD_DYKE_MENDING_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = FLOOD_DYKE_MENDING_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['dyke.remember_the_old_craft', 'dyke.raise_hidden_water']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = FLOOD_DYKE_MENDING_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['dyke.ease_tired_backs', 'dyke.hound_a_rival']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'life']);
  });

  it('step 2 deals the authored hand', () => {
    const step = FLOOD_DYKE_MENDING_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['dyke.harden_wet_earth', 'dyke.call_a_hard_frost']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['energy', 'matter']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(FLOOD_DYKE_MENDING_TEMPLATE.settings).toEqual(['rural']);
    expect(FLOOD_DYKE_MENDING_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(FLOOD_DYKE_MENDING_TEMPLATE.consequenceDraw).toEqual(['story_seed', 'place']);
    expect(FLOOD_DYKE_MENDING_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.flood_dyke_mending',
          reach: 'stone',
          rarityTier: 2,
        }),
        FLOOD_DYKE_MENDING_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
