/**
 * The Forged Charter — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { FORGED_CHARTER_INQUEST_TEMPLATE } from '../forged-charter-inquest';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Forged Charter — template structure", () => {
  it('carries its identity', () => {
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.id).toBe('encounter.town.forged_charter_inquest');
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.reach).toBe('eye');
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.rarityTier).toBe(2);
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = FORGED_CHARTER_INQUEST_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['charter.test_the_ink', 'charter.warm_the_wax']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['energy', 'entropy']);
  });

  it('step 1 deals the authored hand', () => {
    const step = FORGED_CHARTER_INQUEST_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['charter.wake_old_guilt', 'charter.crack_the_inkwell']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.settings).toEqual(['urban']);
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.consequenceDraw).toEqual(['knowledge', 'story_seed']);
    expect(FORGED_CHARTER_INQUEST_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.forged_charter_inquest',
          reach: 'eye',
          rarityTier: 2,
        }),
        FORGED_CHARTER_INQUEST_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
