/**
 * The Granary Riot — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { GRANARY_RIOT_TEMPLATE } from '../granary-riot';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Granary Riot — template structure", () => {
  it('carries its identity', () => {
    expect(GRANARY_RIOT_TEMPLATE.id).toBe('encounter.town.granary_riot');
    expect(GRANARY_RIOT_TEMPLATE.reach).toBe('heart');
    expect(GRANARY_RIOT_TEMPLATE.rarityTier).toBe(2);
    expect(GRANARY_RIOT_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = GRANARY_RIOT_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['granary.calm_frightened_people', 'granary.hold_the_gate']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force', 'mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = GRANARY_RIOT_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['granary.remember_lean_years', 'granary.open_closed_hands']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(GRANARY_RIOT_TEMPLATE.settings).toEqual(['urban']);
    expect(GRANARY_RIOT_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(GRANARY_RIOT_TEMPLATE.consequenceDraw).toEqual(['relationship', 'story_seed']);
    expect(GRANARY_RIOT_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.granary_riot',
          reach: 'heart',
          rarityTier: 2,
        }),
        GRANARY_RIOT_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
