/**
 * Calling the Harvest — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { HARVEST_ALMANAC_TEMPLATE } from '../harvest-almanac';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("Calling the Harvest — template structure", () => {
  it('carries its identity', () => {
    expect(HARVEST_ALMANAC_TEMPLATE.id).toBe('encounter.town.harvest_almanac');
    expect(HARVEST_ALMANAC_TEMPLATE.reach).toBe('star');
    expect(HARVEST_ALMANAC_TEMPLATE.rarityTier).toBe(2);
    expect(HARVEST_ALMANAC_TEMPLATE.steps).toHaveLength(1);
  });

  it('step 0 deals the authored hand', () => {
    const step = HARVEST_ALMANAC_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['harvest.hasten_the_signs', 'harvest.stoke_their_pride']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(HARVEST_ALMANAC_TEMPLATE.settings).toEqual(['rural']);
    expect(HARVEST_ALMANAC_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(HARVEST_ALMANAC_TEMPLATE.consequenceDraw).toEqual(['drive', 'movement']);
    expect(HARVEST_ALMANAC_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.harvest_almanac',
          reach: 'star',
          rarityTier: 2,
        }),
        HARVEST_ALMANAC_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
