/**
 * The Hired Knives — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { HIRED_KNIVES_TEMPLATE } from '../hired-knives';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Hired Knives — template structure", () => {
  it('carries its identity', () => {
    expect(HIRED_KNIVES_TEMPLATE.id).toBe('encounter.rival.hired_knives');
    expect(HIRED_KNIVES_TEMPLATE.reach).toBe('shadow');
    expect(HIRED_KNIVES_TEMPLATE.rarityTier).toBe(2);
    expect(HIRED_KNIVES_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = HIRED_KNIVES_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['knives.hide_their_passing', 'knives.doubt_every_face']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['darkness']);
  });

  it('step 1 deals the authored hand', () => {
    const step = HIRED_KNIVES_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['knives.shatter_the_blades', 'knives.rouse_the_witness']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(HIRED_KNIVES_TEMPLATE.settings).toEqual(['rural', 'urban', 'wayside']);
    expect(HIRED_KNIVES_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban', 'wayside']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(HIRED_KNIVES_TEMPLATE.consequenceDraw).toEqual(['relationship', 'drive']);
    expect(HIRED_KNIVES_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.rival.hired_knives',
          reach: 'shadow',
          rarityTier: 2,
        }),
        HIRED_KNIVES_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
