/**
 * The Inheritance Wake — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { INHERITANCE_WAKE_TEMPLATE } from '../inheritance-wake';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Inheritance Wake — template structure", () => {
  it('carries its identity', () => {
    expect(INHERITANCE_WAKE_TEMPLATE.id).toBe('encounter.town.inheritance_wake');
    expect(INHERITANCE_WAKE_TEMPLATE.reach).toBe('heart');
    expect(INHERITANCE_WAKE_TEMPLATE.rarityTier).toBe(2);
    expect(INHERITANCE_WAKE_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = INHERITANCE_WAKE_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['wake.remember_the_dead', 'wake.stoke_their_pride']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['energy', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(INHERITANCE_WAKE_TEMPLATE.settings).toEqual(['rural']);
    expect(INHERITANCE_WAKE_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(INHERITANCE_WAKE_TEMPLATE.consequenceDraw).toEqual(['relationship', 'membership']);
    expect(INHERITANCE_WAKE_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.inheritance_wake',
          reach: 'heart',
          rarityTier: 2,
        }),
        INHERITANCE_WAKE_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
