/**
 * The Judicial Duel — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { JUDICIAL_DUEL_TEMPLATE } from '../judicial-duel';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Judicial Duel — template structure", () => {
  it('carries its identity', () => {
    expect(JUDICIAL_DUEL_TEMPLATE.id).toBe('encounter.town.judicial_duel');
    expect(JUDICIAL_DUEL_TEMPLATE.reach).toBe('iron');
    expect(JUDICIAL_DUEL_TEMPLATE.rarityTier).toBe(2);
    expect(JUDICIAL_DUEL_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = JUDICIAL_DUEL_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['duel.slow_every_move', 'duel.reveal_old_habits']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'time']);
  });

  it('step 1 deals the authored hand', () => {
    const step = JUDICIAL_DUEL_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['duel.rouse_the_crowd', 'duel.twist_their_footing']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'spirit']);
  });

  it('step 2 deals the authored hand', () => {
    const step = JUDICIAL_DUEL_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['duel.weigh_a_false_oath']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['order']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(JUDICIAL_DUEL_TEMPLATE.settings).toEqual(['urban']);
    expect(JUDICIAL_DUEL_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(JUDICIAL_DUEL_TEMPLATE.consequenceDraw).toEqual(['thread', 'place']);
    expect(JUDICIAL_DUEL_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.judicial_duel',
          reach: 'iron',
          rarityTier: 2,
        }),
        JUDICIAL_DUEL_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
