/**
 * The Keeper's Petition — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { KEEPERS_PETITION_TEMPLATE } from '../keepers-petition';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';

describe("The Keeper's Petition — template structure", () => {
  it('carries its identity', () => {
    expect(KEEPERS_PETITION_TEMPLATE.id).toBe('encounter.realm.keepers_petition');
    expect(KEEPERS_PETITION_TEMPLATE.reach).toBe('heart');
    expect(KEEPERS_PETITION_TEMPLATE.rarityTier).toBe(2);
    expect(KEEPERS_PETITION_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = KEEPERS_PETITION_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['petition.still_the_yard', 'petition.weigh_the_grievance']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'order']);
  });

  it('step 1 deals the authored hand', () => {
    const step = KEEPERS_PETITION_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['petition.loosen_the_purse']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['spirit']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(KEEPERS_PETITION_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(KEEPERS_PETITION_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(KEEPERS_PETITION_TEMPLATE.consequenceDraw).toEqual(['condition', 'omen']);
    expect(KEEPERS_PETITION_TEMPLATE.consequenceDraw).toEqual(
      drawConsequenceHand({
        templateId: 'encounter.realm.keepers_petition',
        reach: 'heart',
        rarityTier: 2,
      }),
    );
  });
});
