/**
 * The Ledger by Lamplight — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { LEDGER_BY_LAMPLIGHT_TEMPLATE } from '../ledger-by-lamplight';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Ledger by Lamplight — template structure", () => {
  it('carries its identity', () => {
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.id).toBe('encounter.town.ledger_by_lamplight');
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.reach).toBe('shadow');
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.rarityTier).toBe(2);
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = LEDGER_BY_LAMPLIGHT_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['ledger.darken_the_front', 'ledger.stretch_the_rounds']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['darkness', 'time']);
  });

  it('step 1 deals the authored hand', () => {
    const step = LEDGER_BY_LAMPLIGHT_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['ledger.spare_the_seal', 'ledger.clear_the_head']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.settings).toEqual(['urban']);
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.consequenceDraw).toEqual(['possession', 'place']);
    expect(LEDGER_BY_LAMPLIGHT_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.ledger_by_lamplight',
          reach: 'shadow',
          rarityTier: 2,
        }),
        LEDGER_BY_LAMPLIGHT_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
