/**
 * The Levee Breach — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { LEVEE_BREACH_TEMPLATE } from '../levee-breach';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Levee Breach — template structure", () => {
  it('carries its identity', () => {
    expect(LEVEE_BREACH_TEMPLATE.id).toBe('encounter.town.levee_breach');
    expect(LEVEE_BREACH_TEMPLATE.reach).toBe('iron');
    expect(LEVEE_BREACH_TEMPLATE.rarityTier).toBe(2);
    expect(LEVEE_BREACH_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = LEVEE_BREACH_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['levee.stiffen_the_load']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter']);
  });

  it('step 1 deals the authored hand', () => {
    const step = LEVEE_BREACH_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['levee.show_the_leak']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light']);
  });

  it('step 2 deals the authored hand', () => {
    const step = LEVEE_BREACH_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['levee.bolster_the_wall', 'levee.hasten_the_dawn']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['force', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(LEVEE_BREACH_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(LEVEE_BREACH_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(LEVEE_BREACH_TEMPLATE.consequenceDraw).toEqual(['thread', 'place']);
    expect(LEVEE_BREACH_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.levee_breach',
          reach: 'iron',
          rarityTier: 2,
        }),
        LEVEE_BREACH_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
