/**
 * The Mason's Commission — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { MASONS_COMMISSION_TEMPLATE } from '../masons-commission';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Mason's Commission — template structure", () => {
  it('carries its identity', () => {
    expect(MASONS_COMMISSION_TEMPLATE.id).toBe('encounter.town.masons_commission');
    expect(MASONS_COMMISSION_TEMPLATE.reach).toBe('stone');
    expect(MASONS_COMMISSION_TEMPLATE.rarityTier).toBe(2);
    expect(MASONS_COMMISSION_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = MASONS_COMMISSION_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['commission.stir_the_memory', 'commission.loosen_the_spoil']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = MASONS_COMMISSION_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['commission.harden_the_bed', 'commission.hasten_the_rival']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'force']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(MASONS_COMMISSION_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(MASONS_COMMISSION_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(MASONS_COMMISSION_TEMPLATE.consequenceDraw).toEqual(['relationship', 'possession']);
    expect(MASONS_COMMISSION_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.masons_commission',
          reach: 'stone',
          rarityTier: 2,
        }),
        MASONS_COMMISSION_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
