/**
 * The Mill Lease — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { MILL_LEASE_AUCTION_TEMPLATE } from '../mill-lease-auction';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Mill Lease — template structure", () => {
  it('carries its identity', () => {
    expect(MILL_LEASE_AUCTION_TEMPLATE.id).toBe('encounter.town.mill_lease_auction');
    expect(MILL_LEASE_AUCTION_TEMPLATE.reach).toBe('gold');
    expect(MILL_LEASE_AUCTION_TEMPLATE.rarityTier).toBe(2);
    expect(MILL_LEASE_AUCTION_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = MILL_LEASE_AUCTION_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['mill.uncover_hidden_tallies', 'mill.stretch_the_morning']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'time']);
  });

  it('step 1 deals the authored hand', () => {
    const step = MILL_LEASE_AUCTION_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['mill.read_out_the_rule', 'mill.swell_the_rivals_pride']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['order', 'spirit']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(MILL_LEASE_AUCTION_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(MILL_LEASE_AUCTION_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(MILL_LEASE_AUCTION_TEMPLATE.consequenceDraw).toEqual(['knowledge', 'story_seed']);
    expect(MILL_LEASE_AUCTION_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.mill_lease_auction',
          reach: 'gold',
          rarityTier: 2,
        }),
        MILL_LEASE_AUCTION_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
