/**
 * The Oath-Breaker's Rite — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { OATH_BREAKER_RITE_TEMPLATE } from '../oath-breaker-rite';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Oath-Breaker's Rite — template structure", () => {
  it('carries its identity', () => {
    expect(OATH_BREAKER_RITE_TEMPLATE.id).toBe('encounter.town.oath_breaker_rite');
    expect(OATH_BREAKER_RITE_TEMPLATE.reach).toBe('veil');
    expect(OATH_BREAKER_RITE_TEMPLATE.rarityTier).toBe(2);
    expect(OATH_BREAKER_RITE_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = OATH_BREAKER_RITE_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['oath.remember_old_ways', 'oath.stir_doubt']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(OATH_BREAKER_RITE_TEMPLATE.settings).toEqual(['urban']);
    expect(OATH_BREAKER_RITE_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(OATH_BREAKER_RITE_TEMPLATE.consequenceDraw).toEqual(['condition', 'place']);
    expect(OATH_BREAKER_RITE_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.oath_breaker_rite',
          reach: 'veil',
          rarityTier: 2,
        }),
        OATH_BREAKER_RITE_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
