/**
 * The Overdue Caravan — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { OVERDUE_CARAVAN_TEMPLATE } from '../overdue-caravan';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Overdue Caravan — template structure", () => {
  it('carries its identity', () => {
    expect(OVERDUE_CARAVAN_TEMPLATE.id).toBe('encounter.town.overdue_caravan');
    expect(OVERDUE_CARAVAN_TEMPLATE.reach).toBe('star');
    expect(OVERDUE_CARAVAN_TEMPLATE.rarityTier).toBe(2);
    expect(OVERDUE_CARAVAN_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = OVERDUE_CARAVAN_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['caravan.stir_the_memory']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = OVERDUE_CARAVAN_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['caravan.catch_the_low_sun']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light']);
  });

  it('step 2 deals the authored hand', () => {
    const step = OVERDUE_CARAVAN_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['caravan.stiffen_the_resolve', 'caravan.clear_the_sky']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['energy', 'spirit']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(OVERDUE_CARAVAN_TEMPLATE.settings).toEqual(['urban', 'rural']);
    expect(OVERDUE_CARAVAN_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban', 'rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(OVERDUE_CARAVAN_TEMPLATE.consequenceDraw).toEqual(['story_seed', 'thread']);
    expect(OVERDUE_CARAVAN_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.overdue_caravan',
          reach: 'star',
          rarityTier: 2,
        }),
        OVERDUE_CARAVAN_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
