/**
 * The Run the Pilot Refused — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { PILOTS_RECKONING_TEMPLATE } from '../pilots-reckoning';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Run the Pilot Refused — template structure", () => {
  it('carries its identity', () => {
    expect(PILOTS_RECKONING_TEMPLATE.id).toBe('encounter.town.pilots_reckoning');
    expect(PILOTS_RECKONING_TEMPLATE.reach).toBe('star');
    expect(PILOTS_RECKONING_TEMPLATE.rarityTier).toBe(2);
    expect(PILOTS_RECKONING_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = PILOTS_RECKONING_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['reckoning.sharpen_memory', 'reckoning.clear_the_sky']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(PILOTS_RECKONING_TEMPLATE.settings).toEqual(['urban']);
    expect(PILOTS_RECKONING_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(PILOTS_RECKONING_TEMPLATE.consequenceDraw).toEqual(['relationship', 'story_seed']);
    expect(PILOTS_RECKONING_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.pilots_reckoning',
          reach: 'star',
          rarityTier: 2,
        }),
        PILOTS_RECKONING_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
