/**
 * The Restless Charnel House — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { RESTLESS_OSSUARY_TEMPLATE } from '../restless-ossuary';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Restless Charnel House — template structure", () => {
  it('carries its identity', () => {
    expect(RESTLESS_OSSUARY_TEMPLATE.id).toBe('encounter.town.restless_ossuary');
    expect(RESTLESS_OSSUARY_TEMPLATE.reach).toBe('veil');
    expect(RESTLESS_OSSUARY_TEMPLATE.rarityTier).toBe(2);
    expect(RESTLESS_OSSUARY_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = RESTLESS_OSSUARY_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['ossuary.remember_lost_names', 'ossuary.rouse_restless_dead']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['mind', 'spirit']);
  });

  it('step 1 deals the authored hand', () => {
    const step = RESTLESS_OSSUARY_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['ossuary.ward_charnel_door', 'ossuary.delay_first_light']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['order', 'time']);
  });

  it('step 2 deals the authored hand', () => {
    const step = RESTLESS_OSSUARY_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['ossuary.seal_final_judgment', 'ossuary.stir_old_grudges']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'order']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(RESTLESS_OSSUARY_TEMPLATE.settings).toEqual(['urban']);
    expect(RESTLESS_OSSUARY_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(RESTLESS_OSSUARY_TEMPLATE.consequenceDraw).toEqual(['standing', 'omen']);
    expect(RESTLESS_OSSUARY_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.restless_ossuary',
          reach: 'veil',
          rarityTier: 2,
        }),
        RESTLESS_OSSUARY_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
