/**
 * The Salt Train at the Ford — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { SMUGGLERS_FORD_TEMPLATE } from '../smugglers-ford';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Salt Train at the Ford — template structure", () => {
  it('carries its identity', () => {
    expect(SMUGGLERS_FORD_TEMPLATE.id).toBe('encounter.town.smugglers_ford');
    expect(SMUGGLERS_FORD_TEMPLATE.reach).toBe('shadow');
    expect(SMUGGLERS_FORD_TEMPLATE.rarityTier).toBe(2);
    expect(SMUGGLERS_FORD_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = SMUGGLERS_FORD_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['ford.deepen_the_fog', 'ford.count_the_fine']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['darkness', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(SMUGGLERS_FORD_TEMPLATE.settings).toEqual(['rural']);
    expect(SMUGGLERS_FORD_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(SMUGGLERS_FORD_TEMPLATE.consequenceDraw).toEqual(['movement', 'omen']);
    expect(SMUGGLERS_FORD_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.smugglers_ford',
          reach: 'shadow',
          rarityTier: 2,
        }),
        SMUGGLERS_FORD_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
