/**
 * The Beast in the Granary — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { THE_BEAST_IN_THE_GRANARY_TEMPLATE } from '../the-beast-in-the-granary';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';

describe('The Beast in the Granary — template structure', () => {
  it('carries its identity', () => {
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.id).toBe('encounter.hunt.the_beast_in_the_granary');
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.reach).toBe('shadow');
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.rarityTier).toBe(1);
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = THE_BEAST_IN_THE_GRANARY_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['granary.wake_their_fear', 'granary.weigh_the_winter']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.settings).toEqual(['rural', 'wayside', 'stronghold']);
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'wayside', 'stronghold']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.consequenceDraw).toEqual(['possession', 'membership']);
    expect(THE_BEAST_IN_THE_GRANARY_TEMPLATE.consequenceDraw).toEqual(
      drawConsequenceHand({
        templateId: 'encounter.hunt.the_beast_in_the_granary',
        reach: 'shadow',
        rarityTier: 1,
      }),
    );
  });
});
