/**
 * The Unfinished Rite — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { THE_UNFINISHED_RITE_TEMPLATE } from '../the-unfinished-rite';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';
// THR-1254 — hand-added below the generated block. `compile:encounter --force`
// regenerates this file wholesale, so re-add the composed-hand describe if you
// ever recompile; the generator has no hook for encounter-specific assertions.
import { composeDealtStep } from '../../../engine/encounters/dealHand';
import { buildRepertoire } from '../../../engine/nudgeCardRepertoire';
import { DEAL_HAND_MAX, DEAL_HAND_MIN } from '../../nudge-constants';

describe('The Unfinished Rite — template structure', () => {
  it('carries its identity', () => {
    expect(THE_UNFINISHED_RITE_TEMPLATE.id).toBe('encounter.delve.the_unfinished_rite');
    expect(THE_UNFINISHED_RITE_TEMPLATE.reach).toBe('veil');
    expect(THE_UNFINISHED_RITE_TEMPLATE.rarityTier).toBe(1);
    expect(THE_UNFINISHED_RITE_TEMPLATE.steps).toHaveLength(1);
  });

  it('step 0 deals the authored hand', () => {
    const step = THE_UNFINISHED_RITE_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['rite.loosen_their_nerve', 'rite.kindle_heresy']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'darkness']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(THE_UNFINISHED_RITE_TEMPLATE.settings).toEqual(['sacred', 'arcane', 'rural']);
    expect(THE_UNFINISHED_RITE_TEMPLATE.locationSubtypes).toEqual(expandSettings(['sacred', 'arcane', 'rural']));
  });

  /**
   * THR-1254 — the claim that flips `repertoire-deals-into-encounter-hand` to LIVE.
   *
   * Deliberately composed against a **real** god's repertoire (`buildRepertoire`
   * from a sphere identity), not a fixture holding the whole library: a fixture
   * that pre-supplied every member would assert the fixture rather than that a
   * god who actually earned these cards can be dealt a playable hand from this
   * shipped template. Falsifiable in both directions — drop the `deal`
   * declaration and `dealt` goes empty; break the dealer and the size window fails.
   */
  describe('the composed hand (THR-1247/1254)', () => {
    const step = THE_UNFINISHED_RITE_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    const repertoire = buildRepertoire({ primary: 'darkness', secondary: 'order' });
    const context = {
      primarySphere: 'darkness' as const,
      secondarySphere: 'order' as const,
      tags: step.deal?.tags,
    };

    it('declares a deal, which is what makes it the corpus first', () => {
      expect(step.deal).toBeDefined();
      expect(step.deal?.count).toBeGreaterThan(0);
      // The specials cap is the rule the declaration exists to live inside.
      expect((step.nudges ?? []).length).toBeLessThanOrEqual(2);
    });

    it('the dealer actually contributes cards on top of the specials', () => {
      const { step: composed, report } = composeDealtStep(step, repertoire, context);
      const authored = (step.nudges ?? []).map(nudge => nudge.id);
      const composedIds = (composed.nudges ?? []).map(nudge => nudge.id);

      expect(report?.dealt.length ?? 0).toBeGreaterThan(0);
      expect(composedIds.length).toBeGreaterThan(authored.length);
      // Both specials survive the compose — the dealer fills around them.
      for (const id of authored) expect(composedIds).toContain(id);
      expect(composedIds.length).toBeGreaterThanOrEqual(DEAL_HAND_MIN);
      expect(composedIds.length).toBeLessThanOrEqual(DEAL_HAND_MAX);
    });

    it('deals a different fill to a different god — the contract intent', () => {
      const dark = composeDealtStep(step, repertoire, context).report?.dealt ?? [];
      const forceRep = buildRepertoire({ primary: 'force', secondary: 'matter' });
      const force = composeDealtStep(step, forceRep, {
        primarySphere: 'force',
        secondarySphere: 'matter',
        tags: step.deal?.tags,
      }).report?.dealt ?? [];
      expect(dark).not.toEqual(force);
    });

    it('deals the same hand twice — dealing takes no PRNG', () => {
      const a = composeDealtStep(step, repertoire, context).step.nudges ?? [];
      const b = composeDealtStep(step, repertoire, context).step.nudges ?? [];
      expect(a.map(n => n.id)).toEqual(b.map(n => n.id));
    });
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(THE_UNFINISHED_RITE_TEMPLATE.consequenceDraw).toEqual(['place', 'omen']);
    expect(THE_UNFINISHED_RITE_TEMPLATE.consequenceDraw).toEqual(
      drawConsequenceHand({
        templateId: 'encounter.delve.the_unfinished_rite',
        reach: 'veil',
        rarityTier: 1,
      }),
    );
  });
});
