/**
 * Blamed for the Tithe Barn — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { TITHE_BARN_RAID_TEMPLATE } from '../tithe-barn-raid';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("Blamed for the Tithe Barn — template structure", () => {
  it('carries its identity', () => {
    expect(TITHE_BARN_RAID_TEMPLATE.id).toBe('encounter.town.tithe_barn_raid');
    expect(TITHE_BARN_RAID_TEMPLATE.reach).toBe('shadow');
    expect(TITHE_BARN_RAID_TEMPLATE.rarityTier).toBe(2);
    expect(TITHE_BARN_RAID_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = TITHE_BARN_RAID_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['barn.dull_the_sentries', 'barn.show_the_plain_truth']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(TITHE_BARN_RAID_TEMPLATE.settings).toEqual(['rural']);
    expect(TITHE_BARN_RAID_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(TITHE_BARN_RAID_TEMPLATE.consequenceDraw).toEqual(['thread', 'omen']);
    expect(TITHE_BARN_RAID_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.tithe_barn_raid',
          reach: 'shadow',
          rarityTier: 2,
        }),
        TITHE_BARN_RAID_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
