/**
 * The Tithe Demanded — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { TITHE_DEMANDED_TEMPLATE } from '../tithe-demanded';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand } from '../../content-eval/consequenceDraw';

describe("The Tithe Demanded — template structure", () => {
  it('carries its identity', () => {
    expect(TITHE_DEMANDED_TEMPLATE.id).toBe('encounter.realm.tithe_demanded');
    expect(TITHE_DEMANDED_TEMPLATE.reach).toBe('gold');
    expect(TITHE_DEMANDED_TEMPLATE.rarityTier).toBe(2);
    expect(TITHE_DEMANDED_TEMPLATE.steps).toHaveLength(2);
  });


  it('step 1 deals the authored hand', () => {
    const step = TITHE_DEMANDED_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['tithe.steady_the_collector', 'tithe.the_place_speaks']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['spirit', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(TITHE_DEMANDED_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(TITHE_DEMANDED_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(TITHE_DEMANDED_TEMPLATE.consequenceDraw).toEqual(['condition', 'drive']);
    expect(TITHE_DEMANDED_TEMPLATE.consequenceDraw).toEqual(
      drawConsequenceHand({
        templateId: 'encounter.realm.tithe_demanded',
        reach: 'gold',
        rarityTier: 2,
      }),
    );
  });
});
