/**
 * The Writ at the Toll Gate — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { TOLL_GATE_WRIT_TEMPLATE } from '../toll-gate-writ';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Writ at the Toll Gate — template structure", () => {
  it('carries its identity', () => {
    expect(TOLL_GATE_WRIT_TEMPLATE.id).toBe('encounter.town.toll_gate_writ');
    expect(TOLL_GATE_WRIT_TEMPLATE.reach).toBe('eye');
    expect(TOLL_GATE_WRIT_TEMPLATE.rarityTier).toBe(2);
    expect(TOLL_GATE_WRIT_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = TOLL_GATE_WRIT_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['writ.light_the_page', 'writ.cool_their_scorn']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light', 'mind']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(TOLL_GATE_WRIT_TEMPLATE.settings).toEqual(['urban']);
    expect(TOLL_GATE_WRIT_TEMPLATE.locationSubtypes).toEqual(expandSettings(['urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(TOLL_GATE_WRIT_TEMPLATE.consequenceDraw).toEqual(['knowledge', 'movement']);
    expect(TOLL_GATE_WRIT_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.toll_gate_writ',
          reach: 'eye',
          rarityTier: 2,
        }),
        TOLL_GATE_WRIT_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
