/**
 * The Well Sinking — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { WELL_SINKING_TEMPLATE } from '../well-sinking';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("The Well Sinking — template structure", () => {
  it('carries its identity', () => {
    expect(WELL_SINKING_TEMPLATE.id).toBe('encounter.town.well_sinking');
    expect(WELL_SINKING_TEMPLATE.reach).toBe('stone');
    expect(WELL_SINKING_TEMPLATE.rarityTier).toBe(2);
    expect(WELL_SINKING_TEMPLATE.steps).toHaveLength(2);
  });

  it('step 0 deals the authored hand', () => {
    const step = WELL_SINKING_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['well.wake_the_memory', 'well.bind_the_sand']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter', 'mind']);
  });

  it('step 1 deals the authored hand', () => {
    const step = WELL_SINKING_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['well.hold_off_the_rain', 'well.sway_the_neighbour']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['order', 'time']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(WELL_SINKING_TEMPLATE.settings).toEqual(['rural', 'urban']);
    expect(WELL_SINKING_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural', 'urban']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(WELL_SINKING_TEMPLATE.consequenceDraw).toEqual(['membership', 'omen']);
    expect(WELL_SINKING_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.well_sinking',
          reach: 'stone',
          rarityTier: 2,
        }),
        WELL_SINKING_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
