/**
 * Wolves at the Fold — structural test generated by compile:encounter (THR-1246).
 * Expected values are baked from the content package, so this file asserts the
 * encounter's actual shape rather than any template's.
 */

import { describe, expect, it } from 'vitest';
import { WOLF_WINTER_WATCH_TEMPLATE } from '../wolf-winter-watch';
import { expandSettings } from '../../settingClasses';
import { drawConsequenceHand, handAfterSwap } from '../../content-eval/consequenceDraw';

describe("Wolves at the Fold — template structure", () => {
  it('carries its identity', () => {
    expect(WOLF_WINTER_WATCH_TEMPLATE.id).toBe('encounter.town.wolf_winter_watch');
    expect(WOLF_WINTER_WATCH_TEMPLATE.reach).toBe('iron');
    expect(WOLF_WINTER_WATCH_TEMPLATE.rarityTier).toBe(2);
    expect(WOLF_WINTER_WATCH_TEMPLATE.steps).toHaveLength(3);
  });

  it('step 0 deals the authored hand', () => {
    const step = WOLF_WINTER_WATCH_TEMPLATE.steps[0];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['wolf.reveal_the_trail', 'wolf.twist_a_tale']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['chaos', 'life']);
  });

  it('step 1 deals the authored hand', () => {
    const step = WOLF_WINTER_WATCH_TEMPLATE.steps[1];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['wolf.guard_the_flames']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['light']);
  });

  it('step 2 deals the authored hand', () => {
    const step = WOLF_WINTER_WATCH_TEMPLATE.steps[2];
    if (!('narrativeTemplate' in step)) throw new Error('expected a plain step');
    expect((step.nudges ?? []).map(nudge => nudge.id)).toEqual(['wolf.harden_the_bar', 'wolf.raise_morale']);
    const spheres = [...new Set((step.nudges ?? []).map(nudge => nudge.sphere).filter(Boolean))].sort();
    expect(spheres).toEqual(['matter']);
  });
  it('derives its location subtypes from the declared envelope', () => {
    expect(WOLF_WINTER_WATCH_TEMPLATE.settings).toEqual(['rural']);
    expect(WOLF_WINTER_WATCH_TEMPLATE.locationSubtypes).toEqual(expandSettings(['rural']));
  });

  it('records exactly the hand its id draws (binding, THR-1145)', () => {
    expect(WOLF_WINTER_WATCH_TEMPLATE.consequenceDraw).toEqual(['secret', 'place']);
    expect(WOLF_WINTER_WATCH_TEMPLATE.consequenceDraw).toEqual(
      handAfterSwap(
        drawConsequenceHand({
          templateId: 'encounter.town.wolf_winter_watch',
          reach: 'iron',
          rarityTier: 2,
        }),
        WOLF_WINTER_WATCH_TEMPLATE.consequenceSwap,
      ),
    );
  });
});
