/**
 * Tunable Constants Registry — central catalog of every game-design constant.
 *
 * Imports every tunable numeric/boolean constant from the codebase and
 * organises them into groups with rich metadata: description, valid range,
 * which calculations consume them, and the source file for write-back.
 *
 * Used by the Configuration Manager viewer in the CMS.
 */

import type { TunableGroup, TunableConstant } from './types';

// ── Data imports: src/data/ ─────────────────────────────────────────────

import * as gameConfig from '../../data/game-config';
import * as movement from '../../data/movement-content';
import * as threat from '../../data/threat-content';
import * as influence from '../../data/influence-content';
import * as agentVisual from '../../data/agent-visual-content';
import * as abc from '../../data/agent-behavior-constants';

// ── Engine imports: src/engine/ ─────────────────────────────────────────

import * as terrain from '../../engine/terrain';
import * as wgConstants from '../../engine/worldgen/constants';
import * as forceField from '../../engine/forceField';
import * as terrainTypes from '../../engine/terrainPipeline/types';
import * as agentLife from '../../engine/agentLifecycle';
import * as ambitionTick from '../../engine/ambitionTick';
import * as ambitionBoost from '../../engine/ambitionBoost';
import * as culturalGrav from '../../engine/culturalGravity';
import * as wealth from '../../engine/wealth';
import * as guild from '../../engine/guildSeeding';
import * as prosperity from '../../engine/phaseProsperity';
import * as subloc from '../../engine/phaseSublocations';
import * as unrest from '../../engine/phaseUnrest';
import * as hexState from '../../engine/phaseHexState';
import * as magSat from '../../engine/phaseMagicalSaturation';
import * as hexAction from '../../engine/hexActionBridge';
import * as actionPhases from '../../engine/unifiedActionPhases';
import * as init from '../../engine/gameInit';
import * as trade from '../../engine/tradeRoute';
import * as vignetteProse from '../../engine/vignetteProse';

// ── Helper ──────────────────────────────────────────────────────────────

function n(
  exportName: string,
  value: number,
  description: string,
  sourceFile: string,
  range?: [number, number],
  usedBy?: string,
): TunableConstant {
  return { exportName, value, description, sourceFile, range, usedBy, type: 'number' };
}

function b(
  exportName: string,
  value: boolean,
  description: string,
  sourceFile: string,
  usedBy?: string,
): TunableConstant {
  return { exportName, value, description, sourceFile, usedBy, type: 'boolean' };
}

// ── Groups ──────────────────────────────────────────────────────────────

export const TUNABLE_GROUPS: TunableGroup[] = [

  // ═══════════════════════════════════════════════════════════════════════
  // 1. GAME PACING
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'game-pacing',
    label: 'Game Pacing',
    description: 'Core game-loop timing: doom clock, twilight phase, mandate scoring weights.',
    constants: [
      n('DEFAULT_DOOM_TICKS', gameConfig.DEFAULT_DOOM_TICKS,
        'Total ticks for a standard game length. Higher = longer games.',
        'src/data/game-config.ts', [100, 500000],
        'gameInit → doomClock countdown'),
      n('TWILIGHT_TICKS', gameConfig.TWILIGHT_TICKS,
        'Ticks of twilight phase before game end. Events intensify during twilight.',
        'src/data/game-config.ts', [1, 50],
        'cycleEnd → twilight detection'),
      n('MANDATE_PRIMARY_WEIGHT', gameConfig.MANDATE_PRIMARY_WEIGHT,
        'Score weight for primary mandate conditions. Higher = primary mandates dominate scoring.',
        'src/data/game-config.ts', [0.5, 5.0],
        'mandateScoring → final score'),
      n('MANDATE_SECONDARY_WEIGHT', gameConfig.MANDATE_SECONDARY_WEIGHT,
        'Score weight for secondary mandate conditions.',
        'src/data/game-config.ts', [0.1, 3.0],
        'mandateScoring → final score'),
      n('MANDATE_BASE_WEIGHT', gameConfig.MANDATE_BASE_WEIGHT,
        'Base score weight applied to all mandate conditions equally.',
        'src/data/game-config.ts', [0.0, 2.0],
        'mandateScoring → final score'),
      n('MANDATE_ACHIEVABLE_MULTIPLIER', gameConfig.MANDATE_ACHIEVABLE_MULTIPLIER,
        'Multiplier for achievable mandate conditions. Rewards attainable goals.',
        'src/data/game-config.ts', [1.0, 5.0],
        'mandateScoring → achievable bonus'),
      n('DEFAULT_COLS', init.DEFAULT_COLS,
        'Grid width in hexes. Larger = more territory to explore.',
        'src/engine/gameInit.ts', [10, 50],
        'gameInit → hex grid creation'),
      n('DEFAULT_ROWS', init.DEFAULT_ROWS,
        'Grid height in hexes.',
        'src/engine/gameInit.ts', [8, 40],
        'gameInit → hex grid creation'),
      n('DEFAULT_TICKS_PER_SEASON', init.DEFAULT_TICKS_PER_SEASON,
        'How many ticks make one in-game season. Affects pacing of seasonal events.',
        'src/engine/gameInit.ts', [10, 500],
        'gameInit → season/calendar tracking'),
      n('INITIAL_WORSHIPPER_TIER', init.INITIAL_WORSHIPPER_TIER,
        'Starting influence tier of initial worshippers (0=unbonded, 4=exalted).',
        'src/engine/gameInit.ts', [0, 4],
        'gameInit → starting worshippers'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 2. ENCOUNTER SCORING
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'encounter-scoring',
    label: 'Encounter Scoring',
    description: 'How agents evaluate and prioritise encounter opportunities each tick.',
    constants: [
      n('STEP_PROBABILITY_OFFSET', abc.STEP_PROBABILITY_OFFSET,
        'Offset added to step probability formula. Higher = agents attempt more encounters. Formula: P = capability + modifiers - difficulty/100 + offset.',
        'src/data/agent-behavior-constants.ts', [0.3, 0.8],
        'encounterScoring → step attempt probability'),
      n('MINIMUM_DESIRE', abc.MINIMUM_DESIRE,
        'Floor for desire multiplier. Prevents zero scores for neutral encounters. Lower = stronger axiological influence.',
        'src/data/agent-behavior-constants.ts', [0.01, 0.5],
        'encounterScoring → desire multiplier'),
      n('GROWTH_REWARD_WEIGHT', abc.GROWTH_REWARD_WEIGHT,
        'Weight for tier growth value in expected reward. 0 = ignore growth, 1 = growth dominates scoring.',
        'src/data/agent-behavior-constants.ts', [0.0, 1.0],
        'encounterScoring → expected reward'),
      n('IDLE_SCORE_THRESHOLD', abc.IDLE_SCORE_THRESHOLD,
        'Below this finalScore, the agent idles instead of acting. Lower = agents attempt more marginal encounters.',
        'src/data/agent-behavior-constants.ts', [0.0001, 0.1],
        'encounterScoring → idle vs act decision'),
      n('AMBITION_REACH_BOOST', abc.AMBITION_REACH_BOOST,
        'Flat boost when an active ambition\'s reach matches the encounter\'s primary reach. Higher = ambitions more strongly steer encounter selection.',
        'src/data/agent-behavior-constants.ts', [0.0, 0.5],
        'encounterScoring → ambition alignment'),
      n('ACTION_ATTEMPT_CHANCE', actionPhases.ACTION_ATTEMPT_CHANCE,
        'Base probability an agent attempts an action each tick. Higher = more active world.',
        'src/engine/unifiedActionPhases.ts', [0.1, 1.0],
        'unifiedActionPhases → per-agent action roll'),
      n('ROUTINE_EVENT_CHANCE', actionPhases.ROUTINE_EVENT_CHANCE,
        'Probability of a minor background event per tick. Adds ambient world flavour.',
        'src/engine/unifiedActionPhases.ts', [0.01, 0.5],
        'unifiedActionPhases → routine event generation'),
      n('NOTABLE_EVENT_INTERVAL', actionPhases.NOTABLE_EVENT_INTERVAL,
        'Minimum ticks between notable events. Lower = more dramatic action.',
        'src/engine/unifiedActionPhases.ts', [1, 50],
        'unifiedActionPhases → notable event cooldown'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 3. AWARENESS & PERCEPTION
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'awareness',
    label: 'Awareness & Perception',
    description: 'How far agents can perceive encounters, faction intel range, and social visibility.',
    constants: [
      n('AWARENESS_THRESHOLD', abc.AWARENESS_THRESHOLD,
        'Minimum capability to perceive encounters at all (below this = 0 hops).',
        'src/data/agent-behavior-constants.ts', [0.01, 0.2],
        'encounterAwareness → hop calculation'),
      n('BASE_AWARENESS_HOPS', abc.BASE_AWARENESS_HOPS,
        'Base graph hops granted to any agent above the awareness threshold.',
        'src/data/agent-behavior-constants.ts', [1, 3],
        'encounterAwareness → hop calculation'),
      n('CAPABILITY_PER_HOP', abc.CAPABILITY_PER_HOP,
        'Capability points needed per additional hop beyond base. Lower = awareness extends faster.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.3],
        'encounterAwareness → hop calculation'),
      n('MAX_AWARENESS_HOPS', abc.MAX_AWARENESS_HOPS,
        'Hard cap on awareness range for all reaches.',
        'src/data/agent-behavior-constants.ts', [3, 10],
        'encounterAwareness → hop cap'),
      b('FACTION_NETWORK_AWARENESS', abc.FACTION_NETWORK_AWARENESS,
        'Global toggle for faction network intelligence. Disabling removes all faction-shared awareness.',
        'src/data/agent-behavior-constants.ts',
        'factionAwareness → enable/disable'),
      n('FACTION_NETWORK_MAX_ENTRIES', abc.FACTION_NETWORK_MAX_ENTRIES,
        'Max entries visible per faction at rank 1.0. Actual entries = floor(rank * this). Higher = factions share more intel.',
        'src/data/agent-behavior-constants.ts', [5, 50],
        'factionAwareness → visible entries cap'),
      n('FACTION_SECONDARY_THRESHOLD', abc.FACTION_SECONDARY_THRESHOLD,
        'Minimum reach weight to count as a secondary reach for faction filtering.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'factionAwareness → secondary reach gate'),
      n('FACTION_MIN_RANK_FOR_INTEL', abc.FACTION_MIN_RANK_FOR_INTEL,
        'Minimum rank required to receive any faction intel.',
        'src/data/agent-behavior-constants.ts', [0.01, 0.2],
        'factionAwareness → rank gate'),
      n('FACTION_DEFAULT_RANK', abc.FACTION_DEFAULT_RANK,
        'Default rank when edge properties lack a rank field.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.3],
        'factionAwareness → fallback rank'),
      n('MAX_SCORED_CANDIDATES', abc.MAX_SCORED_CANDIDATES,
        'Hard cap on candidates forwarded to the scoring stage. Lower = faster but fewer options.',
        'src/data/agent-behavior-constants.ts', [20, 100],
        'encounterFilterPipeline → cap stage'),
      n('MIN_DIVERSITY_SLOTS', abc.MIN_DIVERSITY_SLOTS,
        'Minimum entries preserved per encounter type during cap stage.',
        'src/data/agent-behavior-constants.ts', [1, 5],
        'encounterFilterPipeline → diversity preservation'),
      b('THREAT_FLOOR_FILTER', abc.THREAT_FLOOR_FILTER,
        'Whether the threat-tolerance filter stage is active. Disabling lets agents attempt dangerous encounters.',
        'src/data/agent-behavior-constants.ts',
        'encounterFilterPipeline → threat stage'),
      n('VISIBLE_AGENT_MAX_HOPS', abc.VISIBLE_AGENT_MAX_HOPS,
        'Max adjacency hops for "visible" agents in social encounter scanning.',
        'src/data/agent-behavior-constants.ts', [1, 4],
        'socialEncounterGeneration → agent scan range'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 4. RESOLUTION MODIFIERS
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'resolution',
    label: 'Resolution Modifiers',
    description: 'Contextual bonuses/penalties applied during encounter step resolution.',
    constants: [
      n('SPHERE_ALIGNMENT_BONUS', abc.SPHERE_ALIGNMENT_BONUS,
        'Bonus when agent sphere matches encounter sphere.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.25],
        'resolutionModifiers → sphere check'),
      n('SPHERE_OPPOSITION_PENALTY', abc.SPHERE_OPPOSITION_PENALTY,
        'Penalty when agent sphere opposes encounter sphere.',
        'src/data/agent-behavior-constants.ts', [-0.25, -0.05],
        'resolutionModifiers → sphere check'),
      n('EQUIPMENT_MODIFIER_CAP', abc.EQUIPMENT_MODIFIER_CAP,
        'Max total equipment modifier across all items.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.30],
        'resolutionModifiers → equipment sum'),
      n('EQUIPMENT_PER_ITEM_CAP', abc.EQUIPMENT_PER_ITEM_CAP,
        'Max modifier from a single equipment item.',
        'src/data/agent-behavior-constants.ts', [0.03, 0.15],
        'resolutionModifiers → per-item clamp'),
      n('TERRAIN_MODIFIER_CAP', abc.TERRAIN_MODIFIER_CAP,
        'Max total terrain modifier (absolute value, clamped both directions).',
        'src/data/agent-behavior-constants.ts', [0.05, 0.20],
        'resolutionModifiers → terrain clamp'),
      n('FACTION_CONTROL_BONUS', abc.FACTION_CONTROL_BONUS,
        'Bonus for acting in friendly-controlled territory.',
        'src/data/agent-behavior-constants.ts', [0.02, 0.10],
        'resolutionModifiers → territory check'),
      n('HOSTILE_TERRITORY_PENALTY', abc.HOSTILE_TERRITORY_PENALTY,
        'Penalty for acting in hostile-controlled territory.',
        'src/data/agent-behavior-constants.ts', [-0.10, -0.02],
        'resolutionModifiers → territory check'),
      n('TRAIT_BONUS_CAP', abc.TRAIT_BONUS_CAP,
        'Max total trait resolution bonus.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.20],
        'resolutionModifiers → trait sum'),
      n('TRAIT_PER_BONUS_CAP', abc.TRAIT_PER_BONUS_CAP,
        'Max modifier from a single trait.',
        'src/data/agent-behavior-constants.ts', [0.02, 0.10],
        'resolutionModifiers → per-trait clamp'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 5. CAPABILITY GROWTH & TIERS
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'growth',
    label: 'Capability Growth & Tiers',
    description: 'How agents gain domain capability and advance tiers through encounters.',
    constants: [
      n('BASE_ENCOUNTER_GROWTH', abc.BASE_ENCOUNTER_GROWTH,
        'Base growth per successful encounter step completion. Higher = faster progression.',
        'src/data/agent-behavior-constants.ts', [0.1, 1.0],
        'capabilityGrowth → growth delta'),
      n('PROMOTION_ELIGIBLE_MULTIPLIER', abc.PROMOTION_ELIGIBLE_MULTIPLIER,
        'Multiplier when the step outcome has tierPromotionEligible.',
        'src/data/agent-behavior-constants.ts', [1.5, 3.0],
        'capabilityGrowth → promotion growth'),
      n('DIMINISHING_RETURNS_FACTOR', abc.DIMINISHING_RETURNS_FACTOR,
        'Rate at which high capability reduces growth (0–1). Higher = steeper diminishing returns at high cap.',
        'src/data/agent-behavior-constants.ts', [0.3, 0.9],
        'capabilityGrowth → diminishing curve'),
      n('FAILURE_GROWTH_FRACTION', abc.FAILURE_GROWTH_FRACTION,
        'Fraction of base growth awarded on failure. 0 = no failure growth, 0.5 = half credit.',
        'src/data/agent-behavior-constants.ts', [0.0, 0.5],
        'capabilityGrowth → failure handling'),
      n('CRITICAL_SUCCESS_MULTIPLIER', abc.CRITICAL_SUCCESS_MULTIPLIER,
        'Multiplier for critical success outcomes.',
        'src/data/agent-behavior-constants.ts', [1.0, 3.0],
        'capabilityGrowth → critical success'),
      n('CRITICAL_FAILURE_GROWTH', abc.CRITICAL_FAILURE_GROWTH,
        'Growth on critical failure. 0 = no growth at all.',
        'src/data/agent-behavior-constants.ts', [0.0, 0.5],
        'capabilityGrowth → critical failure'),
      n('FACTION_RANK_PER_PROMOTION', abc.FACTION_RANK_PER_PROMOTION,
        'Rank bump for factions whose primary reach matches the promoted domain.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.2],
        'tierPromotion → faction rank update'),
      n('FACTION_RANK_SECONDARY_FRACTION', abc.FACTION_RANK_SECONDARY_FRACTION,
        'Rank bump for factions whose secondary reach matches the promoted domain.',
        'src/data/agent-behavior-constants.ts', [0.02, 0.1],
        'tierPromotion → secondary rank update'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 6. AGENT LIFECYCLE & BEHAVIOR
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'agent-lifecycle',
    label: 'Agent Lifecycle & Behavior',
    description: 'Birth, death, idle behavior, ambition timing, and cultural gravity.',
    constants: [
      n('DEATH_CHANCE_LOW_REP', agentLife.DEATH_CHANCE_LOW_REP,
        'Per-tick death probability for agents below the low-rep threshold.',
        'src/engine/agentLifecycle.ts', [0.001, 0.1],
        'agentLifecycle → death check'),
      n('LOW_REP_THRESHOLD', agentLife.LOW_REP_THRESHOLD,
        'Reputation below which agents become vulnerable to death.',
        'src/engine/agentLifecycle.ts', [0.01, 0.3],
        'agentLifecycle → death eligibility'),
      n('BIRTH_CHANCE', agentLife.BIRTH_CHANCE,
        'Per-tick probability a new agent spawns at a location.',
        'src/engine/agentLifecycle.ts', [0.001, 0.05],
        'agentLifecycle → birth check'),
      n('BIRTH_DENSITY_THRESHOLD', agentLife.BIRTH_DENSITY_THRESHOLD,
        'Max agents at a location before births are suppressed.',
        'src/engine/agentLifecycle.ts', [1, 10],
        'agentLifecycle → density cap'),
      n('AMBITION_DRIFT_THRESHOLD', abc.AMBITION_DRIFT_THRESHOLD,
        'Minimum ambition magnitude to trigger drift behavior. Agent drifts when loyalty_ambition < -threshold.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'idleBehavior → drift trigger'),
      n('IDLE_DRIFT_SPEED', abc.IDLE_DRIFT_SPEED,
        'Number of hops an idle agent moves per tick when drifting.',
        'src/data/agent-behavior-constants.ts', [1, 3],
        'idleBehavior → drift movement'),
      n('IDLE_TRIVIAL_PREFERENCE', abc.IDLE_TRIVIAL_PREFERENCE,
        'Probability a loyal/neutral agent picks a trivial local encounter when idle.',
        'src/data/agent-behavior-constants.ts', [0.3, 1.0],
        'idleBehavior → trivial preference'),
      n('IDLE_MAX_AWARENESS_HOPS', abc.IDLE_MAX_AWARENESS_HOPS,
        'Max hops to consider when searching for idle drift targets.',
        'src/data/agent-behavior-constants.ts', [3, 10],
        'idleBehavior → drift range'),
      n('MILESTONE_CHECK_INTERVAL', ambitionTick.MILESTONE_CHECK_INTERVAL,
        'Ticks between ambition milestone checks.',
        'src/engine/ambitionTick.ts', [5, 50],
        'ambitionTick → milestone timing'),
      n('AMBITION_REEVAL_INTERVAL', ambitionTick.AMBITION_REEVAL_INTERVAL,
        'Ticks between ambition re-evaluation checks.',
        'src/engine/ambitionTick.ts', [10, 100],
        'ambitionTick → re-evaluation timing'),
      n('PRIMARY_AMBITION_WEIGHT', ambitionBoost.PRIMARY_AMBITION_WEIGHT,
        'Weight of primary ambition in movement scoring.',
        'src/engine/ambitionBoost.ts', [0.1, 1.0],
        'ambitionBoost → movement motivation'),
      n('SECONDARY_AMBITION_WEIGHT', ambitionBoost.SECONDARY_AMBITION_WEIGHT,
        'Weight of secondary ambition in movement scoring.',
        'src/engine/ambitionBoost.ts', [0.0, 0.5],
        'ambitionBoost → secondary motivation'),
      n('GRAVITY_SPHERE_WEIGHT', culturalGrav.GRAVITY_SPHERE_WEIGHT,
        'Weight of sphere alignment in cultural gravity calculation.',
        'src/engine/culturalGravity.ts', [0.0, 1.0],
        'culturalGravity → alignment score'),
      n('GRAVITY_REACH_WEIGHT', culturalGrav.GRAVITY_REACH_WEIGHT,
        'Weight of reach alignment in cultural gravity calculation.',
        'src/engine/culturalGravity.ts', [0.0, 1.0],
        'culturalGravity → alignment score'),
      n('GRAVITY_FOUNDATION_WEIGHT', culturalGrav.GRAVITY_FOUNDATION_WEIGHT,
        'Weight of foundation alignment in cultural gravity calculation.',
        'src/engine/culturalGravity.ts', [0.0, 1.0],
        'culturalGravity → alignment score'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 7. SOCIAL FABRIC
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'social',
    label: 'Social Fabric',
    description: 'Trust, reputation, social encounters, and relationship dynamics.',
    constants: [
      n('TRUST_COOPERATE_DELTA', abc.TRUST_COOPERATE_DELTA,
        'Trust gain from a cooperative interaction.',
        'src/data/agent-behavior-constants.ts', [0.01, 0.1],
        'trustMechanics → cooperate event'),
      n('TRUST_DEFECT_DELTA', abc.TRUST_DEFECT_DELTA,
        'Trust loss from a defective interaction. Asymmetric — betrayal hurts more.',
        'src/data/agent-behavior-constants.ts', [-0.2, -0.03],
        'trustMechanics → defect event'),
      n('TRUST_DECAY_PER_TICK', abc.TRUST_DECAY_PER_TICK,
        'Trust decay toward 0 per tick. Lower = memories linger longer.',
        'src/data/agent-behavior-constants.ts', [0.001, 0.01],
        'trustMechanics → per-tick decay'),
      n('REPUTATION_MAX_HOPS', abc.REPUTATION_MAX_HOPS,
        'Max hops for indirect reputation walks. Higher = more distant gossip travels.',
        'src/data/agent-behavior-constants.ts', [2, 6],
        'reputationWalk → walk depth'),
      n('UNKNOWN_REPUTATION', abc.UNKNOWN_REPUTATION,
        'Default reputation when no path exists between agents. 0 = neutral strangers.',
        'src/data/agent-behavior-constants.ts', [-0.5, 0.5],
        'reputationWalk → no-path fallback'),
      n('SHADOW_DISTORTION_FACTOR', abc.SHADOW_DISTORTION_FACTOR,
        'Multiplier for Shadow capability distortion by intermediaries. Higher = more manipulation.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.3],
        'reputationWalk → shadow distortion'),
      n('HEART_TRUST_FACTOR', abc.HEART_TRUST_FACTOR,
        'Multiplier for Heart capability trust resistance. Higher = heart agents resist distortion more.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'reputationWalk → heart resistance'),
      n('FACTION_RANK_TRUST_BONUS', abc.FACTION_RANK_TRUST_BONUS,
        'Trust bonus per intermediary sharing a faction with the source.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.2],
        'reputationWalk → faction bonus'),
      n('STRONG_BOND_THRESHOLD', abc.STRONG_BOND_THRESHOLD,
        'Trust above this triggers cooperative bond boost in social encounters.',
        'src/data/agent-behavior-constants.ts', [0.3, 0.8],
        'socialEncounterGeneration → bond check'),
      n('HOSTILE_BOND_THRESHOLD', abc.HOSTILE_BOND_THRESHOLD,
        'Trust below this triggers hostile bond boost.',
        'src/data/agent-behavior-constants.ts', [-0.6, -0.1],
        'socialEncounterGeneration → hostility check'),
      n('COOPERATIVE_BOND_BOOST', abc.COOPERATIVE_BOND_BOOST,
        'Score boost for cooperative social encounters with strong bonds.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.6],
        'socialEncounterGeneration → scoring'),
      n('RIVAL_BOND_BOOST', abc.RIVAL_BOND_BOOST,
        'Score boost for destructive social encounters with hostile bonds.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'socialEncounterGeneration → scoring'),
      n('STRANGER_MODIFIER', abc.STRANGER_MODIFIER,
        'Score penalty for encounters with unknown agents.',
        'src/data/agent-behavior-constants.ts', [-0.3, 0.0],
        'socialEncounterGeneration → stranger penalty'),
      n('STRANGER_CURIOSITY_THRESHOLD', abc.STRANGER_CURIOSITY_THRESHOLD,
        'Eye capability threshold above which the agent gets a curiosity bonus.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'socialEncounterGeneration → eye capability gate'),
      n('STRANGER_CURIOSITY_BONUS', abc.STRANGER_CURIOSITY_BONUS,
        'Curiosity bonus for perceptive agents encountering strangers.',
        'src/data/agent-behavior-constants.ts', [0.05, 0.3],
        'socialEncounterGeneration → curiosity boost'),
      n('MAX_SOCIAL_CANDIDATES_PER_AGENT', abc.MAX_SOCIAL_CANDIDATES_PER_AGENT,
        'Max social encounter templates generated per target agent.',
        'src/data/agent-behavior-constants.ts', [1, 5],
        'socialEncounterGeneration → candidate cap'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 8. MOVEMENT & PATHFINDING
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'movement',
    label: 'Movement & Pathfinding',
    description: 'Traversal costs, pathfinding motivation, and movement decision thresholds.',
    constants: [
      n('BASE_EDGE_TRAVERSAL_COST', movement.BASE_EDGE_TRAVERSAL_COST,
        'Base cost to traverse any edge. All terrain and location taxes add to this.',
        'src/data/movement-content.ts', [1, 20],
        'movementCost → edge cost calculation'),
      n('DECISION_REEVALUATION_TICKS', movement.DECISION_REEVALUATION_TICKS,
        'How often agents reconsider their destination. Lower = more reactive.',
        'src/data/movement-content.ts', [1, 20],
        'movementExecution → re-evaluation check'),
      n('TRAIL_HISTORY_TICKS', movement.TRAIL_HISTORY_TICKS,
        'How long movement trail entries persist.',
        'src/data/movement-content.ts', [5, 100],
        'movementExecution → trail cleanup'),
      n('DISTANCE_DECAY_FACTOR', movement.DISTANCE_DECAY_FACTOR,
        'How quickly motivation decays with distance. Higher = closer targets strongly preferred.',
        'src/data/movement-content.ts', [0.01, 1.0],
        'pathfinding → distance penalty'),
      n('MIN_EDGE_COST', movement.MIN_EDGE_COST,
        'Absolute minimum edge cost (prevents zero/negative costs).',
        'src/data/movement-content.ts', [0.1, 5.0],
        'movementCost → clamp'),
      n('MAX_CANDIDATE_DISTANCE', movement.MAX_CANDIDATE_DISTANCE,
        'Max graph distance for destination candidates.',
        'src/data/movement-content.ts', [3, 20],
        'pathfinding → candidate range'),
      n('P0_BASE_MOTIVATION_PULL', movement.P0_BASE_MOTIVATION_PULL,
        'Base motivation strength for primary objective pull.',
        'src/data/movement-content.ts', [0.1, 2.0],
        'pathfinding → motivation scoring'),
      n('P0_AMBITION_WEIGHT', movement.P0_AMBITION_WEIGHT,
        'Weight of ambition alignment in movement motivation.',
        'src/data/movement-content.ts', [0.0, 1.0],
        'pathfinding → ambition pull'),
      n('DEFAULT_QUEST_PRIORITY', movement.DEFAULT_QUEST_PRIORITY,
        'Default priority assigned to quest-driven movement.',
        'src/data/movement-content.ts', [0.1, 5.0],
        'pathfinding → quest priority'),
      n('MOVEMENT_SCORE_THRESHOLD', movement.MOVEMENT_SCORE_THRESHOLD,
        'Minimum movement score to trigger relocation. Below this agents stay put.',
        'src/data/movement-content.ts', [0.0, 1.0],
        'movementExecution → move vs stay decision'),
      n('MOVEMENT_EVENT_SIGNIFICANCE', movement.MOVEMENT_EVENT_SIGNIFICANCE,
        'Significance level of movement trace events.',
        'src/data/movement-content.ts', [0.0, 1.0],
        'movementExecution → trace significance'),
      n('THREAT_MODIFIER_FLOOR', movement.THREAT_MODIFIER_FLOOR,
        'Floor value for threat modifier in movement calculations.',
        'src/data/movement-content.ts', [-1.0, 0.0],
        'movementCost → threat adjustment'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 9. ECONOMY & SETTLEMENTS
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'economy',
    label: 'Economy & Settlements',
    description: 'Wealth, trade, prosperity, guilds, sublocations, unrest, and settlement growth.',
    constants: [
      // Wealth
      n('WEALTH_TRADE_SUCCESS_MIN', wealth.WEALTH_TRADE_SUCCESS_MIN,
        'Minimum wealth gain on a successful trade action.',
        'src/engine/wealth.ts', [1, 10],
        'wealth → trade success delta'),
      n('WEALTH_TRADE_SUCCESS_MAX', wealth.WEALTH_TRADE_SUCCESS_MAX,
        'Maximum wealth gain on a successful trade action.',
        'src/engine/wealth.ts', [2, 20],
        'wealth → trade success delta'),
      n('WEALTH_ROUTE_CONTROL_INCOME', wealth.WEALTH_ROUTE_CONTROL_INCOME,
        'Passive wealth per controlled trade route per tick.',
        'src/engine/wealth.ts', [0, 5],
        'wealth → passive income'),
      n('WEALTH_SUBLOCATION_INCOME', wealth.WEALTH_SUBLOCATION_INCOME,
        'Passive wealth per productive sublocation per tick.',
        'src/engine/wealth.ts', [0, 5],
        'wealth → sublocation income'),
      n('WEALTH_PROSPEROUS_HOME_INCOME', wealth.WEALTH_PROSPEROUS_HOME_INCOME,
        'Passive wealth when home settlement prosperity ≥ PROSPERITY_TIER_PROSPEROUS.',
        'src/engine/wealth.ts', [0, 5],
        'wealth → prosperity bonus'),
      n('WEALTH_TRADE_FAILURE_MIN', wealth.WEALTH_TRADE_FAILURE_MIN,
        'Minimum wealth loss on a failed trade action.',
        'src/engine/wealth.ts', [0, 5],
        'wealth → trade failure delta'),
      n('WEALTH_TRADE_FAILURE_MAX', wealth.WEALTH_TRADE_FAILURE_MAX,
        'Maximum wealth loss on a failed trade action.',
        'src/engine/wealth.ts', [1, 10],
        'wealth → trade failure delta'),
      n('WEALTH_ROUTE_DISRUPTED_PENALTY', wealth.WEALTH_ROUTE_DISRUPTED_PENALTY,
        'Wealth loss per disrupted route.',
        'src/engine/wealth.ts', [0, 10],
        'wealth → route disruption'),
      n('WEALTH_AGREEMENT_BROKEN_MIN', wealth.WEALTH_AGREEMENT_BROKEN_MIN,
        'Minimum wealth loss when an agreement is broken against you.',
        'src/engine/wealth.ts', [1, 10],
        'wealth → agreement broken'),
      n('WEALTH_AGREEMENT_BROKEN_MAX', wealth.WEALTH_AGREEMENT_BROKEN_MAX,
        'Maximum wealth loss when an agreement is broken against you.',
        'src/engine/wealth.ts', [2, 15],
        'wealth → agreement broken'),
      n('WEALTH_MERCENARY_COST', wealth.WEALTH_MERCENARY_COST,
        'Cost (wealth) to hire mercenaries.',
        'src/engine/wealth.ts', [1, 50],
        'wealth → mercenary action'),
      n('WEALTH_ASSASSINATION_COST', wealth.WEALTH_ASSASSINATION_COST,
        'Cost (wealth) to commission an assassination.',
        'src/engine/wealth.ts', [5, 50],
        'wealth → assassination action'),
      n('WEALTH_INFLUENCE_COST', wealth.WEALTH_INFLUENCE_COST,
        'Cost (wealth) to buy influence with a faction or agent.',
        'src/engine/wealth.ts', [1, 30],
        'wealth → influence action'),
      n('WEALTH_CONSTRUCTION_COST', wealth.WEALTH_CONSTRUCTION_COST,
        'Cost (wealth) to fund construction of a sublocation.',
        'src/engine/wealth.ts', [5, 50],
        'wealth → construction action'),
      n('WEALTH_MONOPOLY_COST', wealth.WEALTH_MONOPOLY_COST,
        'Cost (wealth) to establish a monopoly over a resource type.',
        'src/engine/wealth.ts', [10, 100],
        'wealth → monopoly action'),
      n('WEALTH_TIER_MAGNATE', wealth.WEALTH_TIER_MAGNATE,
        'Wealth threshold for "Magnate" tier label.',
        'src/engine/wealth.ts', [50, 100],
        'wealth → tier label'),
      n('WEALTH_TIER_WEALTHY', wealth.WEALTH_TIER_WEALTHY,
        'Wealth threshold for "Wealthy" tier label.',
        'src/engine/wealth.ts', [30, 80],
        'wealth → tier label'),
      n('WEALTH_TIER_COMFORTABLE', wealth.WEALTH_TIER_COMFORTABLE,
        'Wealth threshold for "Comfortable" tier label.',
        'src/engine/wealth.ts', [10, 60],
        'wealth → tier label'),
      n('WEALTH_TIER_GETTING_BY', wealth.WEALTH_TIER_GETTING_BY,
        'Wealth threshold for "Getting By" tier label.',
        'src/engine/wealth.ts', [5, 40],
        'wealth → tier label'),
      // Prosperity
      n('PROSPERITY_DELTA_CLAMP', prosperity.PROSPERITY_DELTA_CLAMP,
        'Max absolute prosperity change per tick. Limits how fast settlements boom or bust.',
        'src/engine/phaseProsperity.ts', [1, 25],
        'phaseProsperity → delta clamp'),
      n('PROSPERITY_TRADE_BONUS_PER_ROUTE', prosperity.PROSPERITY_TRADE_BONUS_PER_ROUTE,
        'Prosperity gain per active trades_with edge, scaled by normalised volume.',
        'src/engine/phaseProsperity.ts', [0.5, 10],
        'phaseProsperity → trade bonus'),
      n('PROSPERITY_TIER_FLOURISHING', prosperity.PROSPERITY_TIER_FLOURISHING,
        'Prosperity threshold for "Flourishing" prose / promotion eligibility.',
        'src/engine/phaseProsperity.ts', [60, 100],
        'phaseProsperity → tier label + settlement promotion'),
      n('PROSPERITY_TIER_PROSPEROUS', prosperity.PROSPERITY_TIER_PROSPEROUS,
        'Prosperity threshold for "Prosperous" prose / passive wealth generation.',
        'src/engine/phaseProsperity.ts', [40, 80],
        'phaseProsperity → tier label + wealth gate'),
      n('PROSPERITY_TIER_MODEST', prosperity.PROSPERITY_TIER_MODEST,
        'Prosperity threshold for "Modest" prose / Market District spawn.',
        'src/engine/phaseProsperity.ts', [20, 60],
        'phaseProsperity → tier label + market spawn'),
      n('PROSPERITY_TIER_STRUGGLING', prosperity.PROSPERITY_TIER_STRUGGLING,
        'Prosperity threshold for "Struggling" prose / sublocation dissolution / demotion.',
        'src/engine/phaseProsperity.ts', [5, 40],
        'phaseProsperity → tier label + dissolution gate'),
      n('POPULATION_LAG_TICKS_MIN', prosperity.POPULATION_LAG_TICKS_MIN,
        'Minimum population lag ticks (seeded per settlement at creation via PRNG).',
        'src/engine/phaseProsperity.ts', [1, 5],
        'phaseProsperity → population inertia'),
      n('POPULATION_LAG_TICKS_MAX', prosperity.POPULATION_LAG_TICKS_MAX,
        'Maximum population lag ticks.',
        'src/engine/phaseProsperity.ts', [1, 10],
        'phaseProsperity → population inertia'),
      n('SETTLEMENT_PROMOTION_PROSPERITY', prosperity.SETTLEMENT_PROMOTION_PROSPERITY,
        'Sustained prosperity required for hamlet → town → city promotion.',
        'src/engine/phaseProsperity.ts', [50, 95],
        'phaseProsperity → settlement promotion'),
      n('SETTLEMENT_PROMOTION_SUSTAIN_TICKS', prosperity.SETTLEMENT_PROMOTION_SUSTAIN_TICKS,
        'Ticks prosperity must stay above promotion threshold.',
        'src/engine/phaseProsperity.ts', [1, 20],
        'phaseProsperity → sustained check'),
      n('SETTLEMENT_DEMOTION_PROSPERITY', prosperity.SETTLEMENT_DEMOTION_PROSPERITY,
        'Sustained low prosperity required for city → town → hamlet demotion.',
        'src/engine/phaseProsperity.ts', [5, 40],
        'phaseProsperity → settlement demotion'),
      // Guilds
      n('GUILD_SPAWN_COUNT_MIN', guild.GUILD_SPAWN_COUNT_MIN,
        'Minimum guilds spawned per settlement at world creation.',
        'src/engine/guildSeeding.ts', [0, 5],
        'guildSeeding → spawn count'),
      n('GUILD_SPAWN_COUNT_MAX', guild.GUILD_SPAWN_COUNT_MAX,
        'Maximum guilds spawned per settlement at world creation.',
        'src/engine/guildSeeding.ts', [1, 10],
        'guildSeeding → spawn count'),
      n('GUILD_GOLD_CAP_MIN', guild.GUILD_GOLD_CAP_MIN,
        'Minimum Gold reach capability cap for a guild.',
        'src/engine/guildSeeding.ts', [20, 100],
        'guildSeeding → capability range'),
      n('GUILD_GOLD_CAP_MAX', guild.GUILD_GOLD_CAP_MAX,
        'Maximum Gold reach capability cap for a guild.',
        'src/engine/guildSeeding.ts', [40, 100],
        'guildSeeding → capability range'),
      n('GUILD_SECONDARY_CAP_MIN', guild.GUILD_SECONDARY_CAP_MIN,
        'Minimum secondary reach cap for a guild.',
        'src/engine/guildSeeding.ts', [10, 60],
        'guildSeeding → secondary cap'),
      n('GUILD_SECONDARY_CAP_MAX', guild.GUILD_SECONDARY_CAP_MAX,
        'Maximum secondary reach cap for a guild.',
        'src/engine/guildSeeding.ts', [20, 80],
        'guildSeeding → secondary cap'),
      n('GUILD_MINOR_CAP_MIN', guild.GUILD_MINOR_CAP_MIN,
        'Minimum minor reach cap for a guild.',
        'src/engine/guildSeeding.ts', [0, 30],
        'guildSeeding → minor cap'),
      n('GUILD_MINOR_CAP_MAX', guild.GUILD_MINOR_CAP_MAX,
        'Maximum minor reach cap for a guild.',
        'src/engine/guildSeeding.ts', [5, 40],
        'guildSeeding → minor cap'),
      n('GUILD_MARKET_STALL_THRESHOLD', guild.GUILD_MARKET_STALL_THRESHOLD,
        'Prosperity at which a guild spawns a market stall.',
        'src/engine/guildSeeding.ts', [5, 50],
        'guildSeeding → market stall spawn'),
      // Sublocations
      n('SUBLOC_MARKET_SPAWN_PROSPERITY', subloc.SUBLOC_MARKET_SPAWN_PROSPERITY,
        'Prosperity at which a Market District spawns.',
        'src/engine/phaseSublocations.ts', [20, 80],
        'phaseSublocations → market spawn gate'),
      n('SUBLOC_MARKET_DISSOLVE_PROSPERITY', subloc.SUBLOC_MARKET_DISSOLVE_PROSPERITY,
        'Prosperity below which a Market District dissolves.',
        'src/engine/phaseSublocations.ts', [5, 40],
        'phaseSublocations → market dissolve gate'),
      n('SUBLOC_SMUGGLER_SPAWN_PROSPERITY', subloc.SUBLOC_SMUGGLER_SPAWN_PROSPERITY,
        'Prosperity at which a Smuggler\'s Den spawns.',
        'src/engine/phaseSublocations.ts', [10, 60],
        'phaseSublocations → smuggler spawn gate'),
      n('SUBLOC_MARKET_TRADE_BONUS', subloc.SUBLOC_MARKET_TRADE_BONUS,
        'Trade route bonus when a Market District exists.',
        'src/engine/phaseSublocations.ts', [0.01, 0.5],
        'phaseSublocations → trade modifier'),
      n('SUBLOC_MARKET_VOLUME_BONUS', subloc.SUBLOC_MARKET_VOLUME_BONUS,
        'Volume bonus when a Market District exists.',
        'src/engine/phaseSublocations.ts', [0.01, 0.5],
        'phaseSublocations → volume modifier'),
      n('MINE_PRODUCTION_PER_TICK', subloc.MINE_PRODUCTION_PER_TICK,
        'Resource units produced per mine per tick.',
        'src/engine/phaseSublocations.ts', [1, 10],
        'phaseSublocations → mine output'),
      n('GUILD_WAREHOUSE_THRESHOLD', subloc.GUILD_WAREHOUSE_THRESHOLD,
        'Guild capability threshold that triggers Warehouse sublocation.',
        'src/engine/phaseSublocations.ts', [10, 80],
        'phaseSublocations → warehouse spawn'),
      n('GUILD_COUNTING_HOUSE_THRESHOLD', subloc.GUILD_COUNTING_HOUSE_THRESHOLD,
        'Guild capability threshold that triggers Counting House sublocation.',
        'src/engine/phaseSublocations.ts', [20, 100],
        'phaseSublocations → counting house spawn'),
      // Unrest
      n('UNREST_DECAY_RATE', unrest.UNREST_DECAY_RATE,
        'Unrest points that decay per tick. Natural calming.',
        'src/engine/phaseUnrest.ts', [0, 5],
        'phaseUnrest → natural decay'),
      n('UNREST_PROSPERITY_DAMPER', unrest.UNREST_PROSPERITY_DAMPER,
        'How much prosperity dampens unrest gain. Higher = prosperous settlements resist unrest.',
        'src/engine/phaseUnrest.ts', [0.0, 1.0],
        'phaseUnrest → prosperity check'),
      n('UNREST_DEFECTION_THRESHOLD', unrest.UNREST_DEFECTION_THRESHOLD,
        'Unrest level at which agents start defecting from the settlement.',
        'src/engine/phaseUnrest.ts', [30, 100],
        'phaseUnrest → defection trigger'),
      n('UNREST_SACK_THRESHOLD', unrest.UNREST_SACK_THRESHOLD,
        'Unrest level at which the settlement is sacked (catastrophic collapse).',
        'src/engine/phaseUnrest.ts', [50, 100],
        'phaseUnrest → sack trigger'),
      // Trade routes
      n('TRADE_ROUTE_MAX_VOLUME', trade.TRADE_ROUTE_MAX_VOLUME,
        'Maximum trade volume on a single route.',
        'src/engine/tradeRoute.ts', [1, 50],
        'tradeRoute → volume cap'),
      n('TRADE_ROUTE_DECAY_RATE', trade.TRADE_ROUTE_DECAY_RATE,
        'Volume that decays per tick on unused routes.',
        'src/engine/tradeRoute.ts', [0, 5],
        'tradeRoute → inactivity decay'),
      n('TRADE_ROUTE_FRESHNESS_WINDOW', trade.TRADE_ROUTE_FRESHNESS_WINDOW,
        'Ticks after last trade before a route starts decaying.',
        'src/engine/tradeRoute.ts', [1, 20],
        'tradeRoute → freshness check'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 10. DIVINE INFLUENCE & HEX STATE
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'divine',
    label: 'Divine Influence & Hex State',
    description: 'Essence economy, divine focus/scry, hex corruption/blessing, magical saturation.',
    constants: [
      // Essence economy
      n('BASE_ESSENCE_PER_TICK', influence.BASE_ESSENCE_PER_TICK,
        'Base essence generated per tick regardless of worshippers.',
        'src/data/influence-content.ts', [0, 10],
        'essenceAccumulation → base generation'),
      n('ESSENCE_PER_WORSHIPPER', influence.ESSENCE_PER_WORSHIPPER,
        'Additional essence per worshipper per tick.',
        'src/data/influence-content.ts', [0, 5],
        'essenceAccumulation → worshipper bonus'),
      n('ESSENCE_PER_PLACE_OF_POWER', influence.ESSENCE_PER_PLACE_OF_POWER,
        'Essence from each place of power per tick.',
        'src/data/influence-content.ts', [0, 10],
        'essenceAccumulation → place bonus'),
      n('BASE_MAX_ESSENCE', influence.BASE_MAX_ESSENCE,
        'Starting max essence capacity.',
        'src/data/influence-content.ts', [10, 500],
        'essenceAccumulation → capacity cap'),
      n('MAX_ESSENCE_PER_WORSHIPPER', influence.MAX_ESSENCE_PER_WORSHIPPER,
        'Max essence increase per worshipper.',
        'src/data/influence-content.ts', [0, 50],
        'essenceAccumulation → capacity growth'),
      n('RECRUIT_COST', influence.RECRUIT_COST,
        'Essence cost to recruit a new worshipper.',
        'src/data/influence-content.ts', [1, 100],
        'divineActions → recruit'),
      n('DISCOVER_COST', influence.DISCOVER_COST,
        'Essence cost to discover an agent.',
        'src/data/influence-content.ts', [1, 50],
        'divineActions → discover'),
      n('OBSERVE_COST', influence.OBSERVE_COST,
        'Essence cost to observe an agent.',
        'src/data/influence-content.ts', [1, 50],
        'divineActions → observe'),
      // Divine attention
      n('ATTUNE_COST_DISCOUNT', abc.ATTUNE_COST_DISCOUNT,
        'Essence cost reduction when attuned to a hex.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'divineAttention → attunement discount'),
      n('SCRY_DURATION_TICKS', abc.SCRY_DURATION_TICKS,
        'How long Scry grants awareness (in ticks).',
        'src/data/agent-behavior-constants.ts', [5, 20],
        'divineAttention → scry duration'),
      n('FOCUS_DURATION_TICKS', abc.FOCUS_DURATION_TICKS,
        'How long Divine Focus lasts (in ticks).',
        'src/data/agent-behavior-constants.ts', [1, 5],
        'divineAttention → focus duration'),
      n('FOCUS_EFFICIENCY_BOOST', abc.FOCUS_EFFICIENCY_BOOST,
        'Bond efficiency bonus during Focus.',
        'src/data/agent-behavior-constants.ts', [0.2, 0.6],
        'divineAttention → focus efficiency'),
      // Intervention cost
      n('INTERVENTION_MAX_BONUS', abc.INTERVENTION_MAX_BONUS,
        'Hard cap on probability bonus from divine intervention.',
        'src/data/agent-behavior-constants.ts', [0.10, 0.30],
        'interventionCost → bonus clamp'),
      n('OPPOSING_SPHERE_COST_MULTIPLIER', abc.OPPOSING_SPHERE_COST_MULTIPLIER,
        'Cost multiplier for opposing spheres.',
        'src/data/agent-behavior-constants.ts', [2.0, 5.0],
        'interventionCost → sphere cost'),
      n('NEUTRAL_SPHERE_COST_MULTIPLIER', abc.NEUTRAL_SPHERE_COST_MULTIPLIER,
        'Cost multiplier for unrelated spheres.',
        'src/data/agent-behavior-constants.ts', [1.2, 2.0],
        'interventionCost → sphere cost'),
      // Hex state
      n('HEX_DIVINE_INFLUENCE_DECAY_RATE', hexState.HEX_DIVINE_INFLUENCE_DECAY_RATE,
        'Per-tick decay of divine influence on hexes. Lower = blessings last longer.',
        'src/engine/phaseHexState.ts', [0.001, 0.1],
        'phaseHexState → influence decay'),
      n('HEX_CORRUPTION_DECAY_RATE', hexState.HEX_CORRUPTION_DECAY_RATE,
        'Per-tick decay of corruption on hexes. Lower = corruption lingers.',
        'src/engine/phaseHexState.ts', [0.001, 0.1],
        'phaseHexState → corruption decay'),
      n('HEX_CORRUPTION_TRANSFORM_THRESHOLD', hexState.HEX_CORRUPTION_TRANSFORM_THRESHOLD,
        'Corruption level at which the hex terrain transforms.',
        'src/engine/phaseHexState.ts', [0.3, 1.0],
        'phaseHexState → terrain transformation'),
      n('HEX_DIVINE_TRANSFORM_THRESHOLD', hexState.HEX_DIVINE_TRANSFORM_THRESHOLD,
        'Divine influence level at which the hex terrain transforms.',
        'src/engine/phaseHexState.ts', [0.3, 1.0],
        'phaseHexState → terrain transformation'),
      n('HEX_TRANSFORM_COOLDOWN_TICKS', hexState.HEX_TRANSFORM_COOLDOWN_TICKS,
        'Minimum ticks between hex terrain transformations.',
        'src/engine/phaseHexState.ts', [1, 50],
        'phaseHexState → cooldown gate'),
      n('HEX_INFLUENCE_VISIBILITY_THRESHOLD', hexState.HEX_INFLUENCE_VISIBILITY_THRESHOLD,
        'Influence level at which divine presence becomes visible on the map.',
        'src/engine/phaseHexState.ts', [0.1, 0.8],
        'phaseHexState → visibility gate'),
      // Hex actions
      n('HEX_BLESS_INFLUENCE_DELTA', hexAction.HEX_BLESS_INFLUENCE_DELTA,
        'Divine influence gained when blessing a hex.',
        'src/engine/hexActionBridge.ts', [0.1, 1.0],
        'hexActionBridge → bless action'),
      n('HEX_CORRUPT_CORRUPTION_DELTA', hexAction.HEX_CORRUPT_CORRUPTION_DELTA,
        'Corruption gained when corrupting a hex.',
        'src/engine/hexActionBridge.ts', [0.1, 1.0],
        'hexActionBridge → corrupt action'),
      n('HEX_SEED_INFLUENCE_DELTA', hexAction.HEX_SEED_INFLUENCE_DELTA,
        'Influence gained when seeding a place of power.',
        'src/engine/hexActionBridge.ts', [0.1, 1.0],
        'hexActionBridge → seed action'),
      n('HEX_SURVEY_VISIBILITY_RADIUS', hexAction.HEX_SURVEY_VISIBILITY_RADIUS,
        'Number of hex rings revealed by a survey action.',
        'src/engine/hexActionBridge.ts', [1, 5],
        'hexActionBridge → survey action'),
      // Magical saturation
      n('MAGICAL_SATURATION_DECAY_RATE', magSat.MAGICAL_SATURATION_DECAY_RATE,
        'Per-tick decay of magical saturation.',
        'src/engine/phaseMagicalSaturation.ts', [0.001, 0.1],
        'phaseMagicalSaturation → decay'),
      n('MAGICAL_SATURATION_VEIL_BONUS_THRESHOLD', magSat.MAGICAL_SATURATION_VEIL_BONUS_THRESHOLD,
        'Saturation level at which veil bonus kicks in.',
        'src/engine/phaseMagicalSaturation.ts', [0.1, 0.9],
        'phaseMagicalSaturation → veil gate'),
      n('MAGICAL_SATURATION_VISIBILITY_THRESHOLD', magSat.MAGICAL_SATURATION_VISIBILITY_THRESHOLD,
        'Saturation level at which magical effects become visible.',
        'src/engine/phaseMagicalSaturation.ts', [0.1, 0.8],
        'phaseMagicalSaturation → visibility gate'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 11. THREAT & ENCOUNTER CACHE
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'threat',
    label: 'Threat & Encounter Cache',
    description: 'Threat level calculation weights and encounter cache tuning.',
    constants: [
      n('THREAT_FACTION_WEIGHT', threat.THREAT_FACTION_WEIGHT,
        'Faction hostility contribution to threat level.',
        'src/data/threat-content.ts', [0.0, 2.0],
        'threatCalculation → faction component'),
      n('THREAT_HOSTILE_AGENT_WEIGHT', threat.THREAT_HOSTILE_AGENT_WEIGHT,
        'Hostile agent contribution to threat level.',
        'src/data/threat-content.ts', [0.0, 2.0],
        'threatCalculation → agent component'),
      n('THREAT_ENCOUNTER_WEIGHT', threat.THREAT_ENCOUNTER_WEIGHT,
        'Active encounter contribution to threat level.',
        'src/data/threat-content.ts', [0.0, 2.0],
        'threatCalculation → encounter component'),
      n('THREAT_CULTURE_WEIGHT', threat.THREAT_CULTURE_WEIGHT,
        'Cultural tension contribution to threat level.',
        'src/data/threat-content.ts', [0.0, 2.0],
        'threatCalculation → culture component'),
      n('HOSTILE_STRATEGY_THRESHOLD', threat.HOSTILE_STRATEGY_THRESHOLD,
        'Cooperation score below which an agent is considered hostile.',
        'src/data/threat-content.ts', [-1.0, 0.5],
        'threatCalculation → hostility gate'),
      n('CACHE_REBUILD_THRESHOLD', abc.CACHE_REBUILD_THRESHOLD,
        'When dirty-entry count exceeds this, a full cache rebuild is cheaper than patching.',
        'src/data/agent-behavior-constants.ts', [20, 100],
        'encounterCache → rebuild decision'),
      n('REPUTATION_REWARD_WEIGHT', abc.REPUTATION_REWARD_WEIGHT,
        'Weight of reputation deltas in reward estimate.',
        'src/data/agent-behavior-constants.ts', [0.5, 2.0],
        'encounterCache → reward estimate'),
      n('LOOT_REWARD_WEIGHT', abc.LOOT_REWARD_WEIGHT,
        'Weight of loot availability in reward estimate.',
        'src/data/agent-behavior-constants.ts', [0.1, 1.0],
        'encounterCache → reward estimate'),
      n('DOMAIN_EXERCISE_WEIGHT', abc.DOMAIN_EXERCISE_WEIGHT,
        'Base weight for domain exercise opportunity in reward estimate.',
        'src/data/agent-behavior-constants.ts', [0.1, 0.5],
        'encounterCache → reward estimate'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 12. WORLD GENERATION — Terrain Pipeline
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'worldgen-terrain',
    label: 'World Generation — Terrain',
    description: 'Continent placement, tectonics, elevation, climate, rivers, lakes, and regions.',
    constants: [
      n('CONTINENT_COUNT_MIN', terrainTypes.CONTINENT_COUNT_MIN,
        'Minimum continents generated.',
        'src/engine/terrainPipeline/types.ts', [1, 6],
        'terrainPipeline → continent placement'),
      n('CONTINENT_COUNT_MAX', terrainTypes.CONTINENT_COUNT_MAX,
        'Maximum continents generated.',
        'src/engine/terrainPipeline/types.ts', [2, 8],
        'terrainPipeline → continent placement'),
      n('LAND_TARGET_MIN', terrainTypes.LAND_TARGET_MIN,
        'Minimum fraction of hexes that should be land.',
        'src/engine/terrainPipeline/types.ts', [0.3, 0.8],
        'terrainPipeline → land/sea ratio'),
      n('LAND_TARGET_MAX', terrainTypes.LAND_TARGET_MAX,
        'Maximum fraction of hexes that should be land.',
        'src/engine/terrainPipeline/types.ts', [0.4, 0.9],
        'terrainPipeline → land/sea ratio'),
      n('CONTINENT_RADIUS_MIN', terrainTypes.CONTINENT_RADIUS_MIN,
        'Minimum continent radius in hexes.',
        'src/engine/terrainPipeline/types.ts', [4, 15],
        'terrainPipeline → continent sizing'),
      n('CONTINENT_RADIUS_MAX', terrainTypes.CONTINENT_RADIUS_MAX,
        'Maximum continent radius in hexes.',
        'src/engine/terrainPipeline/types.ts', [10, 30],
        'terrainPipeline → continent sizing'),
      n('FAULT_COUNT_MIN', terrainTypes.FAULT_COUNT_MIN,
        'Minimum tectonic fault lines.',
        'src/engine/terrainPipeline/types.ts', [1, 8],
        'terrainPipeline → mountain chain placement'),
      n('FAULT_COUNT_MAX', terrainTypes.FAULT_COUNT_MAX,
        'Maximum tectonic fault lines.',
        'src/engine/terrainPipeline/types.ts', [2, 12],
        'terrainPipeline → mountain chain placement'),
      n('MOUNTAIN_SPINE_WIDTH', terrainTypes.MOUNTAIN_SPINE_WIDTH,
        'Width of mountain spine along fault lines in hexes.',
        'src/engine/terrainPipeline/types.ts', [1, 5],
        'terrainPipeline → mountain width'),
      n('FAULT_CONTROL_POINTS', terrainTypes.FAULT_CONTROL_POINTS,
        'Number of control points per fault line curve.',
        'src/engine/terrainPipeline/types.ts', [2, 8],
        'terrainPipeline → fault line shape'),
      n('ELEVATION_MOUNTAIN_BASE', terrainTypes.ELEVATION_MOUNTAIN_BASE,
        'Base elevation assigned to mountain hexes.',
        'src/engine/terrainPipeline/types.ts', [0.5, 1.0],
        'terrainPipeline → elevation assignment'),
      n('ELEVATION_FALLOFF_RATE', terrainTypes.ELEVATION_FALLOFF_RATE,
        'How quickly elevation drops away from mountains.',
        'src/engine/terrainPipeline/types.ts', [0.01, 0.2],
        'terrainPipeline → elevation gradient'),
      n('ELEVATION_NOISE_AMPLITUDE', terrainTypes.ELEVATION_NOISE_AMPLITUDE,
        'Amplitude of Perlin noise added to elevation.',
        'src/engine/terrainPipeline/types.ts', [0.05, 0.4],
        'terrainPipeline → elevation variation'),
      n('TEMP_ALTITUDE_PENALTY', terrainTypes.TEMP_ALTITUDE_PENALTY,
        'Temperature reduction per unit elevation.',
        'src/engine/terrainPipeline/types.ts', [0.1, 0.6],
        'terrainPipeline → climate model'),
      n('TEMP_BASE_RANGE', terrainTypes.TEMP_BASE_RANGE,
        'Base temperature range (equator = 1.0, poles = 0).',
        'src/engine/terrainPipeline/types.ts', [0.5, 1.0],
        'terrainPipeline → climate model'),
      n('WIND_DIRECTION', terrainTypes.WIND_DIRECTION,
        'Prevailing wind direction (-1 = west-to-east, 1 = east-to-west).',
        'src/engine/terrainPipeline/types.ts', [-1, 1],
        'terrainPipeline → moisture/rain shadow'),
      n('MOISTURE_COAST_BONUS', terrainTypes.MOISTURE_COAST_BONUS,
        'Moisture bonus for coastal hexes.',
        'src/engine/terrainPipeline/types.ts', [0.1, 0.6],
        'terrainPipeline → moisture model'),
      n('RAIN_SHADOW_FACTOR', terrainTypes.RAIN_SHADOW_FACTOR,
        'How much mountains block moisture (rain shadow effect).',
        'src/engine/terrainPipeline/types.ts', [0.1, 0.8],
        'terrainPipeline → rain shadow'),
      n('MOISTURE_BASE', terrainTypes.MOISTURE_BASE,
        'Base moisture for all land hexes.',
        'src/engine/terrainPipeline/types.ts', [0.0, 0.5],
        'terrainPipeline → moisture model'),
      n('RIVER_SOURCE_COUNT', terrainTypes.RIVER_SOURCE_COUNT,
        'Number of river sources placed on the map.',
        'src/engine/terrainPipeline/types.ts', [2, 20],
        'terrainPipeline → river generation'),
      n('RIVER_MIN_LENGTH', terrainTypes.RIVER_MIN_LENGTH,
        'Minimum river length in hexes (shorter rivers are discarded).',
        'src/engine/terrainPipeline/types.ts', [2, 10],
        'terrainPipeline → river validation'),
      n('LAKE_SIZE_MAX', terrainTypes.LAKE_SIZE_MAX,
        'Maximum size of a normal lake in hexes.',
        'src/engine/terrainPipeline/types.ts', [1, 15],
        'terrainPipeline → lake generation'),
      n('GREAT_LAKE_SIZE_MAX', terrainTypes.GREAT_LAKE_SIZE_MAX,
        'Maximum size of a great lake in hexes.',
        'src/engine/terrainPipeline/types.ts', [5, 30],
        'terrainPipeline → great lake generation'),
      n('GREAT_LAKE_CHANCE', terrainTypes.GREAT_LAKE_CHANCE,
        'Probability that a lake becomes a great lake.',
        'src/engine/terrainPipeline/types.ts', [0.0, 0.5],
        'terrainPipeline → great lake roll'),
      n('REGION_SIZE_MIN', terrainTypes.REGION_SIZE_MIN,
        'Minimum hexes per named region.',
        'src/engine/terrainPipeline/types.ts', [3, 20],
        'terrainPipeline → region partitioning'),
      n('REGION_SIZE_MAX', terrainTypes.REGION_SIZE_MAX,
        'Maximum hexes per named region.',
        'src/engine/terrainPipeline/types.ts', [15, 80],
        'terrainPipeline → region partitioning'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 13. WORLD GENERATION — Noise & Force Fields
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'worldgen-noise',
    label: 'World Generation — Noise',
    description: 'Perlin noise parameters for elevation, temperature, and moisture force fields.',
    constants: [
      n('ELEVATION_SCALE', forceField.ELEVATION_SCALE,
        'Frequency of elevation Perlin noise. Higher = more rugged terrain.',
        'src/engine/forceField.ts', [0.01, 0.2],
        'forceField → elevation noise'),
      n('ELEVATION_OCTAVES', forceField.ELEVATION_OCTAVES,
        'Octaves for elevation noise. Higher = more detail/complexity.',
        'src/engine/forceField.ts', [1, 8],
        'forceField → elevation noise'),
      n('ELEVATION_PERSISTENCE', forceField.ELEVATION_PERSISTENCE,
        'Amplitude decay per octave for elevation. Higher = rougher.',
        'src/engine/forceField.ts', [0.1, 0.9],
        'forceField → elevation noise'),
      n('ELEVATION_LACUNARITY', forceField.ELEVATION_LACUNARITY,
        'Frequency increase per octave for elevation.',
        'src/engine/forceField.ts', [1.0, 4.0],
        'forceField → elevation noise'),
      n('TEMP_NOISE_SCALE', forceField.TEMP_NOISE_SCALE,
        'Frequency of temperature Perlin noise.',
        'src/engine/forceField.ts', [0.01, 0.15],
        'forceField → temperature noise'),
      n('TEMP_OCTAVES', forceField.TEMP_OCTAVES,
        'Octaves for temperature noise.',
        'src/engine/forceField.ts', [1, 6],
        'forceField → temperature noise'),
      n('TEMP_PERSISTENCE', forceField.TEMP_PERSISTENCE,
        'Amplitude decay per octave for temperature.',
        'src/engine/forceField.ts', [0.1, 0.9],
        'forceField → temperature noise'),
      n('TEMP_LACUNARITY', forceField.TEMP_LACUNARITY,
        'Frequency increase per octave for temperature.',
        'src/engine/forceField.ts', [1.0, 4.0],
        'forceField → temperature noise'),
      n('MOISTURE_NOISE_SCALE', forceField.MOISTURE_NOISE_SCALE,
        'Frequency of moisture Perlin noise.',
        'src/engine/forceField.ts', [0.01, 0.2],
        'forceField → moisture noise'),
      n('MOISTURE_OCTAVES', forceField.MOISTURE_OCTAVES,
        'Octaves for moisture noise.',
        'src/engine/forceField.ts', [1, 6],
        'forceField → moisture noise'),
      n('MOISTURE_PERSISTENCE', forceField.MOISTURE_PERSISTENCE,
        'Amplitude decay per octave for moisture.',
        'src/engine/forceField.ts', [0.1, 0.9],
        'forceField → moisture noise'),
      n('MOISTURE_LACUNARITY', forceField.MOISTURE_LACUNARITY,
        'Frequency increase per octave for moisture.',
        'src/engine/forceField.ts', [1.0, 4.0],
        'forceField → moisture noise'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 13b. BIOME CLASSIFICATION — Elevation & Climate Bands
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'biome-classification',
    label: 'Biome Classification — Elevation Bands',
    description: 'Elevation thresholds that determine terrain type: lowland, hills, mountains, high mountains. Also temperature and moisture band boundaries.',
    constants: [
      n('ELEV_DEEP_OCEAN', terrain.ELEV.DEEP_OCEAN,
        'Elevation below which hexes are deep ocean.',
        'src/engine/terrain.ts', [0.05, 0.25],
        'classifyBiome → ocean depth'),
      n('ELEV_SHALLOWS', terrain.ELEV.SHALLOWS,
        'Elevation below which hexes are coastal shallows.',
        'src/engine/terrain.ts', [0.15, 0.35],
        'classifyBiome → ocean depth'),
      n('ELEV_LAKE_MAX', terrain.ELEV.LAKE_MAX,
        'Maximum elevation for lake formation.',
        'src/engine/terrain.ts', [0.20, 0.40],
        'classifyBiome → lake placement'),
      n('ELEV_LOWLAND', terrain.ELEV.LOWLAND,
        'Elevation ceiling for lowland biomes (grassland, forest, etc.).',
        'src/engine/terrain.ts', [0.35, 0.60],
        'classifyBiome → lowland/mid transition'),
      n('ELEV_MID', terrain.ELEV.MID,
        'Elevation ceiling for mid-elevation biomes (hills transition zone).',
        'src/engine/terrain.ts', [0.50, 0.75],
        'classifyBiome → hills/highland transition'),
      n('ELEV_HIGHLAND', terrain.ELEV.HIGHLAND,
        'Elevation ceiling for highland biomes. Above this = mountains.',
        'src/engine/terrain.ts', [0.60, 0.90],
        'classifyBiome + pass07 → mountain override'),
      n('ELEV_HIGH_MOUNTAINS', terrain.ELEV.HIGH_MOUNTAINS,
        'Elevation threshold for high mountains. Above this = high_mountains/volcano.',
        'src/engine/terrain.ts', [0.85, 1.00],
        'pass07 → high mountain override'),
      n('SEA_LEVEL', wgConstants.SEA_LEVEL,
        'Elevation threshold dividing ocean from land.',
        'src/engine/worldgen/constants.ts', [0.25, 0.50],
        'pass02 → ocean mask'),
      n('RIDGE_PEAK_ELEVATION', wgConstants.RIDGE_PEAK_ELEVATION,
        'Peak elevation at ridge spine hexes.',
        'src/engine/worldgen/constants.ts', [0.70, 1.00],
        'pass02 → ridge overlay'),
      n('RIDGE_FOOTHILLS_HEXES', wgConstants.RIDGE_FOOTHILLS_HEXES,
        'Hexes from ridge spine to foothills edge.',
        'src/engine/worldgen/constants.ts', [2, 8],
        'pass02 → ridge falloff'),
      n('VOLCANO_MIN_ELEVATION', wgConstants.VOLCANO_MIN_ELEVATION,
        'Minimum elevation for volcano placement.',
        'src/engine/worldgen/constants.ts', [0.80, 1.00],
        'pass07 → volcano check'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 14. VIGNETTES & PROSE
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'vignettes',
    label: 'Vignettes & Prose',
    description: 'Notification gating, significance thresholds, and prose generation limits.',
    constants: [
      n('VIGNETTE_MAX_PER_TICK', abc.VIGNETTE_MAX_PER_TICK,
        'Max Tier 1 notifications per tick. Prevents notification spam.',
        'src/data/agent-behavior-constants.ts', [1, 5],
        'vignetteNotification → per-tick cap'),
      n('VIGNETTE_QUEST_PRIORITY_THRESHOLD', abc.VIGNETTE_QUEST_PRIORITY_THRESHOLD,
        'Minimum questPriority for Tier 1 vignette classification.',
        'src/data/agent-behavior-constants.ts', [1.0, 3.0],
        'vignetteNotification → tier classification'),
      n('VIGNETTE_SCENE_MAX_SENTENCES', vignetteProse.VIGNETTE_SCENE_MAX_SENTENCES,
        'Max sentences in a vignette scene description.',
        'src/engine/vignetteProse.ts', [1, 8],
        'vignetteProse → scene length'),
      n('VIGNETTE_STAKES_MAX_SENTENCES', vignetteProse.VIGNETTE_STAKES_MAX_SENTENCES,
        'Max sentences in a vignette stakes description.',
        'src/engine/vignetteProse.ts', [1, 5],
        'vignetteProse → stakes length'),
      n('VIGNETTE_LENS_VARIANTS_PER_SPHERE', vignetteProse.VIGNETTE_LENS_VARIANTS_PER_SPHERE,
        'Number of prose variants per sphere for lens descriptions.',
        'src/engine/vignetteProse.ts', [1, 8],
        'vignetteProse → lens variety'),
      n('VIGNETTE_FORECAST_VARIANTS', vignetteProse.VIGNETTE_FORECAST_VARIANTS,
        'Number of forecast prose variants.',
        'src/engine/vignetteProse.ts', [1, 8],
        'vignetteProse → forecast variety'),
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════
  // 15. VISUAL & RENDERING
  // ═══════════════════════════════════════════════════════════════════════
  {
    id: 'visual',
    label: 'Visual & Rendering',
    description: 'Agent token rendering, zoom thresholds, and map display constants.',
    constants: [
      n('ZOOM_TOKEN_THRESHOLD', agentVisual.ZOOM_TOKEN_THRESHOLD,
        'Zoom level above which agent tokens are shown (below = dots only).',
        'src/data/agent-visual-content.ts', [0.1, 2.0],
        'AgentDots → zoom check'),
      n('MAX_RING_AGENTS', agentVisual.MAX_RING_AGENTS,
        'Max agents displayed in the location ring before overflow.',
        'src/data/agent-visual-content.ts', [3, 20],
        'AgentDots → ring layout'),
      n('AGENT_DOT_RADIUS', agentVisual.AGENT_DOT_RADIUS,
        'Radius of agent dot at low zoom.',
        'src/data/agent-visual-content.ts', [1, 10],
        'AgentDots → dot rendering'),
      n('AGENT_TOKEN_RADIUS', agentVisual.AGENT_TOKEN_RADIUS,
        'Radius of agent token at high zoom.',
        'src/data/agent-visual-content.ts', [3, 20],
        'AgentDots → token rendering'),
      n('AGENT_RING_RADIUS', agentVisual.AGENT_RING_RADIUS,
        'Radius of the ring agents are placed on around a location.',
        'src/data/agent-visual-content.ts', [5, 30],
        'AgentDots → ring layout'),
    ],
  },
];

/** Total count of all tunable constants across all groups */
export function getTunableConstantCount(): number {
  return TUNABLE_GROUPS.reduce((sum, g) => sum + g.constants.length, 0);
}
