/**
 * Content Census (THR-473 P1).
 *
 * Measures content coverage across the reach × scale matrix per content type.
 * Flags deserts, empty cells, and untagged entries. Read-only, deterministic.
 *
 * Outputs:
 *   Docs/playtests/coverage/YYYY-MM-DD-content-census.md
 *   Docs/playtests/coverage/YYYY-MM-DD-content-census.json
 *
 * Usage:
 *   npm run content-census
 *   npm run content-census -- --json   # raw JSON to stdout
 *   npm run content-census -- --out-dir <path>
 */

import * as fs from 'fs';
import * as path from 'path';
import { resolveAll } from '../src/engine/contentCensus/adapters';
import { buildReport, buildResolvabilityReport } from '../src/engine/contentCensus/matrix';
import {
  CENSUS_REACH_DOMAINS,
  CENSUS_SCALE_DOMAINS,
  CONTENT_CELL_MIN,
  DESERT_PRIORITY_MODE,
  SCALE_APPLICABILITY,
} from '../src/engine/contentCensus/constants';
import type { CensusReport, ContentType } from '../src/engine/contentCensus/types';
import type { ResolvabilityRow } from '../src/engine/contentCensus/matrix';
import type { ActionScale } from '../src/types/unifiedAction';
import type { ReachDomain } from '../src/types/traits';

// ─── Args ─────────────────────────────────────────────────────────

interface Args {
  outDir: string;
  jsonOnly: boolean;
}

function parseArgs(): Args {
  const argv = process.argv.slice(2);
  let outDir = 'Docs/playtests/coverage';
  let jsonOnly = false;
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--out-dir' && i + 1 < argv.length) outDir = argv[++i];
    else if (a === '--json') jsonOnly = true;
  }
  return { outDir, jsonOnly };
}

// ─── ANSI helpers ─────────────────────────────────────────────────

const GREEN = '\x1b[32m';
const YELLOW = '\x1b[33m';
const RED = '\x1b[31m';
const DIM = '\x1b[2m';
const BOLD = '\x1b[1m';
const RESET = '\x1b[0m';

function pct(n: number): string {
  return `${(n * 100).toFixed(1)}%`;
}

// ─── Markdown rendering ──────────────────────────────────────────

function statusIcon(status: string): string {
  if (status === 'filled') return '■';
  if (status === 'desert') return '▪';
  if (status === 'empty') return '·';
  return ' ';
}

function renderHeatmapMd(report: CensusReport, contentType: ContentType): string {
  const matrix = report.matrices.find(m => m.contentType === contentType);
  if (!matrix) return '';

  const scales = CENSUS_SCALE_DOMAINS;
  const header = ['reach', ...scales.map(s => s.padEnd(8))].join(' | ');
  const separator = ['------', ...scales.map(() => '--------')].join(' | ');

  const rows = CENSUS_REACH_DOMAINS.map(reach => {
    const cells = scales.map(scale => {
      const cell = matrix.cells.find(c => c.reach === reach && c.scale === scale);
      if (!cell || cell.status === 'na') return 'N/A     ';
      const icon = statusIcon(cell.status);
      return `${icon}${cell.count}`.padEnd(8);
    });
    return [reach.padEnd(6), ...cells].join(' | ');
  });

  return [`| ${header} |`, `| ${separator} |`, ...rows.map(r => `| ${r} |`)].join('\n');
}

function renderMarkdown(
  report: CensusReport,
  resolvability: ResolvabilityRow[],
  dateStr: string,
): string {
  const lines: string[] = [];

  lines.push(`# Content Census — ${dateStr}`);
  lines.push('');
  lines.push(`Generated by \`npm run content-census\` (THR-473 P1).  `);
  lines.push(`Cell threshold: filled ≥ ${CONTENT_CELL_MIN} entries; desert 1–${CONTENT_CELL_MIN - 1}; empty 0.  `);
  lines.push(`Desert priority mode: **${DESERT_PRIORITY_MODE}**.`);
  lines.push('');
  lines.push('Legend: `■` filled &nbsp; `▪` desert &nbsp; `·` empty &nbsp; `N/A` not applicable for this type');
  lines.push('');

  // ── 1. Resolvability Report ──────────────────────────────────────
  lines.push('## 1. Resolvability Report');
  lines.push('');
  lines.push('Per registry: % of entries with resolvable reach/scale. Entries needing schema backfill before they appear in the heatmap.');
  lines.push('');
  lines.push('| type | total | reach% | scale% | both% | needs backfill |');
  lines.push('|------|-------|--------|--------|-------|----------------|');
  for (const row of resolvability) {
    const backfill = row.total - row.bothResolved;
    lines.push(
      `| ${row.contentType} | ${row.total} | ${pct(row.reachPct)} | ${pct(row.scalePct)} | ${pct(row.bothPct)} | ${backfill} |`
    );
  }
  lines.push('');

  // ── 2. Summary ────────────────────────────────────────────────────
  lines.push('## 2. Summary');
  lines.push('');
  lines.push('| type | entries | applicable cells | filled | desert | empty | untagged | fill% |');
  lines.push('|------|---------|-----------------|--------|--------|-------|----------|-------|');
  for (const s of report.summary) {
    lines.push(
      `| ${s.contentType} | ${s.totalEntries} | ${s.applicableCells} | ${s.filledCells} | ${s.desertCells} | ${s.emptyCells} | ${s.untaggedCount} | ${pct(s.fillPct)} |`
    );
  }
  lines.push('');

  // ── 3. Per-type heatmaps ──────────────────────────────────────────
  lines.push('## 3. Per-type Heatmaps (reach × scale)');
  lines.push('');
  for (const contentType of ['encounters', 'actions'] as ContentType[]) {
    const matrix = report.matrices.find(m => m.contentType === contentType);
    if (!matrix || matrix.totalEntries === 0) continue;
    lines.push(`### ${contentType}`);
    lines.push('');
    lines.push(renderHeatmapMd(report, contentType));
    lines.push('');
  }
  lines.push('*Other content types have no resolved (reach, scale) entries — see Resolvability Report.*');
  lines.push('');

  // ── 4. Desert list ────────────────────────────────────────────────
  lines.push('## 4. Desert List (1–' + (CONTENT_CELL_MIN - 1) + ' entries)');
  lines.push('');
  if (report.desertList.length === 0) {
    lines.push('*No deserts.*');
  } else {
    lines.push('| type | reach | scale | count | priority |');
    lines.push('|------|-------|-------|-------|----------|');
    for (const d of report.desertList) {
      lines.push(`| ${d.contentType} | ${d.reach} | ${d.scale} | ${d.count} | ${d.priorityScore} |`);
    }
  }
  lines.push('');

  // ── 5. Empty list ─────────────────────────────────────────────────
  lines.push('## 5. Empty List (0 entries, highest-priority deserts)');
  lines.push('');
  if (report.emptyList.length === 0) {
    lines.push('*No empty applicable cells.*');
  } else {
    lines.push('| type | reach | scale | priority |');
    lines.push('|------|-------|-------|----------|');
    for (const e of report.emptyList.slice(0, 100)) {
      lines.push(`| ${e.contentType} | ${e.reach} | ${e.scale} | ${e.priorityScore} |`);
    }
    if (report.emptyList.length > 100) {
      lines.push(`| ... | | | | *(${report.emptyList.length - 100} more — see JSON output)* |`);
    }
  }
  lines.push('');

  // ── 6. Untagged list ─────────────────────────────────────────────
  lines.push('## 6. Untagged List (re-tag worklist)');
  lines.push('');
  lines.push('Entries missing reach and/or scale — must be tagged before appearing in the heatmap.');
  lines.push('');
  for (const group of report.untaggedList) {
    lines.push(`### ${group.contentType} (${group.entries.length} entries)`);
    lines.push('');
    const applicableScales = SCALE_APPLICABILITY[group.contentType] ?? [];
    lines.push(`*Applicable scales: ${applicableScales.join(', ') || 'none defined'}*`);
    lines.push('');
    for (const e of group.entries.slice(0, 50)) {
      lines.push(`- \`${e.id}\` — ${e.reason}`);
    }
    if (group.entries.length > 50) {
      lines.push(`- *(${group.entries.length - 50} more — see JSON output)*`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

// ─── Console output ───────────────────────────────────────────────

function printReport(report: CensusReport, resolvability: ResolvabilityRow[]): void {
  console.log(`\n${BOLD}Content Census${RESET}  (${report.date})`);
  console.log(`  Cell threshold: filled ≥ ${CONTENT_CELL_MIN}  |  mode: ${DESERT_PRIORITY_MODE}`);

  console.log(`\n${BOLD}Resolvability${RESET}`);
  for (const row of resolvability) {
    const backfill = row.total - row.bothResolved;
    const color = row.bothPct === 1 ? GREEN : row.bothPct > 0 ? YELLOW : RED;
    console.log(
      `  ${row.contentType.padEnd(12)} total:${String(row.total).padStart(4)}  both:${color}${pct(row.bothPct)}${RESET}  ${DIM}(${backfill} need backfill)${RESET}`
    );
  }

  console.log(`\n${BOLD}Summary${RESET}`);
  for (const s of report.summary) {
    const color = s.filledCells === s.applicableCells && s.applicableCells > 0 ? GREEN
      : s.desertCells > 0 ? YELLOW : DIM;
    console.log(
      `  ${s.contentType.padEnd(12)} entries:${String(s.totalEntries).padStart(4)}  fill:${color}${pct(s.fillPct)}${RESET}  ` +
      `desert:${s.desertCells}  empty:${s.emptyCells}  untagged:${s.untaggedCount}`
    );
  }

  console.log(`\n${BOLD}Desert cells${RESET} (${report.desertList.length})`);
  for (const d of report.desertList.slice(0, 20)) {
    console.log(`  ${d.contentType.padEnd(12)} ${d.reach.padEnd(7)} ${d.scale.padEnd(8)} count:${d.count}`);
  }
  if (report.desertList.length > 20) {
    console.log(`  ${DIM}... ${report.desertList.length - 20} more (see output files)${RESET}`);
  }

  console.log(`\n${BOLD}Empty cells${RESET} (${report.emptyList.length})`);
  for (const e of report.emptyList.slice(0, 10)) {
    console.log(`  ${e.contentType.padEnd(12)} ${e.reach.padEnd(7)} ${e.scale}`);
  }
  if (report.emptyList.length > 10) {
    console.log(`  ${DIM}... ${report.emptyList.length - 10} more (see output files)${RESET}`);
  }
}

// ─── Main ─────────────────────────────────────────────────────────

function main(): void {
  const args = parseArgs();

  if (!args.jsonOnly) {
    process.stdout.write('  Loading registries... ');
  }
  const entries = resolveAll();
  if (!args.jsonOnly) {
    console.log(`${entries.length} entries`);
    process.stdout.write('  Building report... ');
  }

  const dateStr = new Date().toISOString().slice(0, 10);
  const report = buildReport(dateStr, entries);
  const resolvability = buildResolvabilityReport(entries);

  if (!args.jsonOnly) {
    console.log('done');
  }

  if (args.jsonOnly) {
    console.log(JSON.stringify({ date: dateStr, report, resolvability }, null, 2));
    return;
  }

  printReport(report, resolvability);

  // Write outputs
  if (!fs.existsSync(args.outDir)) fs.mkdirSync(args.outDir, { recursive: true });

  const mdFile = path.join(args.outDir, `${dateStr}-content-census.md`);
  const jsonFile = path.join(args.outDir, `${dateStr}-content-census.json`);

  fs.writeFileSync(mdFile, renderMarkdown(report, resolvability, dateStr), 'utf-8');
  fs.writeFileSync(jsonFile, JSON.stringify({ date: dateStr, report, resolvability }, null, 2), 'utf-8');

  console.log(`\n  Wrote: ${mdFile}`);
  console.log(`  Wrote: ${jsonFile}`);
}

main();
