/**
 * Encounter Volume Model (THR-475).
 *
 * Pure-arithmetic script — no engine load, no PRNG.
 * Derives the library-size targets from named constants in encounterSurface.ts
 * so the ~1,000-surface target is a tunable output, not an asserted number.
 *
 * Usage:
 *   npm run volume-model
 *
 * Outputs dated md + json to Docs/playtests/coverage/.
 * Two runs on the same day produce byte-identical files.
 */

import * as fs from 'fs';
import * as path from 'path';

import {
  SURFACE_KEY_AXES,
  SURFACES_PER_RUN_TARGET,
  RELEVANT_FRACTION,
  RUNS_BEFORE_REPETITION,
} from '../src/engine/encounterSurface';
import { REACH_DOMAINS } from '../src/types/traits';

// ─── Constants used locally in the model ────────────────────────

const REACH_COUNT = REACH_DOMAINS.length;
const SUBLOCATION_TYPE_COUNT = 8; // Sublocation types in registry (estimate)
const SOCIAL_ROLE_COUNT = 6;     // NPC role enum cardinality (null + 5 roles)

// ─── Derived model ──────────────────────────────────────────────

function deriveModel() {
  const runPoolMinEligible = Math.ceil(SURFACES_PER_RUN_TARGET / RELEVANT_FRACTION);
  const totalLibraryTarget = runPoolMinEligible * RUNS_BEFORE_REPETITION;

  // Max theoretical cardinality: product of axis cardinalities × template count.
  // This is a ceiling; actual surfaces are bounded by authored template count.
  const axisCardinality: Record<string, number> = {
    reachPrimary: REACH_COUNT,
    sublocationTypeId: SUBLOCATION_TYPE_COUNT,
    socialRole: SOCIAL_ROLE_COUNT,
  };
  const axisCeilingProduct = SURFACE_KEY_AXES.reduce(
    (product, axis) => product * (axisCardinality[axis] ?? 1),
    1,
  );

  return {
    inputs: {
      SURFACES_PER_RUN_TARGET,
      RELEVANT_FRACTION,
      RUNS_BEFORE_REPETITION,
      SURFACE_KEY_AXES: [...SURFACE_KEY_AXES],
      axisCardinality,
    },
    derived: {
      runPoolMinEligible,
      totalLibraryTarget,
      axisCeilingProduct,
    },
    interpretation: {
      note: [
        `Run pool: need ≥${runPoolMinEligible} unique surfaces eligible per run to hit the ${SURFACES_PER_RUN_TARGET} target at ${RELEVANT_FRACTION * 100}% relevance.`,
        `Library target: ~${totalLibraryTarget} total surfaces for ${RUNS_BEFORE_REPETITION}-run replayability.`,
        `Axis ceiling: product of axis cardinalities = ${axisCeilingProduct} (ceiling before template count bounds it).`,
        `Phase 0 delivers the naming layer. Surface production (multiplication) begins Phase 1+.`,
      ],
    },
  };
}

// ─── Output ─────────────────────────────────────────────────────

function toDateStr(): string {
  const now = new Date();
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  return `${y}-${m}-${d}`;
}

function toMarkdown(model: ReturnType<typeof deriveModel>, date: string): string {
  const { inputs, derived, interpretation } = model;
  return [
    `# Encounter Volume Model — ${date}`,
    '',
    '## Inputs',
    '',
    `| Constant | Value |`,
    `|----------|-------|`,
    `| SURFACES_PER_RUN_TARGET | ${inputs.SURFACES_PER_RUN_TARGET} |`,
    `| RELEVANT_FRACTION | ${inputs.RELEVANT_FRACTION} |`,
    `| RUNS_BEFORE_REPETITION | ${inputs.RUNS_BEFORE_REPETITION} |`,
    `| SURFACE_KEY_AXES | ${inputs.SURFACE_KEY_AXES.join(', ')} |`,
    '',
    '## Axis cardinality',
    '',
    `| Axis | Cardinality |`,
    `|------|-------------|`,
    ...Object.entries(inputs.axisCardinality).map(([k, v]) => `| ${k} | ${v} |`),
    '',
    '## Derived targets',
    '',
    `| Metric | Value |`,
    `|--------|-------|`,
    `| Run pool min eligible | ${derived.runPoolMinEligible} |`,
    `| Total library target | ${derived.totalLibraryTarget} |`,
    `| Axis ceiling product | ${derived.axisCeilingProduct} |`,
    '',
    '## Interpretation',
    '',
    ...interpretation.note.map(n => `- ${n}`),
    '',
    '_Generated by `npm run volume-model`. Two runs on the same day produce byte-identical output._',
  ].join('\n');
}

function run() {
  const model = deriveModel();
  const date = toDateStr();
  const outDir = path.resolve('Docs/playtests/coverage');

  fs.mkdirSync(outDir, { recursive: true });

  const mdPath = path.join(outDir, `${date}-encounter-volume-model.md`);
  const jsonPath = path.join(outDir, `${date}-encounter-volume-model.json`);

  fs.writeFileSync(mdPath, toMarkdown(model, date), 'utf8');
  fs.writeFileSync(jsonPath, JSON.stringify({ date, ...model }, null, 2) + '\n', 'utf8');

  console.log(`Volume model written:`);
  console.log(`  ${mdPath}`);
  console.log(`  ${jsonPath}`);
  console.log('');
  console.log('Summary:');
  console.log(`  Run pool min eligible : ${model.derived.runPoolMinEligible}`);
  console.log(`  Total library target  : ${model.derived.totalLibraryTarget}`);
  console.log(`  Axis ceiling product  : ${model.derived.axisCeilingProduct}`);
}

run();
