/**
 * generate-kind-row-catalog — the kind × CRUD grid as data (THR-1300 slice 1).
 *
 * Writes `.claude/skills/undertaking-pipeline/reference/kind-row-catalog.generated.md`
 * from `UNDERTAKING_KIND_ROWS` and the template registry, so a batch brief can be
 * gap-weighted against the grid that actually exists rather than the one the
 * author remembers. The encounter line's `anchor-catalog.generated.md` is the
 * sibling; like it, this file is a committed artifact under
 * `check:generated-freshness` (out-of-prebuild list) — a stale grid is a brief
 * aimed at a cell that was filled last week.
 *
 *   npm run generate-kind-row-catalog            # write
 *   npm run generate-kind-row-catalog -- --check # exit 1 if the committed copy differs
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { getAllUndertakingKindRows } from '../src/data/undertaking-kinds';
import { getAllStrategicTemplates } from '../src/engine/strategicActionCandidates';

export const KIND_ROW_CATALOG_PATH = '.claude/skills/undertaking-pipeline/reference/kind-row-catalog.generated.md';

export function renderKindRowCatalog(): string {
  const rows = getAllUndertakingKindRows();
  const templates = new Map(getAllStrategicTemplates().map(t => [t.id, t]));
  const inRows = new Set(rows.flatMap(r => [...r.createTemplateIds, ...r.updateTemplateIds, ...r.destroyTemplateIds]));
  const rowless = [...templates.values()].filter(t => !inRows.has(t.id)).sort((a, b) => a.id.localeCompare(b.id));
  const cell = (ids: readonly string[]) => ids.length
    ? ids.map(id => templates.has(id) ? `\`${id}\`` : `~~\`${id}\`~~ (unresolved)`).join('<br>')
    : '**— empty —**';
  const lines: string[] = [];
  lines.push('# Kind-row catalog — the kind × CRUD grid');
  lines.push('');
  lines.push('> Generated by `npm run generate-kind-row-catalog` from `src/data/undertaking-kinds.ts` and the template registry. Do not edit; a batch brief is gap-weighted against **this** grid. Empty cells are the brief\'s first targets; a D column that is empty is a kind that is not a kind (THR-1297).');
  lines.push('');
  lines.push(`Rows: ${rows.length} · templates in rows: ${inRows.size} · row-less templates: ${rowless.length}`);
  lines.push('');
  lines.push('| kind | tier | ownable | lexicon | C (create) | U (update) | D (destroy) | object |');
  lines.push('|---|---|---|---|---|---|---|---|');
  for (const r of rows) {
    lines.push(`| \`${r.kindId}\` — ${r.displayName} | ${r.tier} | ${r.ownable ? 'yes' : 'no'} | \`${r.lexicon}\` | ${cell(r.createTemplateIds)} | ${cell(r.updateTemplateIds)} | ${cell(r.destroyTemplateIds)} | ${r.objectShape} |`);
  }
  lines.push('');
  lines.push('## Kinds with builds and no row');
  lines.push('');
  lines.push('`sublocation` (T2) and `faction` (T3): their create verbs ship, their destroys do not, so no row is registered — registering one against an ambient process would be presence of counter-play rather than counter-play. These are the two cells every pilot brief weights first.');
  lines.push('');
  lines.push('## Row-less templates');
  lines.push('');
  lines.push('Templates the registry does not place. `multi_tick_project` ones fail the contract\'s kind-membership block (on the ratchet until placed); `instant` and `claim_control` ones may stay row-less with a `mutationHint`.');
  lines.push('');
  lines.push('| template | verb | mode | family |');
  lines.push('|---|---|---|---|');
  for (const t of rowless) lines.push(`| \`${t.id}\` | ${t.verb} | ${t.executionMode} | ${t.behaviorFamily} |`);
  lines.push('');
  return lines.join('\n');
}

const isMain = process.argv[1]?.replace(/\\/g, '/').endsWith('generate-kind-row-catalog.mjs')
  || process.argv[1]?.replace(/\\/g, '/').endsWith('generate-kind-row-catalog.ts');
if (isMain) {
  const rendered = renderKindRowCatalog();
  if (process.argv.includes('--check')) {
    const current = existsSync(KIND_ROW_CATALOG_PATH) ? readFileSync(KIND_ROW_CATALOG_PATH, 'utf8') : '';
    if (current !== rendered) {
      console.error(`[generate-kind-row-catalog] ${KIND_ROW_CATALOG_PATH} is stale — run npm run generate-kind-row-catalog`);
      process.exit(1);
    }
    console.log(`[generate-kind-row-catalog] ${KIND_ROW_CATALOG_PATH} is current.`);
  } else {
    writeFileSync(KIND_ROW_CATALOG_PATH, rendered);
    console.log(`[generate-kind-row-catalog] wrote ${KIND_ROW_CATALOG_PATH}`);
  }
}
