#!/usr/bin/env node

/**
 * generate-design-wiki — keeps the Design Reference Wiki self-connected.
 *
 * Single source of truth: public/wiki-manifest.json.
 * On run:
 *   (a) regenerates public/design-wiki.html (the hub) from the manifest, and
 *   (b) re-injects a managed nav into every manifest page, replacing the content
 *       between <!--WIKI-NAV--> / <!--/WIKI-NAV--> markers (or inserting the block
 *       immediately after <body> when markers are absent). Idempotent.
 *
 * Wired into `npm run build` via prebuild, so a page regenerated by another skill
 * gets its nav (and the hub) restored on the next build.
 *
 * Pattern doc: Docs/design-reference-wiki.md. Sibling generators:
 * generate-ul-dashboard-data.ts, generate-impediment-dashboard.ts.
 */

import fs from "node:fs";
import path from "node:path";

import {
  type Manifest,
  type ManifestPage,
  type BacklogEntry,
  REPO_ROOT,
  PUBLIC_DIR,
  MANIFEST_PATH,
  NAV_START,
  NAV_END,
  escapeHtml,
  readManifest,
  buildNav,
} from "./design-wiki-nav.ts";

const DRY_RUN = process.argv.includes("--dry-run");

function replaceBetweenMarkers(source: string, replacement: string): string | null {
  const startIndex = source.indexOf(NAV_START);
  const endIndex = source.indexOf(NAV_END);
  if (startIndex === -1 || endIndex === -1 || endIndex < startIndex) return null;
  return `${source.slice(0, startIndex)}${replacement}${source.slice(endIndex + NAV_END.length)}`;
}

function insertAfterBody(source: string, block: string): string | null {
  const match = source.match(/<body[^>]*>/i);
  if (!match || match.index === undefined) return null;
  const insertAt = match.index + match[0].length;
  return `${source.slice(0, insertAt)}\n${block}${source.slice(insertAt)}`;
}

/** Re-inject the managed nav into one page. Returns a status string for logging. */
function injectNav(manifest: Manifest, page: ManifestPage): string {
  const filePath = path.join(PUBLIC_DIR, page.file);
  if (!fs.existsSync(filePath)) {
    return `skip ${page.file} — file not found (fail-soft)`;
  }

  const source = fs.readFileSync(filePath, "utf8");
  const nav = buildNav(manifest, page.id);

  let updated = replaceBetweenMarkers(source, nav);
  let mode = "replaced markers";
  if (updated === null) {
    updated = insertAfterBody(source, nav);
    mode = "inserted after <body>";
  }
  if (updated === null) {
    return `skip ${page.file} — no markers and no <body> tag (fail-soft)`;
  }

  if (updated === source) {
    return `unchanged ${page.file}`;
  }
  if (!DRY_RUN) fs.writeFileSync(filePath, updated, "utf8");
  return `${mode} → ${page.file}`;
}

function groupBySection<T extends { section: string }>(items: T[]): Map<string, T[]> {
  const map = new Map<string, T[]>();
  for (const item of items) {
    const key = item.section || "Other";
    const bucket = map.get(key) ?? [];
    bucket.push(item);
    map.set(key, bucket);
  }
  return map;
}

function buildHub(manifest: Manifest): string {
  const nav = buildNav(manifest, "__home__");
  const pagesBySection = groupBySection(manifest.pages);

  const pageSections = [...pagesBySection.entries()]
    .map(([section, pages]) => {
      const cards = pages
        .map(
          (page) => `      <a class="wiki-card" href="${escapeHtml(page.file)}">
        <h3>${escapeHtml(page.title)}</h3>
        <p>${escapeHtml(page.blurb)}</p>
      </a>`,
        )
        .join("\n");
      return `    <section class="wiki-section">
      <h2>${escapeHtml(section)}</h2>
      <div class="wiki-grid">
${cards}
      </div>
    </section>`;
    })
    .join("\n");

  const backlog = manifest.backlog ?? [];
  const backlogSection =
    backlog.length === 0
      ? ""
      : `    <section class="wiki-section wiki-section--backlog">
      <h2>To document next</h2>
      <div class="wiki-grid">
${backlog
  .map(
    (entry) => `        <div class="wiki-card wiki-card--planned" aria-disabled="true">
          <h3>${escapeHtml(entry.title)}</h3>
          <p>${escapeHtml(entry.blurb)}</p>
          <span class="wiki-card__badge">planned</span>
        </div>`,
  )
  .join("\n")}
      </div>
    </section>`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>${escapeHtml(manifest.title)}</title>
<!-- GENERATED by scripts/generate-design-wiki.ts from public/wiki-manifest.json — do not edit by hand. -->
<style>
  @import url('https://fonts.googleapis.com/css2?family=Cinzel:wght@400;600;700&family=Crimson+Text:ital,wght@0,400;0,600;1,400&display=swap');
  :root {
    --parchment: #f4edd8;
    --parchment-dark: #e8dfc8;
    --ink: #2c1810;
    --ink-light: #5a3d2b;
    --ink-faint: #8a7060;
    --gold: #b8860b;
    --gold-light: #daa520;
  }
  * { box-sizing: border-box; }
  body { margin: 0; background: var(--parchment); color: var(--ink); font-family: 'Crimson Text', Georgia, serif; }
  .wiki-main { max-width: 1100px; margin: 0 auto; padding: 2.5rem 1.5rem 4rem; }
  .wiki-hero h1 { font-family: 'Cinzel', Georgia, serif; font-size: 2.4rem; color: var(--ink); margin: 0 0 0.4rem; letter-spacing: 0.02em; }
  .wiki-hero p { font-size: 1.1rem; color: var(--ink-light); margin: 0 0 2rem; max-width: 70ch; }
  .wiki-section { margin-bottom: 2.6rem; }
  .wiki-section h2 { font-family: 'Cinzel', Georgia, serif; font-size: 1.2rem; color: var(--gold); text-transform: uppercase; letter-spacing: 0.08em; border-bottom: 1px solid var(--parchment-dark); padding-bottom: 0.4rem; margin-bottom: 1.1rem; }
  .wiki-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(280px, 1fr)); gap: 1rem; }
  .wiki-card { display: block; background: #fff8e7; border: 1px solid var(--parchment-dark); border-left: 4px solid var(--gold); border-radius: 4px; padding: 1.1rem 1.2rem; text-decoration: none; color: inherit; transition: box-shadow 0.15s, transform 0.15s, border-color 0.15s; position: relative; }
  a.wiki-card:hover { box-shadow: 0 4px 14px rgba(44, 24, 16, 0.15); transform: translateY(-2px); border-left-color: var(--gold-light); }
  .wiki-card h3 { font-family: 'Cinzel', Georgia, serif; font-size: 1.05rem; margin: 0 0 0.4rem; color: var(--ink); }
  .wiki-card p { margin: 0; font-size: 0.95rem; line-height: 1.5; color: var(--ink-light); }
  .wiki-card--planned { opacity: 0.7; border-left-style: dashed; border-left-color: var(--ink-faint); background: #f0e9d4; cursor: default; }
  .wiki-card__badge { display: inline-block; margin-top: 0.6rem; font-family: 'Cinzel', Georgia, serif; font-size: 0.65rem; letter-spacing: 0.1em; text-transform: uppercase; color: var(--ink-faint); border: 1px solid var(--ink-faint); border-radius: 3px; padding: 0.1rem 0.4rem; }
  .wiki-foot { margin-top: 3rem; padding-top: 1.2rem; border-top: 1px solid var(--parchment-dark); font-size: 0.85rem; color: var(--ink-faint); }
</style>
</head>
<body>
${nav}
  <main class="wiki-main">
    <header class="wiki-hero">
      <h1>Design Reference Wiki</h1>
      <p>The browsable system-design pages for Threadbearer. This hub and the nav on every page are generated from <code>public/wiki-manifest.json</code> by <code>scripts/generate-design-wiki.ts</code> on every build.</p>
    </header>
${pageSections}
${backlogSection}
    <footer class="wiki-foot">
      Generated from <code>public/wiki-manifest.json</code>. To add a page: drop its HTML in <code>public/</code>, register it in the manifest, and run <code>npm run build</code>.
    </footer>
  </main>
</body>
</html>
`;
}

function main(): void {
  const manifest = readManifest();

  // (a) regenerate the hub
  const hubPath = path.join(PUBLIC_DIR, manifest.home);
  const hubHtml = buildHub(manifest);
  if (!DRY_RUN) fs.writeFileSync(hubPath, hubHtml, "utf8");
  console.log(`generate-design-wiki: ${DRY_RUN ? "[dry-run] would write" : "wrote"} ${path.relative(REPO_ROOT, hubPath)} (hub, ${manifest.pages.length} pages, ${(manifest.backlog ?? []).length} planned)`);

  // (b) re-inject nav into every manifest page
  for (const page of manifest.pages) {
    const status = injectNav(manifest, page);
    console.log(`generate-design-wiki: ${DRY_RUN ? "[dry-run] " : ""}${status}`);
  }
}

main();
