/**
 * Faction Action Encounter Templates — THR-29 Social Expansion C.
 *
 * Encounter templates generated by faction action executors. These inject into
 * the agent decision pipeline as encounter candidates for faction members
 * (quest_board, bounty_hunt, rivalry encounters) or faction leadership (conclave_debate).
 *
 * Quality bar: every encounter must make the player feel that institutions
 * have personalities — and those personalities collide with human lives.
 * Benchmark: "The Arcane Circle decided something. Kael Thornweaver is in the blast radius."
 *
 * Design doc: Docs/plans/2026-04-14-faction-agency-implementation.md
 * Quality gate: Docs/plans/2026-04-18-faction-agency-quality-gate.md
 */

import type { UnifiedActionTemplate } from '../types/unifiedAction';

// ─── Quest Board (Commission Quest) ─────────────────────────────────────────

export const FA_QUEST_BOARD_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.quest_board',
  name: 'Faction Quest Board',
  rarityTier: 1,
  intrinsicTier: 'shaping',
  reach: 'iron',
  crudType: 'read',
  scale: 'local',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['loyalty_ambition', 'mercy_ruthlessness'],
  narrativeTemplates: {
    initiation: 'takes a commission from the faction\'s notice board',
    success: 'the work is done; the faction\'s coffers and confidence grow slightly',
    failure: 'the commission goes unfinished — the notice yellows on the board',
  },
  steps: [
    {
      reach: 'eye',
      duration: { min: 1, max: 2 },
      difficulty: 0.25,
      failBehavior: 'continue_weakened',
      onSuccess: [],
      onFailure: [],
      narrativeTemplate:
        'The notice board at {location} has a new posting — faction work, not guild rumor. ' +
        '{name} reads it twice. The task is specific and the reward is fair. ' +
        '{?has_faction_membership}The seal at the bottom is one {name} recognize{s}. ' +
        'It carries weight.{/has_faction_membership}' +
        '{?no_faction_membership}The posting is for members only. {name} is not ' +
        'a member — but the door to the guildhall is open, and inside someone ' +
        'could be convinced.{/no_faction_membership}',
      successAfterimage: 'The commission is taken. Someone is counting on this.',
      failureAfterimage: 'The notice goes unclaimed. The board fills with other work.',
    },
    {
      reach: 'iron',
      duration: { min: 3, max: 5 },
      difficulty: 0.40,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.40, possession: 0.40, bestowed_power: 0.20 },
        },
        tierPromotionEligible: true,
        reputationDelta: 0.04,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 0.80, possession: 0.20 } },
      },
      narrativeTemplate:
        'The commission is harder than the posting made it sound — they always are. ' +
        '{name} works through it at {location}: the specific thing the faction needed done, ' +
        'the obstacle that wasn\'t listed, the moment where the job became real rather than theoretical. ' +
        '{?has_ally}Having {ally} nearby makes the difference. Two people working the same ' +
        'problem from different angles.{/has_ally}' +
        '{?has_artifact}{artifact:any} earns its place on this job.{/has_artifact}',
      successAfterimage: 'Done. The faction will notice the work was good.',
      failureAfterimage: 'The job outgrew the person. It happens. The faction will not forget.',
    },
  ],
};

// ─── Rivalry Confrontation (Declare Rivalry aftermath) ────────────────────────

export const FA_RIVALRY_CONFRONTATION_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.rivalry_confrontation',
  name: 'Rival Faction Confrontation',
  rarityTier: 2,
  intrinsicTier: 'shaping',
  reach: 'iron',
  crudType: 'update',
  scale: 'local',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['mercy_ruthlessness', 'courage_prudence'],
  narrativeTemplates: {
    initiation: 'encounters a member of a rival faction at close quarters',
    success: 'stands their ground; the rival faction loses a small advantage',
    failure: 'the confrontation ends badly — the rival faction has demonstrated its reach',
  },
  steps: [
    {
      reach: 'eye',
      duration: { min: 1, max: 1 },
      difficulty: 0.20,
      failBehavior: 'continue_weakened',
      onSuccess: [],
      onFailure: [],
      narrativeTemplate:
        'At {location}, {name} recognize{s} the other person a moment before the other person ' +
        'recognizes {them}. The faction emblem is subtle — a pin, a colored scarf, the particular ' +
        'way they stand near the door — but {name} has been watching for this. ' +
        'The rivalry is new. No one has been given instructions on what to do when they meet.',
      successAfterimage: 'Recognized and ready. {name} has the first advantage.',
      failureAfterimage: 'Recognized first. The situation is already tilted.',
    },
    {
      reach: 'iron',
      duration: { min: 2, max: 3 },
      difficulty: 0.45,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.50, possession: 0.30, bestowed_power: 0.20 },
        },
        tierPromotionEligible: false,
        reputationDelta: 0.03,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 0.90, possession: 0.10 } },
      },
      narrativeTemplate:
        'The confrontation at {location} is not quite a fight. It is the moment before a fight — ' +
        'the inventory of what each person is willing to do and what they are not. ' +
        '{name} makes {their} position clear in the way {name} finds clearest: ' +
        '{?iron_dominant}through the language of physical consequence, through the weight ' +
        'of standing your ground when the other person wants you to move.{/iron_dominant}' +
        '{?shadow_dominant}through what {name} knows about them, through what {name} ' +
        'implies rather than states.{/shadow_dominant}' +
        '{?other_dominant}through words, through reputation, through the simple fact ' +
        'of refusing to be moved.{/other_dominant}' +
        'The rival backs down — or {name} does. Either way, the rivalry is no longer theoretical.',
      successAfterimage: 'The rival faction understands the terrain has changed.',
      failureAfterimage: 'The rival faction has demonstrated what a rivalry costs.',
    },
  ],
};

// ─── Loyalty Test (Excommunication precursor) ────────────────────────────────

export const FA_LOYALTY_TEST_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.loyalty_test',
  name: 'Loyalty Examination',
  rarityTier: 2,
  intrinsicTier: 'shaping',
  reach: 'heart',
  crudType: 'read',
  scale: 'local',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['loyalty_ambition', 'revelation_discretion'],
  narrativeTemplates: {
    initiation: 'is called before the faction to answer for their loyalties',
    success: 'answers the faction\'s questions with enough conviction to stay',
    failure: 'the faction is not satisfied — the relationship is now formal and cold',
  },
  steps: [
    {
      reach: 'heart',
      duration: { min: 2, max: 3 },
      difficulty: 0.50,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.60, possession: 0.40 },
        },
        tierPromotionEligible: false,
        reputationDelta: 0.02,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 1.0 } },
      },
      narrativeTemplate:
        'The room is too quiet when {name} walks in. The faction\'s senior members are arranged ' +
        'with the specific formality that means this matters. Someone has made tea. No one is drinking it. ' +
        'The questions come slowly: Where were you? Who did you speak to? What did you tell them? ' +
        '{name} answer{s}. Some answers are easy. Some require {them} to decide, in the middle of ' +
        'speaking, what the truth actually is. The faction is listening for the shape of the answers ' +
        'as much as the content — they are looking for the sound of a person who still belongs here. ' +
        '{?loyalty_high}The conviction in {their} voice is real. Even the suspicious ones can hear it.{/loyalty_high}' +
        '{?loyalty_low}{name}\'s answers are technically accurate. The faction notices ' +
        'they have stopped short of several things that would have been easy to say.{/loyalty_low}',
      successAfterimage: 'The faction is satisfied — this time. {name} is still here.',
      failureAfterimage: 'The door closes behind {name} with a particular finality.',
    },
  ],
};

// ─── Bounty Hunt ──────────────────────────────────────────────────────────────

export const FA_BOUNTY_HUNT_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.bounty_hunt',
  name: 'Faction Bounty',
  rarityTier: 2,
  intrinsicTier: 'story_beat',
  reach: 'shadow',
  crudType: 'delete',
  scale: 'regional',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['honesty_cunning', 'mercy_ruthlessness'],
  narrativeTemplates: {
    initiation: 'takes a bounty commission from the faction',
    success: 'the bounty is collected; someone pays a price they didn\'t know was coming',
    failure: 'the target escapes, the faction is out its coin, and someone now knows they\'re being hunted',
  },
  steps: [
    {
      reach: 'eye',
      duration: { min: 2, max: 3 },
      difficulty: 0.35,
      failBehavior: 'continue_weakened',
      onSuccess: [],
      onFailure: [],
      narrativeTemplate:
        '{name} begins where every hunt begins: with information. Who is the target? ' +
        'Where do they sleep? Who do they trust? The faction\'s posting was thin on detail — ' +
        'intentionally, probably. The things that actually matter are not on paper. ' +
        '{name} asks around at {location}, carefully, in the way that doesn\'t announce ' +
        'what the asking is for. This part of the work is patient and unglamorous and ' +
        'it is also the part where the job is won or lost.',
      successAfterimage: 'The target is located. The hunt is real now.',
      failureAfterimage: 'The trail is cold. Someone moved the target, or the target moved themselves.',
    },
    {
      reach: 'shadow',
      duration: { min: 3, max: 5 },
      difficulty: 0.55,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { possession: 0.50, condition: 0.30, bestowed_power: 0.20 },
        },
        tierPromotionEligible: true,
        reputationDelta: 0.05,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 0.80, possession: 0.20 } },
      },
      narrativeTemplate:
        'The moment comes at {location}: target in sight, the approach planned, ' +
        'the decision made. The thing about bounty work — the thing they don\'t say in ' +
        'the posting — is that it is not theoretical once you are looking at the person. ' +
        'They are doing something ordinary: reading, eating, talking to someone they trust. ' +
        'The faction\'s reasons for wanting them found are abstract. The person in front of ' +
        '{name} is not abstract.' +
        '{?has_ally}Having {ally} here changes the calculation. Another set of hands, ' +
        'another angle on the problem.{/has_ally}' +
        '{name} does what {name} came to do, or {name} does not.',
      successAfterimage: 'The bounty is collected. The faction\'s ledger balances. Someone\'s life doesn\'t.',
      failureAfterimage: 'The target got away. They know now. That makes everything harder.',
    },
  ],
};

// ─── Alliance Ceremony ────────────────────────────────────────────────────────

export const FA_ALLIANCE_CEREMONY_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.alliance_ceremony',
  name: 'Alliance Concordat',
  rarityTier: 2,
  intrinsicTier: 'shaping',
  reach: 'heart',
  crudType: 'create',
  scale: 'regional',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['mercy_ruthlessness', 'loyalty_ambition'],
  narrativeTemplates: {
    initiation: 'witnesses the factions\' alliance concordat',
    success: 'the alliance is formalized; new doors open for both sides',
    failure: 'the ceremony stalls on terms that seem minor and prove not to be',
  },
  steps: [
    {
      reach: 'heart',
      duration: { min: 2, max: 3 },
      difficulty: 0.30,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.60, bestowed_power: 0.40 },
        },
        tierPromotionEligible: false,
        reputationDelta: 0.03,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 0.80, possession: 0.20 } },
      },
      narrativeTemplate:
        'The ceremony at {location} is brief by design — both factions have learned ' +
        'not to trust lengthy ceremonies. Two leaders, a document, a room of people ' +
        'watching to see if the handshake looks real. ' +
        '{name} is here because someone with rank thought it mattered that {they} be here. ' +
        'That is its own kind of compliment. ' +
        'The concordat is signed. The room exhales. From this moment, what was separate is joined — ' +
        'not merged, not identical, but connected by a line of mutual interest that will take years ' +
        'to either strengthen or snap. ' +
        'The tea is poured. {name} stands with people from both factions in the same room for the ' +
        'first time, learning what it sounds like when their different vocabularies try to share a language.',
      successAfterimage: 'The alliance is real now. The work of making it matter begins.',
      failureAfterimage: 'The ceremony produced no concordat. The factions leave with what they brought.',
    },
  ],
};

// ─── Rivalry Subterfuge ───────────────────────────────────────────────────────

export const FA_RIVALRY_SUBTERFUGE_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.rivalry_subterfuge',
  name: 'Rival Espionage',
  rarityTier: 2,
  intrinsicTier: 'shaping',
  reach: 'shadow',
  crudType: 'read',
  scale: 'local',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['honesty_cunning', 'revelation_discretion'],
  narrativeTemplates: {
    initiation: 'infiltrates a rival faction\'s operations',
    success: 'extracts useful intelligence about the rival faction\'s plans',
    failure: 'the operation is compromised — the rival faction now knows someone was looking',
  },
  steps: [
    {
      reach: 'shadow',
      duration: { min: 2, max: 4 },
      difficulty: 0.50,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.40, possession: 0.40, bestowed_power: 0.20 },
          tagFilters: ['#shadow', '#eye'],
        },
        tierPromotionEligible: false,
        reputationDelta: 0.04,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 0.90, possession: 0.10 } },
      },
      narrativeTemplate:
        'The rival faction\'s operations at {location} are not secret exactly — they operate ' +
        'openly enough that secrecy isn\'t the protection. The protection is that no one is ' +
        'looking carefully enough. {name} is looking carefully. ' +
        '{?has_artifact}{artifact:shadow} makes this easier. ' +
        'The right tools for the right kind of looking.{/has_artifact}' +
        'The rival faction has a meeting schedule, a set of contacts, a pattern of where their ' +
        'members go and what they do when they get there. Learning that pattern is not dramatic. ' +
        'It is patient and methodical and it produces something useful when the patience holds.',
      successAfterimage: 'The intelligence is good. The rival faction is less opaque than it was.',
      failureAfterimage: 'The operation burned. The rival faction knows someone was inside.',
    },
  ],
};

// ─── Defection Pitch ──────────────────────────────────────────────────────────

export const FA_DEFECTION_PITCH_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.defection_pitch',
  name: 'Recruit from Rival',
  rarityTier: 2,
  intrinsicTier: 'shaping',
  reach: 'heart',
  crudType: 'update',
  scale: 'local',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['loyalty_ambition', 'honesty_cunning'],
  narrativeTemplates: {
    initiation: 'approaches a member of the rival faction with a proposition',
    success: 'plants doubt in a rival member\'s mind — or confirms their departure',
    failure: 'the pitch fails; the rival faction now knows they\'re being recruited against',
  },
  steps: [
    {
      reach: 'heart',
      duration: { min: 2, max: 3 },
      difficulty: 0.45,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.50, bestowed_power: 0.50 },
        },
        tierPromotionEligible: false,
        reputationDelta: 0.03,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 0.80, possession: 0.20 } },
      },
      narrativeTemplate:
        'At {location}, {name} finds the person they came to find and sits down across from them ' +
        'without preamble. The pitch is not about defection — no one says that word. ' +
        'It is about opportunity, about what the rival faction has stopped offering that used to matter, ' +
        'about what happens when loyalty becomes a habit rather than a choice. ' +
        'The person listens. They are here, which means they had enough curiosity to come. ' +
        'Whether they have enough dissatisfaction to act is something {name} cannot know until ' +
        'they speak, and then cannot be certain of even then. ' +
        'People are complicated about where they belong.',
      successAfterimage: 'The seed is planted. Whether it grows is not in {name}\'s hands anymore.',
      failureAfterimage: 'The pitch failed — and now the rival faction knows their member was approached.',
    },
  ],
};

// ─── Conclave Debate (group scene) ───────────────────────────────────────────

export const FA_CONCLAVE_DEBATE_TEMPLATE: UnifiedActionTemplate = {
  id: 'fa.conclave_debate',
  name: 'Faction Conclave',
  rarityTier: 3,
  intrinsicTier: 'story_beat',
  reach: 'heart',
  crudType: 'update',
  scale: 'regional',
  apCost: 1,
  actorAffinities: ['individual'],
  motivations: ['preservation_transformation', 'loyalty_ambition'],
  narrativeTemplates: {
    initiation: 'participates in a faction conclave',
    success: 'their voice shapes the conclave\'s direction',
    failure: 'the conclave reaches its conclusion without being moved by what {name} said',
  },
  steps: [
    {
      reach: 'eye',
      duration: { min: 1, max: 1 },
      difficulty: 0.25,
      failBehavior: 'continue_weakened',
      onSuccess: [],
      onFailure: [],
      narrativeTemplate:
        'The faction convenes in the inner room — not the hall they use for visitors, ' +
        'the room they use for themselves. The question has been posted: what does ' +
        'the faction do about the thing that has been gathering since the last meeting. ' +
        '{name} has read the question. {name} has been thinking about it, in the way ' +
        'you think about things that are also thinking about you. ' +
        'The others arrive one by one. Some are ready to speak. Some have come to listen. ' +
        'Some have come to count who else is in the room.',
      successAfterimage: '{name} understands the terrain before the debate begins.',
      failureAfterimage: '{name} reads the room wrong. The debate starts on uncertain ground.',
    },
    {
      reach: 'heart',
      duration: { min: 2, max: 2 },
      difficulty: 0.40,
      failBehavior: 'continue_weakened',
      onSuccess: [],
      onFailure: [],
      narrativeTemplate:
        'The debate is not a debate in any formal sense. It is a conversation where the ' +
        'stakes of the conversation are also part of what is being discussed. ' +
        'Senior voices speak first, because they always do. Then the ones who disagree speak, ' +
        'because disagreement that goes unvoiced becomes something worse. ' +
        '{name} listens to where the room is and makes a calculation: ' +
        'what {they} believe, what the room can hear, and what version of those two things ' +
        'is actually speakable in this moment without losing the thread of either.',
      successAfterimage: 'The room has heard {name}. The debate is moving somewhere.',
      failureAfterimage: 'The room has moved past what {name} said. It is still moving.',
    },
    {
      reach: 'heart',
      duration: { min: 1, max: 1 },
      difficulty: 0.35,
      failBehavior: 'fail_action',
      onSuccess: [],
      onFailure: [],
      successMetadata: {
        rewardPool: {
          categoryWeights: { condition: 0.50, bestowed_power: 0.50 },
        },
        tierPromotionEligible: true,
        reputationDelta: 0.06,
      },
      failureMetadata: {
        rewardPool: { categoryWeights: { condition: 1.0 } },
      },
      narrativeTemplate:
        'The vote is called. In this faction, votes are not always formal — sometimes the ' +
        'vote is whoever speaks last and most clearly when the room is tired of speaking. ' +
        '{name} makes {their} final statement, which is either the thing {they} have been ' +
        'building toward since the first step of this, or a recognition that the building ' +
        'has gone somewhere {name} did not intend. ' +
        'The faction decides. The conclave closes. What was open is now settled — ' +
        'for now, which is the only kind of settled that ever lasts.',
      successAfterimage: 'The faction\'s direction has shifted toward what {name} argued for.',
      failureAfterimage: 'The faction decided. {name}\'s voice was heard and not persuasive.',
    },
  ],
};

// ─── Registry ────────────────────────────────────────────────────────────────

export const FACTION_ACTION_ENCOUNTER_TEMPLATES: UnifiedActionTemplate[] = [
  FA_QUEST_BOARD_TEMPLATE,
  FA_RIVALRY_CONFRONTATION_TEMPLATE,
  FA_LOYALTY_TEST_TEMPLATE,
  FA_BOUNTY_HUNT_TEMPLATE,
  FA_ALLIANCE_CEREMONY_TEMPLATE,
  FA_RIVALRY_SUBTERFUGE_TEMPLATE,
  FA_DEFECTION_PITCH_TEMPLATE,
  FA_CONCLAVE_DEBATE_TEMPLATE,
];
