/**
 * IA manifest v1 — commitment document of what the player should see.
 *
 * Source of truth for interface-audit and playtest tooling.
 * Generated by transliterating Docs/ia-manifest.yaml for THR-206.
 */

export type SurfaceMount = 'always' | 'modal' | 'drillin';
export type SurfaceView = 'start' | 'ascendant' | 'game' | 'codex' | 'styleguide' | 'cms';

export interface IAReader {
  state_path: string;
  reader: string;
  visible_when: string;
}

export interface IASurface {
  surface: string;
  view: SurfaceView;
  mount: SurfaceMount;
  reads: IAReader[];
  optional_readers?: string[];
  notes?: string;
  openUrl?: string;
}

export const IA_SURFACES: IASurface[] = [
  {
    "surface": "start.page",
    "view": "start",
    "mount": "always",
    "reads": [
      {
        "state_path": "(none — pre-game state)",
        "reader": "StartPage",
        "visible_when": "view === 'start'"
      }
    ],
    "notes": "Landing view. Entry point for new game, continue, credits, settings.\n",
    "openUrl": "/"
  },
  {
    "surface": "start.credits-modal",
    "view": "start",
    "mount": "modal",
    "reads": [
      {
        "state_path": "(none)",
        "reader": "CreditsModal",
        "visible_when": "credits button clicked"
      }
    ],
    "notes": "Static credits content. No GameState dependency.\n"
  },
  {
    "surface": "start.settings-modal",
    "view": "start",
    "mount": "modal",
    "reads": [
      {
        "state_path": "(none — app-level settings)",
        "reader": "SettingsModal",
        "visible_when": "settings button clicked"
      }
    ],
    "notes": "Audio, display, debug toggles. App-level, not per-game.\n"
  },
  {
    "surface": "ascendant.selection",
    "view": "ascendant",
    "mount": "always",
    "reads": [
      {
        "state_path": "ascendantIdentity",
        "reader": "AscendantSelection",
        "visible_when": "ascendantIdentity === null"
      }
    ],
    "notes": "Archetype + identity selection for new game.\n",
    "openUrl": "/?view=ascendant"
  },
  {
    "surface": "ascendant.cosmology-panel",
    "view": "ascendant",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "cosmology.sphereWeights",
        "reader": "CosmologyPanel",
        "visible_when": "cosmology drill-in during selection"
      }
    ],
    "notes": "Shows sphere weighting and derived rivals.\n"
  },
  {
    "surface": "game.hex-map",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "graph",
        "reader": "HexMapV2",
        "visible_when": "always"
      },
      {
        "state_path": "tiles",
        "reader": "HexMapV2",
        "visible_when": "always"
      },
      {
        "state_path": "visibilityMap",
        "reader": "HexMapV2",
        "visible_when": "always"
      }
    ],
    "notes": "The core map. WebGL scene — assertions via __DEBUG.snapshotScene(), not pixels.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.essence-panel",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "essencePool",
        "reader": "EssencePanel",
        "visible_when": "always"
      }
    ],
    "notes": "Player's essence reserves across spheres. Must always be visible.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.simulation-controls",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "clock",
        "reader": "SimulationControls",
        "visible_when": "always"
      }
    ],
    "notes": "Pause/play/tick controls. Tick counter.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.doom-bar",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "doomClock",
        "reader": "DoomBar",
        "visible_when": "always"
      },
      {
        "state_path": "doomDefinition",
        "reader": "DoomBar",
        "visible_when": "always"
      }
    ],
    "notes": "Top-level doom progression indicator. Click expands to DoomClockDetail.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.doom-clock-detail",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "doomClock",
        "reader": "DoomClockDetail",
        "visible_when": "always"
      },
      {
        "state_path": "doomDefinition",
        "reader": "DoomClockDetail",
        "visible_when": "always"
      },
      {
        "state_path": "doomIdentityMatrix",
        "reader": "DoomClockDetail",
        "visible_when": "always"
      }
    ],
    "notes": "Expanded doom view with archetype details.\n"
  },
  {
    "surface": "game.omen-indicator",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "omenState",
        "reader": "OmenIndicator",
        "visible_when": "omenState !== undefined"
      },
      {
        "state_path": "tick",
        "reader": "OmenIndicator",
        "visible_when": "always"
      }
    ],
    "notes": "Atmospheric pressure indicator (THR-19). Click opens OmenDetail.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.omen-detail",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "omenState",
        "reader": "OmenDetail",
        "visible_when": "always"
      },
      {
        "state_path": "tick",
        "reader": "OmenDetail",
        "visible_when": "always"
      }
    ],
    "notes": "Detail modal for active omens.\n"
  },
  {
    "surface": "game.mandate-tracker",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "mandateState",
        "reader": "MandateTracker",
        "visible_when": "mandateState !== null"
      },
      {
        "state_path": "mandateDefinition",
        "reader": "MandateTracker",
        "visible_when": "always"
      }
    ],
    "notes": "Mandate progress at a glance. Click opens MandateDetail.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.mandate-detail",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "mandateState",
        "reader": "MandateDetail",
        "visible_when": "always"
      },
      {
        "state_path": "mandateDefinition",
        "reader": "MandateDetail",
        "visible_when": "always"
      }
    ],
    "notes": "Mandate stakes, progress, completion criteria.\n"
  },
  {
    "surface": "game.ascendant-bar",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "ascendantIdentity",
        "reader": "AscendantBar",
        "visible_when": "ascendantIdentity !== null"
      },
      {
        "state_path": "essencePool",
        "reader": "AscendantBar",
        "visible_when": "always"
      }
    ],
    "notes": "Player identity bar. Click opens AscendantSheet.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.ascendant-sheet",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "ascendantIdentity",
        "reader": "AscendantSheet",
        "visible_when": "always"
      },
      {
        "state_path": "worldSoul",
        "reader": "AscendantSheet",
        "visible_when": "always"
      },
      {
        "state_path": "echoStates",
        "reader": "AscendantSheet",
        "visible_when": "always"
      }
    ],
    "notes": "Full ascendant profile. Identity, echoes, world-soul bonds.\n"
  },
  {
    "surface": "game.identity-chip",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "ascendantIdentity",
        "reader": "IdentityChip",
        "visible_when": "ascendantIdentity !== null"
      }
    ],
    "notes": "Compact identity display. Synchronizes with AscendantBar.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.avatar-hud",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "ascendantIdentity.embodiment",
        "reader": "AvatarHUD",
        "visible_when": "ascendantIdentity embodied (physical avatar present)"
      }
    ],
    "notes": "Avatar-specific HUD. Only when player has a physical presence in the world.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.action-drawer",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "essencePool",
        "reader": "ActionDrawer",
        "visible_when": "always"
      },
      {
        "state_path": "ascendantIdentity",
        "reader": "ActionDrawer",
        "visible_when": "always"
      }
    ],
    "notes": "Player intervention surface. Cards filtered by context. Open/close state exposed\nvia __DEBUG.getActiveUIState().actionDrawerOpen.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.attention-pool-indicator",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "activeThreadTugs",
        "reader": "AttentionPoolIndicator",
        "visible_when": "always"
      }
    ],
    "notes": "Attention tier capacity indicator (THR-19 / attention-tier-model).\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.rivals-button",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "rivalStates",
        "reader": "RivalsButton",
        "visible_when": "always"
      },
      {
        "state_path": "rivalDefinitions",
        "reader": "RivalsButton",
        "visible_when": "always"
      }
    ],
    "notes": "Compact rivals status. Click opens RivalPanel.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.rival-panel",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "rivalStates",
        "reader": "RivalPanel",
        "visible_when": "always"
      },
      {
        "state_path": "rivalDefinitions",
        "reader": "RivalPanel",
        "visible_when": "always"
      }
    ],
    "notes": "Full rival status list.\n"
  },
  {
    "surface": "game.toast-stack",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "tickEvents",
        "reader": "ToastStack",
        "visible_when": "tickEvents with notification directive"
      }
    ],
    "notes": "Transient event notifications. Player-facing only (filtered).\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.alert-bar",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "tickEvents",
        "reader": "AlertBar",
        "visible_when": "tickEvents marked as alert-level"
      }
    ],
    "notes": "Persistent alert row for high-significance events.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.world-pulse",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "phase",
        "reader": "WorldPulse",
        "visible_when": "always"
      },
      {
        "state_path": "tick",
        "reader": "WorldPulse",
        "visible_when": "always"
      }
    ],
    "notes": "World atmospheric state indicator — phase, tick rate, pressure.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.live-location-bar",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "graph",
        "reader": "LiveLocationBar",
        "visible_when": "a hex or location is selected"
      }
    ],
    "notes": "Context strip showing currently-focused location or hex name.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.chronicle-panel",
    "view": "game",
    "mount": "always",
    "reads": [
      {
        "state_path": "chronicleEntries",
        "reader": "ChroniclePanel",
        "visible_when": "always"
      }
    ],
    "notes": "Rolling chronicle feed of tier-3 events.\n",
    "openUrl": "/?view=game&seeded"
  },
  {
    "surface": "game.hex-detail-view",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "HexDetailView",
        "visible_when": "hex is selected"
      },
      {
        "state_path": "hexRevelation",
        "reader": "HexDetailView",
        "visible_when": "always"
      }
    ],
    "notes": "Expanded view of a selected hex. Drives HexBreadcrumb, HexSidebar, HexChronicle.\n"
  },
  {
    "surface": "game.hex-breadcrumb",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "HexBreadcrumb",
        "visible_when": "hex or location is selected"
      }
    ],
    "notes": "Navigation breadcrumb for hex → location → sublocation drill.\n"
  },
  {
    "surface": "game.hex-sidebar",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "HexSidebar",
        "visible_when": "always"
      }
    ],
    "notes": "Sidebar listing contents of selected hex.\n"
  },
  {
    "surface": "game.hex-chronicle",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "chronicleEntries",
        "reader": "HexChronicle",
        "visible_when": "always"
      }
    ],
    "notes": "Per-hex chronicle entries filtered to the selected hex.\n"
  },
  {
    "surface": "game.location-view",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "LocationView",
        "visible_when": "location is selected"
      }
    ],
    "notes": "In-place location drill (not the modal). Shows sublocations + inhabitants.\n"
  },
  {
    "surface": "game.retinue-panel",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "RetinuePanel",
        "visible_when": "always"
      },
      {
        "state_path": "unifiedActions",
        "reader": "RetinuePanel",
        "visible_when": "always"
      }
    ],
    "notes": "Threaded (bonded) agents in player's retinue. Core portfolio-scan UI.\n"
  },
  {
    "surface": "game.threads-panel",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "ThreadsPanel",
        "visible_when": "always"
      }
    ],
    "notes": "Player's woven threads (relationships, stakes). Click opens ThreadDetailView.\n"
  },
  {
    "surface": "game.thread-detail-view",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "ThreadDetailView",
        "visible_when": "always"
      }
    ],
    "notes": "Single thread detail: participants, stakes, history.\n"
  },
  {
    "surface": "game.strand-view",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "StrandView",
        "visible_when": "always"
      }
    ],
    "notes": "Strand visualization — subset of thread view focused on specific entity pairs.\n"
  },
  {
    "surface": "game.agent-info-card",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "graph",
        "reader": "AgentInfoCard",
        "visible_when": "agent is selected"
      },
      {
        "state_path": "agentKnowledge",
        "reader": "AgentInfoCard",
        "visible_when": "always"
      }
    ],
    "notes": "Compact agent card. Lighter than AgentProfileModal; appears in sidebar.\n"
  },
  {
    "surface": "game.location-profile-modal",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "LocationProfileModal",
        "visible_when": "always"
      }
    ],
    "notes": "Full location profile: prosperity, factions, agents, structures.\n"
  },
  {
    "surface": "game.agent-profile-modal",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "AgentProfileModal",
        "visible_when": "always"
      },
      {
        "state_path": "agentKnowledge",
        "reader": "AgentProfileModal",
        "visible_when": "always"
      }
    ],
    "notes": "Full agent dossier with backstory strata, intelligence, traits.\n"
  },
  {
    "surface": "game.agent-intelligence-panel",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "intelligenceRecords",
        "reader": "AgentIntelligencePanel",
        "visible_when": "always"
      }
    ],
    "notes": "Intelligence-on-this-agent submodal (THR-141).\n"
  },
  {
    "surface": "game.faction-sheet",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "FactionSheet",
        "visible_when": "always"
      },
      {
        "state_path": "dynamicFactionDefinitions",
        "reader": "FactionSheet",
        "visible_when": "always"
      }
    ],
    "notes": "Full faction profile: rank structure, agenda, members, trust.\n"
  },
  {
    "surface": "game.army-sheet",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "ArmySheet",
        "visible_when": "always"
      }
    ],
    "notes": "Full army profile: composition, morale, position, objective.\n"
  },
  {
    "surface": "game.artifact-sheet",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "ArtifactSheet",
        "visible_when": "always"
      }
    ],
    "notes": "Full artifact profile: origin, properties, bearer history.\n"
  },
  {
    "surface": "game.harvest-screen",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "chronicle",
        "reader": "HarvestScreen",
        "visible_when": "always"
      },
      {
        "state_path": "echoStates",
        "reader": "HarvestScreen",
        "visible_when": "always"
      },
      {
        "state_path": "worldSoul",
        "reader": "HarvestScreen",
        "visible_when": "always"
      },
      {
        "state_path": "cycle",
        "reader": "HarvestScreen",
        "visible_when": "always"
      }
    ],
    "notes": "End-of-cycle harvest ritual. Only appears when phase === 'harvest'.\n"
  },
  {
    "surface": "game.intervention-confirm",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "essencePool",
        "reader": "InterventionConfirm",
        "visible_when": "always"
      }
    ],
    "notes": "Divine intervention confirmation step. Nudge / whisper / vision selection.\n"
  },
  {
    "surface": "game.choice-set-modal",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "unifiedActions",
        "reader": "ChoiceSetModal",
        "visible_when": "active encounter with choice set pending (THR-73)"
      }
    ],
    "notes": "Player choice-set resolution within an encounter.\n"
  },
  {
    "surface": "game.agenda-picker",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "strategicState",
        "reader": "AgendaPicker",
        "visible_when": "always"
      }
    ],
    "notes": "Agenda selection for strategic actions.\n"
  },
  {
    "surface": "game.scry-overlay",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "ScryOverlay",
        "visible_when": "always"
      }
    ],
    "notes": "Scry (divine vision) overlay. Reveals hex contents per scry state.\n"
  },
  {
    "surface": "game.journey-vignette-modal",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "pendingVignettes",
        "reader": "JourneyVignetteModal",
        "visible_when": "pendingVignettes non-empty"
      }
    ],
    "notes": "Journey-beat vignette popup.\n"
  },
  {
    "surface": "game.encounter-veil",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "unifiedActions",
        "reader": "EncounterVeil",
        "visible_when": "watched encounter active"
      },
      {
        "state_path": "graph",
        "reader": "EncounterVeil",
        "visible_when": "always"
      }
    ],
    "notes": "Encounter-in-progress overlay (watched mode).\n"
  },
  {
    "surface": "game.debug-panel",
    "view": "game",
    "mount": "modal",
    "reads": [
      {
        "state_path": "graph",
        "reader": "DebugPanel",
        "visible_when": "always"
      },
      {
        "state_path": "unifiedActions",
        "reader": "DebugPanel",
        "visible_when": "always"
      },
      {
        "state_path": "tickEvents",
        "reader": "DebugPanel",
        "visible_when": "always"
      }
    ],
    "notes": "Dev-only diagnostic panel. Keyboard: ` toggles, F1 opens to CLI tab. Not prod-visible but part of the dev IA.\n"
  },
  {
    "surface": "game.narrative-feed",
    "view": "game",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "recentEvents",
        "reader": "NarrativeFeed",
        "visible_when": "always"
      }
    ],
    "notes": "Rolling narrative prose feed. Drives player's sense of what's happening.\n"
  },
  {
    "surface": "codex.main",
    "view": "codex",
    "mount": "always",
    "reads": [
      {
        "state_path": "(content tables — not GameState)",
        "reader": "Codex",
        "visible_when": "view === 'codex'"
      }
    ],
    "notes": "Browsable catalog of divine actions, possessions, conditions, agreements,\nmortal actions. Content-driven, not game-state-driven. Drives CodexSidebar +\nCodexCard + CodexDetailPanel.\n",
    "openUrl": "/?view=codex"
  },
  {
    "surface": "codex.sidebar",
    "view": "codex",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "(content tables)",
        "reader": "CodexSidebar",
        "visible_when": "always"
      }
    ],
    "notes": "Codex category nav.\n"
  },
  {
    "surface": "codex.detail-panel",
    "view": "codex",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "(selected content item)",
        "reader": "CodexDetailPanel",
        "visible_when": "always"
      }
    ],
    "notes": "Codex item detail view.\n"
  },
  {
    "surface": "styleguide.main",
    "view": "styleguide",
    "mount": "always",
    "reads": [
      {
        "state_path": "(none — static component samples)",
        "reader": "StyleGuide",
        "visible_when": "view === 'styleguide'"
      }
    ],
    "notes": "Visual component reference at src/components/StyleGuide/StyleGuide.tsx.\nAll shared primitives rendered with sample data.\n",
    "openUrl": "/?view=styleguide"
  },
  {
    "surface": "cms.content-browser",
    "view": "cms",
    "mount": "always",
    "reads": [
      {
        "state_path": "(content tables — not GameState)",
        "reader": "ContentBrowser",
        "visible_when": "view === 'cms'"
      }
    ],
    "notes": "Top-level CMS browser. Drives CMSMainPanel + CMSDetailPanel.\n",
    "openUrl": "/?view=cms"
  },
  {
    "surface": "cms.main-panel",
    "view": "cms",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "(content table selection)",
        "reader": "CMSMainPanel",
        "visible_when": "always"
      }
    ],
    "notes": "CMS table view — active content table being browsed.\n"
  },
  {
    "surface": "cms.detail-panel",
    "view": "cms",
    "mount": "drillin",
    "reads": [
      {
        "state_path": "(content item selection)",
        "reader": "CMSDetailPanel",
        "visible_when": "always"
      }
    ],
    "notes": "CMS item detail view.\n"
  }
];
